# Generated by Django 2.2.10 on 2020-05-18 15:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScoreCheckerUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.CharField(help_text='Email extracted from resume', max_length=30, unique=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, help_text='Mobile extracted from resume', max_length=20, null=True, verbose_name='Mobile')),
                ('total_score', models.PositiveIntegerField(default=0, null=True)),
                ('section_scores', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
