# Generated by Django 2.2.10 on 2020-06-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumescorechecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescorecheckeruserdetails',
            name='candidate_id',
            field=models.CharField(blank=True, help_text='Candidate id stored here', max_length=50, null=True, verbose_name='Candidate_Id'),
        ),
        migrations.AlterField(
            model_name='resumescorecheckeruserdetails',
            name='email',
            field=models.CharField(blank=True, help_text='Email extracted from resume', max_length=30, null=True, verbose_name='Email'),
        ),
    ]
