export const FETCH_SESSION_AVAILABILITY = 'FETCH_SESSION_AVAILABILITY'

export const FETCH_CART_COUNT = 'FETCH_CART_COUNT'

export const CART_COUNT_FETCHED = 'CART_COUNT_FETCHED'

export const FETCH_CANDIDATE_INFO = 'CANDIDATE_INFO_FETCHED'
