
export const FETCH_PERSONAL_INFO  = 'FETCH_PERSONAL_INFO';

export const UPDATE_PERSONAL_INFO  = 'UPDATE_PERSONAL_INFO';

export const SAVE_USER_INFO  = 'SAVE_USER_INFO';

export const FETCH_IMAGE_URL = 'FETCH_IMAGE_URL';

export const FETCH_INTEREST_LIST = 'FETCH_INTEREST_LIST';

export const SAVE_INTEREST_LIST = 'SAVE_INTEREST_LIST';

export const UPDATE_SUMMARY_WITH_SUGGESTION = 'UPDATE_SUMMARY_WITH_SUGGESTION';

export const UPDATE_ENTITY_PREFERENCE = 'UPDATE_ENTITY_PREFERENCE'

export const HIDE_SUBSCRIBE_BUTTON = 'HIDE_SUBSCRIBE_BUTTON'


