

FUNCTIONALAREA = [
 {u'pdesc': u'Finance / Accounts / Investment Banking',
  u'pid': 10007},
 {u'pdesc': u'Customer Service / Back Office Operations',
  u'pid': 10014},
 {u'pdesc': u'IT - Software',
  u'pid': 10013},
 {u'pdesc': u'Production / Maintenance / Service',
  u'pid': 10018},
 {u'pdesc': u'Sales / BD',
  u'pid': 10033},
 {u'pdesc': u'IT - Hardware / Networking / Telecom Engineering',
  u'pid': 10012},
 {u'pdesc': u'Engineering Design / Construction',
  u'pid': 10011},
 {u'pdesc': u'Administration / Front Office / Secretary',
  u'pid': 10001},
 {u'pdesc': u'Marketing / Advertising / MR / PR / Events',
  u'pid': 10020},
 {u'pdesc': u'Quality / Testing (QA-QC)',
  u'pid': 10028},
 {u'pdesc': u'Education / Training / Language',
  u'pid': 10005},
 {u'pdesc': u'Architecture / Interior Design',
  u'pid': 10055},
 {u'pdesc': u'Civil Services / Military / Police',
  u'pid': 10004},
 {u'pdesc': u'Environment / Health / Safety',
  u'pid': 10050},
 {u'pdesc': u'Graphic Design / Web Design / Copywriting',
  u'pid': 10056},
 {u'pdesc': u'Hotel / Restaurant',
  u'pid': 10009},
 {u'pdesc': u'HR / Recruitment',
  u'pid': 10010},
 {u'pdesc': u'Journalism / Content / Writing',
  u'pid': 10015},
 {u'pdesc': u'Legal / Company Secretary',
  u'pid': 10016},
 {u'pdesc': u'Management Consulting / Strategy / EA',
  u'pid': 10017},
 {u'pdesc': u'Medical / Healthcare',
  u'pid': 10008},
 {u'pdesc': u'Oil & Gas Engineering / Mining / Geology',
  u'pid': 10047},
 {u'pdesc': u'R&D / Product Design',
  u'pid': 10034},
 {u'pdesc': u'Real Estate',
  u'pid': 10030},
 {u'pdesc': u'Retail / Export-Import / Trading',
  u'pid': 10042},
 {u'pdesc': u'SBU Head / CEO / Director / Entrepreneur',
  u'pid': 10040},
 {u'pdesc': u'Security / Detective Services',
  u'pid': 10035},
 {u'pdesc': u'Statistics / Analytics / Acturial Science',
  u'pid': 10049},
 {u'pdesc': u'Supply Chain / Purchase / Inventory',
  u'pid': 10038},
 {u'pdesc': u'Travel / Aviation / Merchant Navy',
  u'pid': 10003},
 {u'pdesc': u'TV / Film / Radio / Entertainment',
  u'pid': 10046},
 {u'pdesc': u'Other',
  u'pid': 10044},
 {u'pdesc': u'Certified Telecom Professionals',
  u'pid': 10057}
]

SKILL = [
 {u'pdesc': u'Finance / Accounts / Investment Banking',
  u'pid': 10007},
 {u'pdesc': u'Customer Service / Back Office Operations',
  u'pid': 10014},
 {u'pdesc': u'IT - Software',
  u'pid': 10013},
 {u'pdesc': u'Production / Maintenance / Service',
  u'pid': 10018},
 {u'pdesc': u'Sales / BD',
  u'pid': 10033},
 {u'pdesc': u'IT - Hardware / Networking / Telecom Engineering',
  u'pid': 10012},
 {u'pdesc': u'Engineering Design / Construction',
  u'pid': 10011},
 {u'pdesc': u'Administration / Front Office / Secretary',
  u'pid': 10001},
 {u'pdesc': u'Marketing / Advertising / MR / PR / Events',
  u'pid': 10020},
 {u'pdesc': u'Quality / Testing (QA-QC)',
  u'pid': 10028},
 {u'pdesc': u'Education / Training / Language',
  u'pid': 10005},
 {u'pdesc': u'Architecture / Interior Design',
  u'pid': 10055},
 {u'pdesc': u'Civil Services / Military / Police',
  u'pid': 10004},
 {u'pdesc': u'Environment / Health / Safety',
  u'pid': 10050},
 {u'pdesc': u'Graphic Design / Web Design / Copywriting',
  u'pid': 10056},
 {u'pdesc': u'Hotel / Restaurant',
  u'pid': 10009},
 {u'pdesc': u'HR / Recruitment',
  u'pid': 10010},
 {u'pdesc': u'Journalism / Content / Writing',
  u'pid': 10015},
 {u'pdesc': u'Legal / Company Secretary',
  u'pid': 10016},
 {u'pdesc': u'Management Consulting / Strategy / EA',
  u'pid': 10017},
 {u'pdesc': u'Medical / Healthcare',
  u'pid': 10008},
 {u'pdesc': u'Oil & Gas Engineering / Mining / Geology',
  u'pid': 10047},
 {u'pdesc': u'R&D / Product Design',
  u'pid': 10034},
 {u'pdesc': u'Real Estate',
  u'pid': 10030},
 {u'pdesc': u'Retail / Export-Import / Trading',
  u'pid': 10042},
 {u'pdesc': u'SBU Head / CEO / Director / Entrepreneur',
  u'pid': 10040},
 {u'pdesc': u'Security / Detective Services',
  u'pid': 10035},
 {u'pdesc': u'Statistics / Analytics / Acturial Science',
  u'pid': 10049},
 {u'pdesc': u'Supply Chain / Purchase / Inventory',
  u'pid': 10038},
 {u'pdesc': u'Travel / Aviation / Merchant Navy',
  u'pid': 10003},
 {u'pdesc': u'TV / Film / Radio / Entertainment',
  u'pid': 10046},
 {u'pdesc': u'Other',
  u'pid': 10044},
 {u'pdesc': u'Certified Telecom Professionals',
  u'pid': 10057}
]

AREA_WITH_LABEL = [('', 'Functional Area')] + [(area['pid'], area['pdesc']) for area in FUNCTIONALAREA]

SKILL_WITH_LABEL = [('', 'Key Skills')] + [(skill['pid'], skill['pdesc']) for skill in SKILL]
