

SEARCH_STOPWORDS_LOOKUP = {
    'limited': '',
    'ltd': '',
    'all': '',
    'and': '',
    'incorporate': '',
    'being': '',
    'over': '',
    'against': '',
    'through': '',
    'its': '',
    'before': '',
    'how': '',
    'iii': '',
    'had': '',
    'should': '',
    'to': '',
    'only': '',
    'jobss': '',
    'has': '',
    'curriculum vitae': '',
    'do': '',
    'them': '',
    'his': '',
    'very': '',
    'cannot': '',
    'they': '',
    'not': '',
    'during': '',
    'him': '',
    'nor': '',
    'did': '',
    'each': '',
    'where': '',
    'because': '',
    'pvt': '',
    'doing': '',
    'some': '',
    'are': '',
    'further': '',
    'what': '',
    'for': '',
    'below': '',
    '/': '',
    'does': '',
    'above': '',
    'between': '',
    'public': '',
    'she': '',
    'we': '',
    'after': '',
    'jobs': '',
    'resume': '',
    'here': '',
    'job': '',
    'by': '',
    'on': '',
    'about': '',
    'her': '',
    'of': '',
    'could': '',
    'ltd': '',
    'or': '',
    'own': '',
    'into': '',
    'down': '',
    'cv': '',
    'from': '',
    'would': '',
    'whom': '',
    'there': '',
    'been': '',
    'few': '',
    'too': '',
    'themselves': '',
    'was': '',
    'until': '',
    '\\': '',
    'more': '',
    'himself': '',
    'both': '',
    'but': '',
    'incorporation': '',
    'off': '',
    'an': '',
    'with': '',
    'than': '',
    'those': '',
    'he': '',
    'me': '',
    'also': '',
    'myself': '',
    'this': '',
    'up': '',
    'will': '',
    'while': '',
    'can': '',
    'were': '',
    'my': '',
    'at': '',
    'have': '',
    'then': '',
    'vi': '',
    'is': '',
    'am': '',
    'mine': '',
    'iv': '',
    'ii': '',
    'as': '',
    'itself': '',
    'experience': '',
    'want': '',
    'in': '',
    'their': '',
    'if': '',
    'these': '',
    'no': '',
    'that': '',
    'when': '',
    'same': '',
    'any': '',
    'till': '',
    'other': '',
    'which': '',
    'so': '',
    'you': '',
    'inc': '',
    'qualification': '',
    'again': '',
    'who': '',
    'most': '',
    'such': '',
    'why': '',
    'incorporated': '',
    'the': '',
    'having': '',
    'once': ''
}
FILLERS = {
    'engineer':True,
    'developer':True,
    'executive':True,
    'leader':True,
    'manager':True,
    'assistant':True,
    'officer':True,
    'consultant':True,
    'associate':True,
    'representative':True,
    'member':True,
    'lead':True,
    'head':True,
    'crew':True,
    'staff':True,
    'expert':True,
    'general':True,
    'employee':True
}
