# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0005_auto_20190207_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.User', verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='userproject',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Project Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userproject',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='resumebuilder.Skill', verbose_name='List of Skills'),
        ),
    ]
