# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-08 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0006_auto_20190208_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='link_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Link Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userachievement',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreference',
            name='reference_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Reference Name'),
            preserve_default=False,
        ),
    ]
