# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-13 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0007_auto_20190208_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='users/'),
        ),
    ]
