# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-04 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0008_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=5, verbose_name='Proficiency'),
        ),
    ]
