# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('resumebuilder', '0012_userlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(
                    choices=[(1, 'LinkedIn'), (2, 'Github'), (3, 'Behance'), (4, 'Dribble'), (5, 'Keggle'), (6, 'NPM'),
                             (7, 'Upwork'), (8, 'PyPI'), (9, 'Stack Overflow')], max_length=10,
                    verbose_name='Link Name')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='extracurricular',
            field=models.CharField(blank=True,
                                   choices=[(0, '3D printing'), (1, 'Acrobatics'), (2, 'Acting'), (3, 'Amateur radio'),
                                            (4, 'Animation'), (5, 'Aquascaping'), (6, 'Baking'), (7, 'Baton twirling'),
                                            (8, 'Beatboxing'), (9, 'Board/tabletop games'), (10, 'Book restoration'),
                                            (11, 'Brazilian jiu-jitsu'), (12, 'Cabaret'), (13, 'Calligraphy'),
                                            (14, 'Candle making'), (15, 'Coffee roasting'), (16, 'Collecting'),
                                            (17, 'Coloring'), (18, 'Computer programming'), (19, 'Cooking'),
                                            (20, 'Cosplaying'), (21, 'Couponing'), (22, 'Creative writing'),
                                            (23, 'Crocheting'), (24, 'Cross-stitch'), (25, 'Crossword puzzles'),
                                            (26, 'Cryptography'), (27, 'Dance'), (28, 'Digital arts'),
                                            (29, 'Do it yourself'), (30, 'Drama'), (31, 'Drawing'), (32, 'Electronics'),
                                            (33, 'Embroidery'), (34, 'Fantasy sports'), (35, 'Fashion'),
                                            (36, 'Fishkeeping'), (37, 'Flower arranging'),
                                            (38, 'Foreign language learning'),
                                            (39, 'Gaming (tabletop games and role-playing games)'), (40, 'Genealogy'),
                                            (41, 'Glassblowing'), (42, 'Graphic design'), (43, 'Gunsmithing'),
                                            (44, 'Herp keeping'), (45, 'Homebrewing'), (46, 'Hydroponics'),
                                            (47, 'Ice skating'), (48, 'Jewelry making'), (49, 'Jigsaw puzzles'),
                                            (50, 'Juggling'), (51, 'Karate'), (52, 'Knife making'), (53, 'Knitting'),
                                            (54, 'Kombucha brewing'), (55, 'Lace making'), (56, 'Lapidary'),
                                            (57, 'Leather crafting'), (58, 'Lego building'), (59, 'Lock Picking'),
                                            (60, 'Listening to music'), (61, 'Machining'), (62, 'Macrame'),
                                            (63, 'Magic'), (64, 'Metalworking'), (65, 'Model building'),
                                            (66, 'Model engineering'), (67, 'Needlepoint'), (68, 'Origami'),
                                            (69, 'Painting'), (70, 'Philately'), (71, 'Photography'),
                                            (72, 'Playing musical instruments'), (73, 'Poi'), (74, 'Pottery'),
                                            (75, 'Puzzles'), (76, 'Quilling'), (77, 'Quilting'), (78, 'Reading'),
                                            (79, 'Robot combat'), (80, 'Scrapbooking'), (81, 'Sculpting'),
                                            (82, 'Sewing'), (83, 'Singing'), (84, 'Sketching'), (85, 'Soapmaking'),
                                            (86, 'Stand-up comedy'), (87, 'Taxidermy'), (88, 'Video game developing'),
                                            (89, 'Video gaming'), (90, 'Video editing'), (91, 'Watching movies'),
                                            (92, 'Watching television'), (93, 'Whittling'), (94, 'Wood carving'),
                                            (95, 'Woodworking'), (96, 'Worldbuilding'), (97, 'Writing'),
                                            (98, 'Yo-yoing'), (99, 'Yoga')], max_length=50, null=True,
                                   verbose_name='Extra Curricular'),
        ),
        migrations.AddField(
            model_name='usersociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.User',
                                    verbose_name='User'),
        ),
    ]
