# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resumebuilder', '0013_auto_20190308_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='User First Name'),
        ),

    ]
