# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0014_auto_20190308_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallink',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExternalLink',
        ),
    ]
