# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0015_auto_20190308_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User First Name'),
        ),
    ]
