# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0016_auto_20190308_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Start Date'),
        ),
    ]
