# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-11 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0017_auto_20190311_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
