# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0018_auto_20190311_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertification',
            name='year_of_certification',
            field=models.IntegerField(verbose_name='Year of Certification'),
        ),
    ]
