# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0020_auto_20190311_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='candidate_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Candidate Id'),
        ),
    ]
