# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('resumebuilder', '0021_user_candidate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Candidate Id')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Candidate First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Candidate Last Name')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Candidate Email')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Candidate Contact Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Candidate Location')),
                ('image', models.FileField(blank=True, null=True, upload_to='users/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True, verbose_name='Gender')),
                ('extracurricular', models.CharField(blank=True, choices=[(0, '3D printing'), (1, 'Acrobatics'), (2, 'Acting'), (3, 'Amateur radio'), (4, 'Animation'), (5, 'Aquascaping'), (6, 'Baking'), (7, 'Baton twirling'), (8, 'Beatboxing'), (9, 'Board/tabletop games'), (10, 'Book restoration'), (11, 'Brazilian jiu-jitsu'), (12, 'Cabaret'), (13, 'Calligraphy'), (14, 'Candle making'), (15, 'Coffee roasting'), (16, 'Collecting'), (17, 'Coloring'), (18, 'Computer programming'), (19, 'Cooking'), (20, 'Cosplaying'), (21, 'Couponing'), (22, 'Creative writing'), (23, 'Crocheting'), (24, 'Cross-stitch'), (25, 'Crossword puzzles'), (26, 'Cryptography'), (27, 'Dance'), (28, 'Digital arts'), (29, 'Do it yourself'), (30, 'Drama'), (31, 'Drawing'), (32, 'Electronics'), (33, 'Embroidery'), (34, 'Fantasy sports'), (35, 'Fashion'), (36, 'Fishkeeping'), (37, 'Flower arranging'), (38, 'Foreign language learning'), (39, 'Gaming (tabletop games and role-playing games)'), (40, 'Genealogy'), (41, 'Glassblowing'), (42, 'Graphic design'), (43, 'Gunsmithing'), (44, 'Herp keeping'), (45, 'Homebrewing'), (46, 'Hydroponics'), (47, 'Ice skating'), (48, 'Jewelry making'), (49, 'Jigsaw puzzles'), (50, 'Juggling'), (51, 'Karate'), (52, 'Knife making'), (53, 'Knitting'), (54, 'Kombucha brewing'), (55, 'Lace making'), (56, 'Lapidary'), (57, 'Leather crafting'), (58, 'Lego building'), (59, 'Lock Picking'), (60, 'Listening to music'), (61, 'Machining'), (62, 'Macrame'), (63, 'Magic'), (64, 'Metalworking'), (65, 'Model building'), (66, 'Model engineering'), (67, 'Needlepoint'), (68, 'Origami'), (69, 'Painting'), (70, 'Philately'), (71, 'Photography'), (72, 'Playing musical instruments'), (73, 'Poi'), (74, 'Pottery'), (75, 'Puzzles'), (76, 'Quilling'), (77, 'Quilting'), (78, 'Reading'), (79, 'Robot combat'), (80, 'Scrapbooking'), (81, 'Sculpting'), (82, 'Sewing'), (83, 'Singing'), (84, 'Sketching'), (85, 'Soapmaking'), (86, 'Stand-up comedy'), (87, 'Taxidermy'), (88, 'Video game developing'), (89, 'Video gaming'), (90, 'Video editing'), (91, 'Watching movies'), (92, 'Watching television'), (93, 'Whittling'), (94, 'Wood carving'), (95, 'Woodworking'), (96, 'Worldbuilding'), (97, 'Writing'), (98, 'Yo-yoing'), (99, 'Yoga')], max_length=50, null=True, verbose_name='Extra Curricular')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Extra Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('date', models.DateField(verbose_name='Date')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_certification', models.CharField(max_length=250, verbose_name='Certification Name')),
                ('year_of_certification', models.IntegerField(verbose_name='Year of Certification')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, verbose_name='Specialization')),
                ('institution_name', models.CharField(max_length=250, verbose_name='Institution Name')),
                ('course_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CR', 'Correspondence')], max_length=2, verbose_name='Institution Name')),
                ('percentage_cgpa', models.CharField(max_length=250, verbose_name='Percentage Or CGPA')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_pursuing', models.BooleanField(verbose_name='Still Pursuing')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(max_length=100, verbose_name='Job Profile')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_working', models.BooleanField(verbose_name='Present')),
                ('job_location', models.CharField(max_length=100, verbose_name='Job Location')),
                ('work_description', models.TextField(verbose_name='Job Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Language Name')),
                ('proficiency', models.IntegerField(default=3, verbose_name='Proficiency')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, verbose_name='Project Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=150, verbose_name='Reference Name')),
                ('reference_designation', models.CharField(max_length=150, verbose_name='Reference Designation')),
                ('about_candidate', models.TextField(verbose_name='About Candidate')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(choices=[(1, 'LinkedIn'), (2, 'Github'), (3, 'Behance'), (4, 'Dribble'), (5, 'Keggle'), (6, 'NPM'), (7, 'Upwork'), (8, 'PyPI'), (9, 'Stack Overflow')], max_length=10, verbose_name='Link Name')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate')),
            ],
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercertification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usereducation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlanguage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersociallink',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='UserCertification',
        ),
        migrations.DeleteModel(
            name='UserEducation',
        ),
        migrations.DeleteModel(
            name='UserExperience',
        ),
        migrations.DeleteModel(
            name='UserLanguage',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
        migrations.DeleteModel(
            name='UserReference',
        ),
        migrations.DeleteModel(
            name='UserSocialLink',
        ),
        migrations.AddField(
            model_name='candidateproject',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='resumebuilder.Skill', verbose_name='List of Skills'),
        ),
        migrations.AddField(
            model_name='skill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate',
                                    verbose_name='Candidate'),
            preserve_default=False,
        ),
    ]
