# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-02 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0022_auto_20190402_1611'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='candidate',
        #     name='gender',
        #     field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=1, null=True, verbose_name='Gender'),
        # ),
        # migrations.AlterField(
        #     model_name='candidate',
        #     name='image',
        #     field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Candidate Image Url'),
        # ),
    ]
