# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0024_auto_20190403_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateproject',
            name='currently_working',
            field=models.BooleanField(default=False, verbose_name='Currently Working'),
        ),
    ]
