# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0025_candidateproject_currently_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatelanguage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
