# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0027_auto_20190416_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='entity_preference_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
