# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import resumebuilder.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0028_candidate_entity_preference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCustomisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_no', models.SmallIntegerField(default=1)),
                ('color', models.SmallIntegerField(choices=[(1, 'Black')], default=1)),
                ('font_size', models.SmallIntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=1)),
                ('entity_position', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
            ],
            bases=(resumebuilder.mixins.PreviewImageCreationMixin, models.Model),
        ),
        migrations.AddField(
            model_name='candidate',
            name='selected_template',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Selected Template'),
        ),
        migrations.AlterField(
            model_name='candidateachievement',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='is_pursuing',
            field=models.BooleanField(default=False, verbose_name='Still Pursuing'),
        ),
        migrations.AlterField(
            model_name='candidateeducation',
            name='percentage_cgpa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Percentage Or CGPA'),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='is_working',
            field=models.BooleanField(default=False, verbose_name='Present'),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='job_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Location'),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='work_description',
            field=models.TextField(blank=True, null=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='candidateproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='about_candidate',
            field=models.TextField(blank=True, null=True, verbose_name='About Candidate'),
        ),
        migrations.AddField(
            model_name='ordercustomisation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate'),
        ),
    ]
