# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-23 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0029_auto_20190522_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercustomisation',
            old_name='font_size',
            new_name='heading_font_size',
        ),
        migrations.AddField(
            model_name='ordercustomisation',
            name='text_font_size',
            field=models.SmallIntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=1),
        ),
    ]
