# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-10 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0030_auto_20190523_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateachievement',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='candidateproject',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='candidateproject',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='ordercustomisation',
            name='color',
            field=models.SmallIntegerField(choices=[(1, 'Green'), (2, 'Blue'), (3, 'Red'), (4, 'Black'), (5, 'Yellow'), (6, 'Purple')], default=1),
        ),
    ]
