# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0031_auto_20190610_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='extracurricular',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Extra Curricular'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Candidate Location'),
        ),
        migrations.AlterField(
            model_name='candidateachievement',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='candidateachievement',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='job_location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Job Location'),
        ),
    ]
