# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-20 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0033_auto_20190614_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateeducation',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree'),
        ),
    ]
