# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-20 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0034_candidateeducation_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducation',
            name='course_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CR', 'Correspondence'), ('NA', 'NA')], max_length=2, verbose_name='Institution Name'),
        ),
    ]
