# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0035_auto_20190620_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hide_subscribe_button',
            field=models.BooleanField(default=False, verbose_name='Hide SubscribeButton'),
        ),
    ]
