# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0036_candidate_hide_subscribe_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='hide_subscribe_button',
        ),
    ]
