# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0037_remove_candidate_hide_subscribe_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='upload_resume',
            field=models.BooleanField(default=True, verbose_name='Upload Resume'),
        ),
    ]
