# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0038_candidate_upload_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_generated',
            field=models.BooleanField(default=True, verbose_name='Resume Generated'),
        ),
    ]
