# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0039_candidate_resume_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_download_count',
            field=models.IntegerField(default=0),
        ),
    ]
