# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-28 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0040_candidate_resume_download_count'),
        ('resumebuilder', '0038_candidate_upload_resume'),
    ]

    operations = [
    ]
