# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_merge_20191121_1839'),
        ('resumebuilder', '0041_merge_20191128_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResumeOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_status', models.SmallIntegerField(choices=[(1, 'Free Resume Created'), (2, 'Service Resume Created')], default=-1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='resume_download_count',
            new_name='resume_creation_count',
        ),
        migrations.AddField(
            model_name='candidateresumeoperations',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumebuilder.Candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='candidateresumeoperations',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
