# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0042_auto_20191203_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='active_subscription',
            field=models.BooleanField(default=False, verbose_name='Active Subscription'),
        ),
    ]
