# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('page', models.PositiveIntegerField(choices=[(1, 'Homepage'), (2, 'Roundone')], default=1)),
                ('user_id', models.CharField(max_length=100, verbose_name='User ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.TextField(max_length=1024)),
                ('rating', models.DecimalField(decimal_places=2, default=2.5, max_digits=8)),
                ('designation', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/testimonial/', verbose_name='Profile Image')),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TopTrending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('view_all', models.CharField(help_text='provide full url to redirect on click.', max_length=255)),
                ('is_jobassistance', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
