# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='trendingcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.TopTrending'),
        ),
        migrations.AddField(
            model_name='toptrending',
            name='products',
            field=models.ManyToManyField(related_name='trendingcourses', through='homepage.TrendingProduct', to='shop.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='trendingproduct',
            unique_together=set([('trendingcourse', 'product')]),
        ),
    ]
