# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170707_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toptrending',
            name='view_all',
            field=models.CharField(help_text='provide full url with http:// to redirect on click.', max_length=255),
        ),
    ]
