# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20170714_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='page',
            field=models.PositiveIntegerField(choices=[(1, 'Homepage'), (2, 'Roundone'), (3, 'Course Catalogue')], default=1),
        ),
    ]
