# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20181001_1219'),
        ('homepage', '0004_auto_20180201_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Testimonial for skill pages', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='shop.Category', verbose_name='University-Category'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='page',
            field=models.PositiveIntegerField(choices=[(0, '--Select Page--'), (1, 'Homepage'), (2, 'Roundone'), (3, 'Course Catalogue'), (4, 'University Page')], default=0),
        ),
    ]
