# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180201_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='page',
            field=models.PositiveIntegerField(choices=[(0, '--Select Page--'), (1, 'Homepage'), (2, 'Roundone'), (3, 'Course Catalogue'), (4, 'University Page')], default=0),
        ),
    ]
