# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20181008_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='page',
            field=models.PositiveIntegerField(choices=[(0, '--Select Page--'), (1, 'Homepage'), (2, 'Roundone'), (3, 'Course Catalogue'), (4, 'University Page'), (5, 'University Course')], default=0),
        ),
    ]
