# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-13 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20181206_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermAndAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.PositiveIntegerField(choices=[(1, 'Privacy Policy'), (2, 'Terms & Condition'), (3, 'Disclaimer')], default=0, help_text='page id')),
                ('content', models.TextField(help_text='html content', verbose_name='content')),
            ],
        ),
    ]
