# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-18 06:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_termandagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termandagreement',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='html content', verbose_name='content'),
        ),
    ]
