# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-20 10:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20190918_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticSiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.PositiveIntegerField(choices=[(1, 'Privacy Policy'), (2, 'Terms and Condition'), (3, 'Disclaimer')], default=-1, help_text='page id')),
                ('content', ckeditor.fields.RichTextField(help_text='html content', verbose_name='content')),
            ],
        ),
        migrations.DeleteModel(
            name='TermAndAgreement',
        ),
    ]
