# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_auto_20191230_1324'),
        ('homepage', '0009_auto_20190920_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptrending',
            name='fa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.FunctionalArea', unique=True),
        ),
    ]
