# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-17 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_auto_20191216_1948'),
        ('homepage', '0009_auto_20190920_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='page',
            field=models.PositiveIntegerField(choices=[(0, '--Select Page--'), (1, 'Homepage'), (2, 'Roundone'), (3, 'Course Catalogue'), (6, 'Skill Page'), (4, 'University Page'), (5, 'University Course')], default=0),
        ),
        migrations.AddField(
            model_name='testimonialcategoryrelationship',
            name='testimonial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Testimonial'),
        ),
    ]
