# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-30 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_auto_20191230_1324'),
        ('homepage', '0010_toptrending_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toptrending',
            name='fa',
        ),
        migrations.AddField(
            model_name='toptrending',
            name='fa',
            field=models.ManyToManyField(blank=True, null=True, to='shop.FunctionalArea'),
        ),
    ]
