# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20191230_1331'),
        ('homepage', '0010_auto_20191217_1228'),
    ]

    operations = [
    ]
