# Generated by Django 2.2.10 on 2020-05-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_merge_20200514_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Offer Name')),
                ('sticky_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Offer Sticky Text')),
                ('offer_value', models.CharField(blank=True, help_text="For eg. 'Upto 30%' off!' or 'Flat 20%' off!'", max_length=100, null=True, verbose_name='Offer value Text')),
                ('banner_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Offer Banner Text')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
