# Generated by Django 2.2.10 on 2020-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_merge_20200420_1106'),
        ('homepage', '0013_merge_20200430_1635'),
    ]

    operations = [
    ]
