# Generated by Django 2.2.10 on 2020-05-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_homepageoffer'),
        ('homepage', '0013_merge_20200430_1635'),
    ]

    operations = [
    ]
