# Generated by Django 2.2.10 on 2020-06-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_merge_20200514_1418'),
        ('homepage', '0014_merge_20200519_1907'),
    ]

    operations = [
    ]
