# Generated by Django 2.2.10 on 2020-06-08 21:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_merge_20200609_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageoffer',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 21, 54, 22, 255900, tzinfo=utc), verbose_name='End Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepageoffer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 21, 54, 29, 503470, tzinfo=utc), verbose_name='Start Time'),
            preserve_default=False,
        ),
    ]
