# Generated by Django 2.2.10 on 2020-07-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20200609_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSpecialTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('display_name', models.CharField(max_length=25, unique=True, verbose_name='Display Name')),
                ('skill_page_url', models.CharField(blank=True, max_length=60, verbose_name='URL of Skill Page')),
                ('tag', models.CharField(blank=True, help_text="For eg. 'New' or 'Limited time offer'", max_length=100, null=True, verbose_name='Tag on Display Name ')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/mobile/homepage/', verbose_name='Mobile Icon')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
