# Generated by Django 2.2.10 on 2021-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_navigationspecialtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageoffer',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/homepage/', verbose_name='desktop Icon'),
        ),
        migrations.AddField(
            model_name='homepageoffer',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mobile/homepage/', verbose_name='Mobile Icon'),
        ),
        # migrations.AlterField(
        #     model_name='navigationspecialtag',
        #     name='tag',
        #     field=models.CharField(blank=True, help_text="For eg. 'New' or 'Limited time offer'. Recommended 'New' only", max_length=100, null=True, verbose_name='Tag on Display Name (Optional)'),
        # ),
        # migrations.AlterField(
        #     model_name='staticsitecontent',
        #     name='page_type',
        #     field=models.PositiveIntegerField(choices=[(1, 'Privacy Policy'), (2, 'Terms and Conditions'), (3, 'Disclaimer')], default=-1, help_text='page id'),
        # ),
    ]
