OPERATION_TYPE = ((0, 'Vendor Document Upload'),
      )

QUEUE_NAME = ((0, 'Default'),
              (1, 'Order List'),
              (2, 'Midout List'),
              (3, 'Inbox'),
              (4, 'Replaced Order'),
              (5, 'Approval'),
              (6, 'Approved'),
              (7, 'Rejected by Admin'),
              (8, 'Rejected by Candidate'),
              (9, 'Booster'),
              (10, 'Whatsapp Jobs'),
              (11, 'Certification/Assessment'),
              (12, 'Domestic Profile Update'),
              (13, 'Domestic Profile Approval'),
              (14, 'Domestic Profile Initiated'),
              (15, 'International Profile Update'),
              (16, 'International Profile Approval'),
              (17, 'Allocated'),
              (18, 'Closed Orderitems'),
              (19, 'Partner Inbox'),
              (20, 'Hold Items'),
              (21, 'Verification Reports'),
              (22, 'Order Detail'),
              (23, 'Welcome Call Queue View'),
              (24, 'Welcome Call Assigned'),
              (25, 'Welcome CallBack'),
              (26, 'Welcome Call Service Issue'),
              (27, 'Welcome Call Closed'),

              #linkedin queues

              (28, 'Linkedin Inbox '),
              (29, 'Linkedin Rejected by Candidate'),
              (30, 'Linkedin Rejected by Admin'),
              (31, 'Linkedin Approval'),
              (31, 'Linkedin Approved'),
              )