OPERATION_TYPE = ((0, 'Not Uploaded'),
      (1, 'Candidate Resume Upload'),
      (2, 'Draft 1 Send'),
      (3, 'Draft 2 Send'),
      (4, 'Closed'),
      (5, 'Admin Rejected'),
      (6, 'Candidate Rejected'),
      (7, 'Pending Admin Approval'),
      (8, 'Assigned'),
      (9, 'Booster Emails Sent'),
      (10, 'Resume Sent Door Step'),
      (11, 'Service Started'),
      (12, 'Profile Updated'),
      (13, 'Candidate Rejection with upload'),
      (14, 'Pending Report Upload'),
      )
