# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review', '0002_auto_20170718_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPageWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.CharField(blank=True, help_text='comma(,) comma separated e.g. 123,145, ...', max_length=500, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
