# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 07:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20180201_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1500, verbose_name='Content'),
        ),
    ]
