# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20180201_1308'),
        ('review', '0003_detailpagewidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpagewidget',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Widget'),
        ),
    ]
