# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-22 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_detailpagewidget_widget'),
        ('review', '0004_auto_20180209_1324'),
    ]

    operations = [
    ]
