# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_merge_20180222_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpagewidget',
            name='object_id',
        ),
        migrations.AddField(
            model_name='detailpagewidget',
            name='listid',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=6),
        ),
    ]
