# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20180313_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpagewidget',
            name='listid',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, help_text='Give comma separeted id like 1,2,3 .. in product, blog and skill', max_length=66, null=True, size=6),
        ),
    ]
