# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20180329_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Title'),
        ),
    ]
