# Generated by Django 2.2.10 on 2020-05-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20200514_1311'),
    ]

    operations = [
    ]
