# Generated by Django 2.2.10 on 2020-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20200430_1649'),
        ('review', '0010_auto_20200420_1116'),
    ]

    operations = [
    ]
