# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0003_draft_cd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='key_skills',
            field=models.CharField(blank=True, help_text='comma separated(,) separated skills, e.g. java, python, ...', max_length=2000, null=True),
        ),
    ]
