# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0004_auto_20170919_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(-1, '---------'), (0, 'School'), (1, 'College')], default=1),
        ),
    ]
