export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_PRODUCT_IDS = 'GET_PRODUCT_IDS'
export const SAVE_PRODUCT_IDS = 'SAVE_PRODUCT_IDS'
export const REQUEST_FREE_RESUME = 'REQUEST_FREE_RESUME'
export const POLLING_FREE_RESUME = 'POLLING_FREE_RESUME'
export const DOWNLOAD_FREE_RESUME = 'DOWNLOAD_FREE_RESUME'