export const FETCH_TEMPLATE = 'FETCH_TEMPLATE'
export const SAVE_TEMPLATE = 'SAVE_TEMPLATE'
export const FETCH_MODAL_STATUS = 'FETCH_MODAL_STATUS'
export const UPDATE_MODAL_STATUS = 'UPDATE_MODAL_STATUS'