# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('heading', models.CharField(max_length=255, verbose_name='chapter')),
                ('answer', models.TextField(verbose_name='answer')),
                ('ordering', models.PositiveSmallIntegerField(blank=True, help_text='An integer used to order the chapter             amongst others related to the same chapter. If not given this             chapter will be last in the list.', verbose_name='ordering')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentheading', to='faq.Chapter', verbose_name='parentchapter')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'ordering': ('heading',),
            },
        ),
        migrations.CreateModel(
            name='FAQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('text', models.TextField(help_text='The actual question itself.', verbose_name='question')),
                ('answer', models.TextField(blank=True, help_text='The answer text.', verbose_name='answer')),
                ('status', models.IntegerField(choices=[(2, 'Active'), (1, 'Inactive'), (0, 'Moderation')], default=0, help_text="Only questions with their status set to 'Active' will be displayed.", verbose_name='status')),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like the question to be displayed.', verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'Frequent asked question',
                'verbose_name_plural': 'Frequently asked questions',
                'ordering': ['sort_order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='A short description of this topic.', verbose_name='description')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TopicChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='Sort Order')),
                ('active', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='faq.Chapter')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='faq.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='chapters',
            field=models.ManyToManyField(blank=True, through='faq.TopicChapter', to='faq.Chapter', verbose_name='Topic Chapter'),
        ),
    ]
