# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 10:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('heading', models.CharField(max_length=255, verbose_name='chapter')),
                ('answer', ckeditor.fields.RichTextField(blank=True, help_text='The answer text.', verbose_name='answer')),
                ('ordering', models.PositiveSmallIntegerField(default=1, help_text='An integer used to order the chapter             amongst others related to the same chapter. If not given this             chapter will be last in the list.', verbose_name='ordering')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentheading', to='faq.Chapter', verbose_name='parentchapter')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_vendor', to='partner.Vendor')),
            ],
            options={
                'verbose_name': 'chapter',
                'ordering': ('heading',),
                'verbose_name_plural': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='FAQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(help_text='The actual question itself.', verbose_name='question')),
                ('answer', ckeditor.fields.RichTextField(blank=True, help_text='The answer text.', verbose_name='answer')),
                ('status', models.IntegerField(choices=[(2, 'Active'), (1, 'Inactive'), (0, 'Moderation')], default=0, help_text="Only questions with their status set to 'Active' will be displayed.", verbose_name='status')),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like the question to be displayed.', verbose_name='sort order')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_vendor', to='partner.Vendor')),
            ],
            options={
                'verbose_name': 'Frequent asked question',
                'ordering': ['sort_order', 'created'],
                'verbose_name_plural': 'Frequently asked questions',
            },
        ),
    ]
