# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.IntegerField(choices=[(2, 'Active'), (1, 'Inactive'), (0, 'Moderation')], default=0, help_text="Only questions with their status set to 'Active' will be displayed.", verbose_name='status'),
        ),
    ]
