# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faquestion',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_vendor', to='partner.Vendor'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentheading', to='faq.Chapter', verbose_name='parentchapter'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_vendor', to='partner.Vendor'),
        ),
    ]
