# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20170419_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentheading', to='faq.Chapter', verbose_name='parentchapter'),
        ),
        migrations.AlterField(
            model_name='faquestion',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicchapter',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
