# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20170419_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentheading', to='faq.Chapter', verbose_name='parentchapter'),
        ),
    ]
