# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20170718_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='screenchapter',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='screenchapter',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='ScreenChapter',
        ),
    ]
