# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20170809_1504'),
        ('faq', '0004_auto_20170728_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='faquestion',
            name='public_vendor',
            field=models.ManyToManyField(blank=True, related_name='public_question', to='partner.Vendor', verbose_name='Public To Vendor'),
        ),
    ]
