# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20170419_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicchapters', to='faq.Chapter'),
        ),
        migrations.AlterField(
            model_name='topicchapter',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicchapters', to='faq.Topic'),
        ),
    ]
