# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('negative_marking', models.FloatField(default=0.0)),
                ('levels', models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (5, 'N.A')])),
                ('question_type', models.PositiveSmallIntegerField(choices=[(1, 'MCQ(SINGLE)'), (2, 'MCQ(MULTIPLE)')])),
                ('question_options', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='comprehension',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='test_section',
        ),
        migrations.AlterField(
            model_name='comprehensionsection',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprehensionsection',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AddField(
            model_name='question',
            name='comprehension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.ComprehensionSection'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.TestSection'),
        ),
    ]
