# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20190524_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestSection',
            new_name='Section',
        ),
        migrations.RenameModel(
            old_name='ComprehensionSection',
            new_name='SubSection',
        ),
    ]
