# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20190524_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='levels',
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (5, 'N.A')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='comprehension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.SubSection'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MCQ(SINGLE)'), (2, 'MCQ(MULTIPLE)')], default=1),
        ),
    ]
