# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20190524_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test_section',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='comprehension',
            new_name='subsection',
        ),
    ]
