# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20190524_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_info',
            field=models.CharField(default='', max_length=255),
        ),
    ]
