# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20190725_1745'),
        ('assessment', '0007_test_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcourse', to='shop.Product'),
        ),
    ]
