# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_test_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
