# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_auto_20190806_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='negative_marking',
            new_name='negative_marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='weight',
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1),
        ),
    ]
