# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20190905_1238'),
        ('assessment', '0010_auto_20190807_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondarycategories', to='shop.Category'),
        ),
    ]
