# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20190905_1238'),
        ('assessment', '0011_test_secondary_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='secondary_categories',
        ),
        migrations.AddField(
            model_name='test',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='testcategories', to='shop.Category'),
        ),
    ]
