export const FETCH_TEMPLATE = 'FETCH_TEMPLATE'
export const SAVE_TEMPLATE = 'SAVE_TEMPLATE'
export const SET_SELECTED_TEMPLATE = 'SET_SELECTED_TEMPLATE'
export const CUSTOMIZE_TEMPLATE = 'CUSTOMIZE_TEMPLATE'