export const GET_CANDIDATE_ID = 'GET_CANDIDATE_ID';
export const LOGIN_CANDIDATE = 'LOGIN_CANDIDATE';
export const GET_HOME_COMPONENT_TITLE = 'GET_HOME_COMPONENT_TITLE';
export const FEEDBACK_SUBMIT = 'FEEDBACK_SUBMIT';
