# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('question1', models.CharField(blank=True, max_length=500, verbose_name='Question1')),
                ('anser1', models.CharField(blank=True, max_length=500, verbose_name='Answer1')),
                ('question2', models.CharField(blank=True, max_length=500, verbose_name='Question2')),
                ('anser2', models.CharField(blank=True, max_length=500, verbose_name='Answer2')),
                ('question3', models.CharField(blank=True, max_length=500, verbose_name='Question3')),
                ('anser3', models.CharField(blank=True, max_length=500, verbose_name='Answer3')),
                ('question4', models.CharField(blank=True, max_length=500, verbose_name='Question4')),
                ('anser4', models.CharField(blank=True, max_length=500, verbose_name='Answer4')),
                ('question5', models.CharField(blank=True, max_length=500, verbose_name='Question5')),
                ('anser5', models.CharField(blank=True, max_length=500, verbose_name='Answer5')),
                ('oi', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
            ],
        ),
    ]
