# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('shine_id', models.CharField(max_length=255, unique=True, verbose_name='shine_id')),
            ],
        ),
    ]
