# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuser',
            name='shine_id',
            field=models.CharField(max_length=255, verbose_name='shine_id'),
        ),
    ]
