# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170802_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuser',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='cpuser',
            name='cp_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='cpid'),
        ),
        migrations.AddField(
            model_name='cpuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='shine_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='shine_id'),
        ),
        migrations.AlterField(
            model_name='cpuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='username'),
        ),
    ]
