export const FETCH_MY_SERVICES = "FETCH_MY_SERVICES";
export const MY_SERVICES_FETCHED = 'MY_SERVICES_FETCHED';

// pending resume action
export const GET_PENDING_RESUME = 'GET_PENDING_RESUME';
export const PENDING_RESUME_FETCHED = 'PENDING_RESUME_FETCHED';

// upload resume action
export const UPLOAD_RESUME_FORM = 'UPLOAD_RESUME_FORM';

//fetch pending resumes
export const FETCH_PENDING_RESUMES = 'FETCH_PENDING_RESUMES'
export const PENDING_RESUMES_FETCHED = 'PENDING_RESUMES_FETCHED'


//Accept Reject
export const REQUEST_CANDIDATE_OI_ACCEPT_REJECT = 'REQUEST_CANDIDATE_OI_ACCEPT_REJECT'
export const CANDIDATE_OI_ACCEPT_REJECT_SUCCESS = 'CANDIDATE_OI_ACCEPT_REJECT_SUCCESS'

//Pause and Resume Service
export const PAUSE_AND_RESUME_SERVICE_REQUEST = 'PAUSE_AND_RESUME_SERVICE_REQUEST'
export const PAUSE_AND_RESUME_SERVICE_SUCCESS = 'PAUSE_AND_RESUME_SERVICE_SUCCESS'

//Fetch OI details
export const FETCH_OI_DETAILS = 'FETCH_OI_DETAILS'
export const OI_DETAILS_FETCHED = 'OI_DETAILS_FETCHED'

// update service comment count
export const UPDATE_SERVICE_COMMENT_COUNT = 'UPDATE_SERVICE_COMMENT_COUNT'

// update resume shine action
export const UPDATE_RESUME_SHINE = 'UPDATE_RESUME_SHINE';
