export const FETCH_MY_SERVICES = "FETCH_MY_SERVICES"
export const MY_SERVICES_FETCHED = 'MY_SERVICES_FETCHED'

// upload resume action
export const UPLOAD_RESUME_FORM = 'UPLOAD_RESUME_FORM';

// order item comment
export const GET_OI_COMMENT = 'GET_OI_COMMENT'
export const OI_COMMENT_FAILED = 'OI_COMMENT_FAILED'
export const OI_COMMENT_SUCCESS = 'OI_COMMENT_SUCCESS'

// review feedback
// export const SUBMIT_DASHBOARD_REVIEWS = 'SUBMIT_DASHBOARD_REVIEWS'
// export const SUBMIT_DASHBOARD_FAILED = 'SUBMIT_DASHBOARD_FAILED'
// export const SUBMIT_DASHBOARD_SUCCESS = 'SUBMIT_DASHBOARD_SUCCESS'

// fetch reviews
export const FETCH_MY_REVIEWS = "FETCH_MY_REVIEWS"
export const SUBMIT_DASHBOARD_FAILED = 'SUBMIT_DASHBOARD_FAILED'
export const SUBMIT_DASHBOARD_SUCCESS = 'SUBMIT_DASHBOARD_SUCCESS'