export const FETCH_MY_SERVICES = "FETCH_MY_SERVICES";
export const MY_SERVICES_FETCHED = 'MY_SERVICES_FETCHED';

// pending resume action
export const GET_PENDING_RESUME = 'GET_PENDING_RESUME';
export const PENDING_RESUME_FETCHED = 'PENDING_RESUME_FETCHED';

// upload resume action
export const UPLOAD_RESUME_FORM = 'UPLOAD_RESUME_FORM';

//Accept Reject

export const REQUEST_CANDIDATE_OI_ACCEPT_REJECT = 'REQUEST_CANDIDATE_OI_ACCEPT_REJECT'
export const CANDIDATE_OI_ACCEPT_REJECT_SUCCESS = 'CANDIDATE_OI_ACCEPT_REJECT_SUCCESS'
