# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Name of Currency', max_length=100, verbose_name='Name')),
                ('value', models.PositiveIntegerField(help_text='Integer Value', verbose_name='Value')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Exchange')),
                ('offset', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Offset')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='country',
            name='offset',
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countrycurrency', to='geolocation.Currency', verbose_name='Currency'),
        ),
    ]
