# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20170511_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.PositiveIntegerField(choices=[(0, 'Rs.'), (1, '$'), (2, 'AED'), (3, 'GBP')], default=0, help_text='Symbol', verbose_name='Symbol'),
        ),
    ]
