# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_country_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='profile_url',
            field=models.CharField(blank=True, help_text='comma separated(,) profile url, e.g. www.test1.com, www.test2.com', max_length=400, null=True),
        ),
    ]
