# Generated by Django 2.2.10 on 2020-04-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_auto_20200430_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
