# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Current Value'),
        ),
    ]
