# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpoint',
            name='cw_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='CP Credits'),
        ),
    ]
