# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20170926_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created'], 'permissions': (('console_add_remove_wallet_point', 'Can Add/Remove Wallet Point'),), 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='added_by',
            field=models.IntegerField(null=True),
        ),
    ]
