# Generated by Django 2.2.10 on 2020-06-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0098_merge_20200609_0209'),
        ('wallet', '0005_add_added_by_id_in_wallet_transation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_id', models.CharField(max_length=20)),
                ('redeem_options', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
