# Generated by Django 2.2.10 on 2020-06-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0098_merge_20200609_0209'),
        ('wallet', '0006_productpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpoint',
            name='order_id',
        ),
        migrations.AddField(
            model_name='productpoint',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_order', to='order.Order'),
        ),
    ]
