# Generated by Django 2.2.10 on 2020-06-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20200611_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpoint',
            name='candidate_id',
            field=models.CharField(max_length=50),
        ),
    ]
