export const FETCH_USER_SKILL = 'FETCH_USER_SKILL';
export const SAVE_USER_SKILL = 'SAVE_USER_SKILL';
export const UPDATE_USER_SKILL = 'UPDATE_USER_SKILL';
export const DELETE_USER_SKILL = 'DELETE_USER_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const HANDLE_SKILL_SWAP = 'HANDLE_SKILL_SWAP';
