export const  FETCH_TRENDING_COURSES_AND_SKILLS = 'FETCH_TRENDING_COURSES_AND_SKILLS'

export const TRENDING_COURSES_AND_SKILLS_FETCHED = 'TRENDING_COURSES_AND_SKILLS_FETCHED'

export const  FETCH_POPULAR_COURSES = 'FETCH_POPULAR_COURSES'

export const POPULAR_COURSES_FETCHED = 'POPULAR_COURSES_FETCHED'