export const FETCH_USER_AWARD = 'FETCH_USER_AWARD';
export const SAVE_USER_AWARD = 'SAVE_USER_AWARD';
export const UPDATE_USER_AWARD = 'UPDATE_USER_AWARD';
export const DELETE_USER_AWARD = 'DELETE_USER_AWARD';
export const REMOVE_AWARD = 'REMOVE_AWARD';
export const HANDLE_AWARD_SWAP = 'HANDLE_AWARD_SWAP';
