export const FETCH_USER_COURSE = 'FETCH_USER_COURSE';
export const SAVE_USER_COURSE = 'SAVE_USER_COURSE';
export const UPDATE_USER_COURSE = 'UPDATE_USER_COURSE';
export const DELETE_USER_COURSE = 'DELETE_USER_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const BULK_UPDATE_USER_COURSE = 'BULK_UPDATE_USER_COURSE';
