# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicroSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MicrositeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image')),
                ('image_alt', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, help_text='Append http://', null=True)),
                ('position', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024, null=True)),
                ('answer', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('type_of_page', models.PositiveSmallIntegerField(choices=[(1, 'Home Page'), (2, 'Listing Page'), (3, 'Detail Page')])),
            ],
        ),
        migrations.CreateModel(
            name='PartnerTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=255, null=True)),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.TextField(max_length=1024)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('added_on', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('microsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microsite.MicroSite')),
            ],
        ),
    ]
