# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertestimonial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User(if any)'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='banner_image',
            field=models.ManyToManyField(blank=True, to='microsite.MicrositeBanner'),
        ),
        migrations.AddField(
            model_name='partnerfaq',
            name='microsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microsite.MicroSite'),
        ),
        migrations.AddField(
            model_name='microsite',
            name='detail_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_page', to='microsite.PartnerPage'),
        ),
        migrations.AddField(
            model_name='microsite',
            name='home_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page', to='microsite.PartnerPage'),
        ),
        migrations.AddField(
            model_name='microsite',
            name='listing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_page', to='microsite.PartnerPage'),
        ),
    ]
