export const FETCH_SIDENAV_STATUS ='FETCH_SIDENAV_STATUS'
export const UPDATE_SIDENAV_STATUS = 'UPDATE_SIDENAV_STATUS';
export const FETCH_LIST_LINK = 'FETCH_LIST_LINK_'
export const UPDATE_LIST_LINK = 'UPDATE_LIST_LINK'
export const UPDATE_CURRENT_LINK_POS = 'UPDATE_CURRENT_LINK_POS'