export const START_SKILL_PAGE_LOADER = 'START_SKILL_PAGE_LOADER';

export const STOP_SKILL_PAGE_LOADER = 'STOP_SKILL_PAGE_LOADER';

// dashboard wallet loader
export const START_DASHBOARD_WALLET_PAGE_LOADER = 'START_DASHBOARD_WALLET_PAGE_LOADER';

export const STOP_DASHBOARD_WALLET_PAGE_LOADER = 'STOP_DASHBOARD_WALLET_PAGE_LOADER';

// dashboard order loader
export const START_DASHBOARD_ORDER_PAGE_LOADER = 'START_DASHBOARD_ORDER_PAGE_LOADER';

export const STOP_DASHBOARD_ORDER_PAGE_LOADER = 'STOP_DASHBOARD_ORDER_PAGE_LOADER';

// dashboard courses loader
export const START_DASHBOARD_COURSES_PAGE_LOADER = 'START_DASHBOARD_COURSES_PAGE_LOADER';

export const STOP_DASHBOARD_COURSES_PAGE_LOADER = 'STOP_DASHBOARD_COURSES_PAGE_LOADER';

// dashboard services loader
export const START_DASHBOARD_SERVICES_PAGE_LOADER = 'START_DASHBOARD_SERVICES_PAGE_LOADER';

export const STOP_DASHBOARD_SERVICES_PAGE_LOADER = 'STOP_DASHBOARD_SERVICES_PAGE_LOADER';

// comment Loader
export const START_COMMENT_LOADER = 'START_COMMENT_LOADER';

export const STOP_COMMENT_LOADER = 'STOP_COMMENT_LOADER';
