export const START_SKILL_PAGE_LOADER = 'START_SKILL_PAGE_LOADER';

export const STOP_SKILL_PAGE_LOADER = 'STOP_SKILL_PAGE_LOADER';

export const START_DASHBOARD_WALLET_PAGE_LOADER = 'START_DASHBOARD_WALLET_PAGE_LOADER';

export const STOP_DASHBOARD_WALLET_PAGE_LOADER = 'STOP_DASHBOARD_WALLET_PAGE_LOADER';