export const START_SKILL_PAGE_LOADER = 'START_SKILL_PAGE_LOADER';

export const STOP_SKILL_PAGE_LOADER = 'STOP_SKILL_PAGE_LOADER';

// dashboard wallet loader
export const START_DASHBOARD_WALLET_PAGE_LOADER = 'START_DASHBOARD_WALLET_PAGE_LOADER';

export const STOP_DASHBOARD_WALLET_PAGE_LOADER = 'STOP_DASHBOARD_WALLET_PAGE_LOADER';

// dashboard order loader
export const START_DASHBOARD_ORDER_PAGE_LOADER = 'START_DASHBOARD_ORDER_PAGE_LOADER';

export const STOP_DASHBOARD_ORDER_PAGE_LOADER = 'STOP_DASHBOARD_ORDER_PAGE_LOADER';

// dashboard courses loader
export const START_DASHBOARD_COURSES_PAGE_LOADER = 'START_DASHBOARD_COURSES_PAGE_LOADER';

export const STOP_DASHBOARD_COURSES_PAGE_LOADER = 'STOP_DASHBOARD_COURSES_PAGE_LOADER';