export const FETCH_SESSION_AVAILABILITY = 'FETCH_SESSION_AVAILABILITY'

export const FETCH_CART_COUNT = 'FETCH_CART_COUNT'

export const CART_COUNT_FETCHED = 'CART_COUNT_FETCHED'

export const FETCH_CANDIDATE_INFO = 'CANDIDATE_INFO_FETCHED'

export const FETCH_NAVIGATION_OFFERS_AND_SPECIAL_TAGS = 'FETCH_NAVIGATION_OFFERS_AND_SPECIAL_TAGS'

export const NAVIGATION_OFFERS_AND_SPECIAL_TAGS_FETCHED = 'NAVIGATION_OFFERS_AND_SPECIAL_TAGS_FETCHED'