export const FETCH_USER_PROJECT = 'FETCH_USER_PROJECT';
export const SAVE_USER_PROJECT = 'SAVE_USER_PROJECT';
export const UPDATE_USER_PROJECT = 'UPDATE_USER_PROJECT';
export const DELETE_USER_PROJECT = 'DELETE_USER_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const BULK_UPDATE_USER_PROJECT = 'BULK_UPDATE_USER_PROJECT';

