# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_desc', models.TextField(blank=True, default='', verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Keywords')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Set name for slug generation.', max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text="Used to build the tag's URL.", max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('image', models.FileField(blank=True, help_text='use this banner image', max_length=200, null=True, upload_to='images/blog/', verbose_name='Image')),
                ('image_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='content for blog.', null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('allow_comment', models.BooleanField(default=False)),
                ('no_comment', models.PositiveIntegerField(default=0)),
                ('comment_moderated', models.PositiveIntegerField(default=0)),
                ('no_views', models.PositiveIntegerField(default=0)),
                ('no_shares', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='popularity score', max_digits=10)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-score', '-publish_date'],
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_desc', models.TextField(blank=True, default='', verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Keywords')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Image Alt')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Used to build the category's URL.", max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority'],
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_desc', models.TextField(blank=True, default='', verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Keywords')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Image Alt')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Used to build the tag's URL.", max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
    ]
