# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='display_name',
            field=models.CharField(blank=True, help_text='Set title for blog.', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(help_text='Set name for slug generation.', max_length=200, verbose_name='Name'),
        ),
    ]
