# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text="Used to build the category's URL.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text="Used to build the tag's URL.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
