# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='candidate_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
