# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='blog',
            name='comment_moderated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
