# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replied_to',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
