# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170412_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='content for blog.', null=True),
        ),
    ]
