# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-03 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170707_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority']},
        ),
    ]
