# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170412_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text="Used to build the tag's URL.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
