# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20170903_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_desc', models.TextField(blank=True, default='', verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Keywords')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Used to build the author's URL.", max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('visibility', models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'Both')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty')),
                ('image', models.FileField(blank=True, help_text='use this category image', max_length=200, null=True, upload_to='images/blog/author/', verbose_name='Profile Image')),
                ('image_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, default='', verbose_name='About Author')),
                ('designation', models.CharField(blank=True, max_length=255, verbose_name='Designation')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_author_created_by', related_query_name='blog_authors', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_author_last_modified_by', related_query_name='blog_authors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='for user or writer', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-score', '-publish_date'], 'permissions': (('console_change_learning_article', 'Can Change Learning Article From Console'), ('console_change_talent_article', 'Can Change Talent Article From Console'))},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='sites',
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Summary Article'),
        ),
        migrations.AddField(
            model_name='blog',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'Both')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, help_text='use this category image', max_length=200, null=True, upload_to='images/blog/category/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'Both')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AddField(
            model_name='tag',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'Both')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, help_text='for author', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
