# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171122_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fb_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='LinkedIN'),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter'),
        ),
    ]
