# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170412_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-score', '-publish_date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='sites where blog published.', related_name='related_sites', to='sites.Site'),
        ),
    ]
