# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-09 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20180201_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='address',
            field=models.TextField(blank=True, default='Conclave or job fair address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='blog',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speakers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='sponsor_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog/sponsor/', verbose_name='Sponsor Image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='venue',
            field=models.CharField(blank=True, help_text='Location', max_length=255, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='author',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'HR-Insider'), (4, 'HR-Conclave'), (5, 'HR-Jobfair')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'HR-Insider'), (4, 'HR-Conclave'), (5, 'HR-Jobfair')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AlterField(
            model_name='category',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'HR-Insider'), (4, 'HR-Conclave'), (5, 'HR-Jobfair')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'HR-Insider'), (4, 'HR-Conclave'), (5, 'HR-Jobfair')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
    ]
