# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180409_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'HR-Blogger'), (4, 'HR-Conclave'), (5, 'HR-Jobfair')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='address',
            field=models.TextField(blank=True, help_text='Conclave or job fair address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speakers', to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'HR-Blogger'), (4, 'HR-Conclave'), (5, 'HR-Jobfair')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AlterField(
            model_name='category',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'HR-Blogger'), (4, 'HR-Conclave'), (5, 'HR-Jobfair')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'ShineLearning'), (2, 'TalentEconomy'), (3, 'HR-Blogger'), (4, 'HR-Conclave'), (5, 'HR-Jobfair')], default=1, help_text='sites where blog published.', verbose_name='Site Visibilty'),
        ),
    ]
