# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180410_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=255, verbose_name='City'),
        ),
    ]
