# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, help_text='use this category image', max_length=200, null=True, upload_to='images/blog/author/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='use this banner image', max_length=200, null=True, upload_to='images/blog/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='use this category image', max_length=200, null=True, upload_to='images/blog/category/', verbose_name='Image'),
        ),
    ]
