# Generated by Django 2.2.10 on 2020-10-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='related_arts',
            field=models.TextField(default='[]'),
        ),
    ]
