
export const FETCH_LATEST_BLOG = 'FETCH_LATEST_BLOG';   
export const LATEST_BLOG_FETCHED = 'LATEST_BLOG_FETCHED';

export const FETCH_MOST_VIEWED_PRODUCTS = 'FETCH_MOST_VIEWED_PRODUCTS';
export const MOST_VIEWED_PRODUCTS_FETCHED = 'MOST_VIEWED_PRODUCTS_FETCHED';

export const FETCH_IN_DEMAND_PRODUCTS = '_FETCH_IN_DEMAND_PRODUCTS';
export const IN_DEMAND_PRODUCTS_FETCHED = 'IN_DEMAND_PRODUCTS_FETCHED';

export const FETCH_JOB_ASSISTANCE_SERVICES = 'FETCH_JOB_ASSISTANCE_SERVICES';
export const JOB_ASSISTANCE_SERVICES_FETCHED = 'JOB_ASSISTANCE_SERVICES_FETCHED';