# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20170718_1236'),
        ('cart', '0003_lineitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon', verbose_name='Coupon'),
        ),
    ]
