# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='added_on',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
