# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170516_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open - currently active but no owner'), (1, 'Merged - merged in other cart'), (2, 'Saved - currently active but with owner'), (4, 'Frozen - the cart cannot be modified'), (5, 'Closed - order has been made'), (6, 'Archive - cart need to be archived')], default=0, verbose_name='Status'),
        ),
    ]
