# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20170517_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open - currently active but no owner'), (1, 'Merged - merged in other cart'), (2, 'Saved - currently active but with owner'), (3, 'Express - currently active'), (4, 'Frozen - the cart cannot be modified'), (5, 'Closed - order has been made'), (6, 'Archive - cart need to be archived')], default=0, verbose_name='Status'),
        ),
    ]
