# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_deliveryservice_active'),
        ('cart', '0005_auto_20170801_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='delivery_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lineitems', to='shop.DeliveryService'),
        ),
    ]
