# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20170821_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
