# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_lineitem_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Country'),
        ),
    ]
