# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20170912_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Invalid'), (0, 'Failed'), (1, 'Processed'), (2, 'Expired')], default=-1),
        ),
    ]
