# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
