# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_subscription_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='lead_archive',
            field=models.BooleanField(default=False),
        ),
    ]
