# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cart_lead_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_page',
            field=models.BooleanField(default=False),
        ),
    ]
