# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cart_payment_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='lead_created',
            field=models.BooleanField(default=False),
        ),
    ]
