# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20190725_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='last_status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Open - currently active but no owner'), (1, 'Merged - merged in other cart'), (2, 'Saved - currently active but with owner'), (3, 'Express - currently active'), (4, 'Frozen - the cart cannot be modified'), (5, 'Closed - order has been made'), (6, 'Archive - cart need to be archived')], default=None, null=True, verbose_name='Last Status'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open - currently active but no owner'), (1, 'Merged - merged in other cart'), (2, 'Saved - currently active but with owner'), (3, 'Express - currently active'), (4, 'Frozen - the cart cannot be modified'), (5, 'Closed - order has been made'), (6, 'Archive - cart need to be archived')], default=0, verbose_name='Status'),
        ),
    ]
