# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20190806_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='utm_params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
