# Generated by Django 2.2.10 on 2020-05-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_cart_utm_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='site',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Shine Learning'), (1, 'Resume Shine')], default=0, verbose_name='Site Status'),
        ),
    ]
