# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0007_auto_20170821_1322'),
        ('order', '0019_auto_20170831_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTxn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('txn', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Failure'), (3, 'Aborted'), (4, 'Invalid'), (5, 'CANCEL')], default=0)),
                ('payment_mode', models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Cash'), (3, 'EMI'), (4, 'Cheque or Draft'), (5, 'CC-Avenue'), (6, 'Mobikwik'), (7, 'CC-Avenue-International'), (8, 'Debit Card'), (9, 'Credit Card'), (10, 'Net Banking'), (11, 'Emi')], default=0)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=12, null=True, verbose_name='Currency')),
                ('instrument_number', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_issue_date', models.CharField(blank=True, max_length=255, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carttxns', to='cart.Cart', verbose_name='Cart')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordertxns', to='order.Order', verbose_name='Order')),
            ],
        ),
    ]
