# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttxn',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='paymenttxn',
            name='txn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
