# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170831_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttxn',
            name='txn_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Txn Amount'),
        ),
        migrations.AlterField(
            model_name='paymenttxn',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Failure'), (3, 'Aborted'), (4, 'Invalid'), (5, 'Cancel')], default=0),
        ),
    ]
