# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20170901_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttxn',
            name='payment_mode',
            field=models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Cash'), (2, 'Citrus Pay'), (3, 'EMI'), (4, 'Cheque or Draft'), (5, 'CC-Avenue'), (6, 'Mobikwik'), (7, 'CC-Avenue-International'), (8, 'Debit Card'), (9, 'Credit Card'), (10, 'Net Banking')], default=0),
        ),
        migrations.AlterField(
            model_name='paymenttxn',
            name='txn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
