# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20170908_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttxn',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Failure'), (3, 'Aborted'), (4, 'Invalid'), (5, 'Cancel'), (6, 'Refunded')], default=0),
        ),
    ]
