# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20170913_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttxn',
            name='txn_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction info'),
        ),
        migrations.AlterField(
            model_name='paymenttxn',
            name='currency',
            field=models.PositiveIntegerField(choices=[(0, 'Rs.'), (1, '$'), (2, 'AED'), (3, 'GBP')], default=0, verbose_name='Currency'),
        ),
    ]
