# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20170927_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttxn',
            name='txn_info',
            field=models.TextField(default=0, verbose_name='Transaction info'),
            preserve_default=False,
        ),
    ]
