# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-22 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20190417_1751'),
        ('payment', '0009_auto_20190411_1731'),
    ]

    operations = [
    ]
