export const FETCH_MY_COURSES = "FETCH_MY_COURSES"
export const MY_COURSES_FETCHED = 'MY_COURSES_FETCHED'

export const BOARD_NEO_USER = 'BOARD_NEO_USER'
export const UPDATE_COURSE_COMMENT_COUNT = 'UPDATE_COURSE_COMMENT_COUNT' 