export const FETCH_USER_REFERENCE = 'FETCH_USER_REFERENCE';
export const SAVE_USER_REFERENCE = 'SAVE_USER_REFERENCE';
export const UPDATE_USER_REFERENCE = 'UPDATE_USER_REFERENCE';
export const DELETE_USER_REFERENCE = 'DELETE_USER_REFERENCE';
export const REMOVE_REFERENCE = 'REMOVE_REFERENCE';
export const HANDLE_REFERENCE_SWAP = 'HANDLE_REFERENCE_SWAP';
