# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0003_auto_20170720_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=75)),
                ('phn_number', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=200)),
                ('lead_source', models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Skill Page'), (2, 'Detail Page')], default=0)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Country')),
            ],
            options={
                'ordering': ['-modified'],
                'verbose_name_plural': 'User Queries',
            },
        ),
    ]
