# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdServerLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(default='91', max_length=10, verbose_name='Country Code')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('source', models.PositiveSmallIntegerField(choices=[(21, 'AdServerLead')], default=21)),
                ('url', models.CharField(blank=True, max_length=800, null=True)),
                ('created', models.BooleanField(default=False)),
                ('inactive', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userquries',
            name='lead_created',
            field=models.BooleanField(default=False),
        ),
    ]
