# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0002_auto_20171005_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquries',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userquries',
            name='medium',
            field=models.SmallIntegerField(choices=[(0, 'Desktop'), (1, 'Mobile')], default=0),
        ),
        migrations.AddField(
            model_name='userquries',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userquries',
            name='lead_source',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Skill Page'), (2, 'Detail Page'), (6, 'Marketing')], default=0),
        ),
        migrations.AlterField(
            model_name='userquries',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userquries',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
