# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0003_auto_20171006_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquries',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
