# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0006_auto_20171107_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquries',
            name='campaign_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userquries',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquries',
            name='utm_parameter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userquries',
            name='lead_source',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Skill Page'), (2, 'Course Detail Page'), (8, 'Resume Detail Page'), (3, 'Contact Us Page'), (6, 'Marketing'), (7, 'CMS Page')], default=0),
        ),
    ]
