# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0007_auto_20171117_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquries',
            name='campaign_slug',
        ),
        migrations.RemoveField(
            model_name='userquries',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='userquries',
            name='utm_parameter',
        ),
        migrations.AddField(
            model_name='adserverlead',
            name='utm_parameter',
            field=models.TextField(blank=True, default='', verbose_name='utm_parameter'),
        ),
        migrations.AlterField(
            model_name='userquries',
            name='lead_source',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Skill Page'), (2, 'Detail Page'), (3, 'Contact Us Page'), (6, 'Marketing'), (7, 'CMS Page')], default=0),
        ),
    ]
