# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0008_auto_20171120_1227'),
        ('crmapi', '0008_auto_20171120_1833'),
    ]

    operations = [
    ]
