# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-22 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0010_auto_20171121_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquries',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquries',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquries',
            name='lead_source',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Skill Page'), (2, 'Detail Page'), (3, 'Contact Us Page'), (4, 'SEM'), (7, 'CMS Page'), (21, 'AdServerLead')], default=0),
        ),
    ]
