# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0011_auto_20171122_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquries',
            name='lead_source',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Skill Page'), (2, 'Course Detail Page'), (3, 'Contact Us Page'), (4, 'SEM'), (6, 'Chat Lead'), (7, 'CMS Page'), (8, 'Resume Detail Page'), (20, 'Miss Call Lead'), (21, 'AdServerLead'), (26, 'Email Marketing Course Leads'), (27, 'Email Marketing Resume Leads'), (22, 'CartLead')], default=0),
        ),
    ]
