# Generated by Django 2.2.10 on 2020-05-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0014_auto_20190806_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquries',
            name='site',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Shinelearning'), (1, 'ResumeShine.com')], default=0),
        ),
    ]
