

CRON_TO_ID_MAPPING = {
    1: 'add_server_lead_uploader',
    2: 'cart_lead_uploader',
    3: 'cart_drop_out_mail',
    4: 'cashback_mailers',
    5: 'closeorders',
    6: 'featured_profile',
    7: 'feedback_cron',
    8: 'linkedin_tips_email',
    9: 'order_closer',
    10: 'reminder_draft_sms',
    11: 'reminder_mail_and_sms',
    12: 'reminder_mail_for_linkedin',
    13: 'resume_booster',
    14: 'roundone_daily_sale',
    15: 'order_finance_report',
    16: 'order_paid_sms_cron',
    17: 'set_allocated_date_orderitem',
    18: 'update_order_item_closed_date',
    19: 'update_product_buy_count',
    20: 'index_products',
    21: 'update_autocomplete',
    22: 'course_catalogue_cache_set',
    23: 'crm_product_update',
    24: 'jobs_from_shine_to_product',
    25: 'product_fix_seo',
    26: 'product_is_indexed_update',
    27: 'products_review_update',
    28: 'generate_writer_invoice',
    29: 'wallet_expire_daily',
    30: 'ltv_users'
}