export const GET_CANDIDATE_ID = 'GET_CANDIDATE_ID';
export const LOGIN_CANDIDATE = 'LOGIN_CANDIDATE';
export const FEEDBACK_SUBMIT = 'FEEDBACK_SUBMIT';
export const GET_HOME_COMPONENT_TITLE = 'GET_HOME_COMPONENT_TITLE';
export const CHECK_SESSION_AVAILABILITY = 'CHECK_SESSION_AVAILABILITY';
export const GET_CANDIDATE_SHINE_DETAILS = 'GET_CANDIDATE_SHINE_DETAILS';



