export const FETCH_USER_EDUCATION = 'FETCH_USER_EDUCATION';
export const SAVE_USER_EDUCATION = 'SAVE_USER_EDUCATION';
export const UPDATE_USER_EDUCATION = 'UPDATE_USER_EDUCATION';
export const DELETE_USER_EDUCATION = 'DELETE_USER_EDUCATION';
export const REMOVE_EDUCATION = 'REMOVE_EDUCATION';
export const HANDLE_EDUCATION_SWAP = 'HANDLE_EDUCATION_SWAP';
export const BULK_U_C_USER_EDUCATION = 'BULK_U_C_USER_EDUCATION';
