# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 05:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meta.models
import shop.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_desc', models.TextField(blank=True, default='', verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Keywords')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Image Alt')),
                ('name', models.CharField(help_text='Unique name going to decide the slug', max_length=100, verbose_name='Name')),
                ('slug', models.CharField(help_text='Unique slug', max_length=100, unique=True, verbose_name='Slug')),
                ('email', models.EmailField(help_text='Email Address', max_length=100, unique=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, help_text='Mobile Number', max_length=20, verbose_name='Mobile Number')),
                ('address', models.TextField(blank=True, default='', help_text='Address', verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_vendor, verbose_name='Image')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_vendor, verbose_name='Icon')),
                ('pan', models.CharField(blank=True, help_text='PAN No.', max_length=20, verbose_name='PAN No.')),
                ('website', models.CharField(blank=True, help_text='Website', max_length=20, verbose_name='Website.')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnercity', to='geolocation.City', verbose_name='City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnercountry', to='geolocation.Country', verbose_name='Country')),
            ],
            options={
                'get_latest_by': 'created',
                'verbose_name_plural': 'Vendors',
                'ordering': ('-modified', '-created'),
                'verbose_name': 'Vendor',
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
        migrations.CreateModel(
            name='VendorHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('designation', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('vendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorset', to='partner.Vendor', verbose_name='Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='employees',
            field=models.ManyToManyField(blank=True, through='partner.VendorHierarchy', to=settings.AUTH_USER_MODEL, verbose_name='Vendor Hierarchy'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerstate', to='geolocation.State', verbose_name='State'),
        ),
    ]
