# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorhierarchy',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='vendorhierarchy',
            name='vendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorset', to='partner.Vendor', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnercity', to='geolocation.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnercountry', to='geolocation.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='employees',
            field=models.ManyToManyField(blank=True, through='partner.VendorHierarchy', to=settings.AUTH_USER_MODEL, verbose_name='Vendor Hierarchy'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerstate', to='geolocation.State', verbose_name='State'),
        ),
    ]
