# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorhierarchy',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
