# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170718_1236'),
        ('partner', '0002_auto_20170707_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='prd_add_class',
            field=models.ManyToManyField(blank=True, to='shop.ProductClass', verbose_name='Product Add-Types'),
        ),
    ]
