# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_vendor_prd_add_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cp_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='CP Owner'),
        ),
    ]
