# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20170809_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(help_text='Email Address', max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
