# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20170809_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(help_text='Email Address', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Unique name going to decide the slug', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
