# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-05 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.functions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0008_vendor_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('skill', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, default=2018, null=True)),
                ('candidate_email', models.EmailField(help_text='Candidate Email Address', max_length=255, verbose_name='Email')),
                ('candidate_mobile', models.CharField(blank=True, help_text='Candidate Mobile Number', max_length=20, verbose_name='Mobile Number')),
                ('candidate_name', models.CharField(blank=True, help_text='Candidate Name', max_length=20, verbose_name='Name')),
                ('candidate_id', models.CharField(blank=True, help_text='Candidate ID', max_length=30, verbose_name='Candidate ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Certificate')),
                ('user', models.ForeignKey(blank=True, help_text='Created By', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='badge_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_badge_file, verbose_name='Badge Image'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set([('name', 'vendor_provider')]),
        ),
    ]
