# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20180405_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificate',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2019, null=True),
        ),
    ]
