# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20180227_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificate',
            name='user',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='provider',
            field=models.CharField(max_length=128),
        ),
    ]
