# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-07 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0010_auto_20180228_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
