# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-18 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20190123_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterRecruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('recruiter_list', models.TextField(help_text='Recruiter name')),
                ('type_recruiter', models.PositiveIntegerField(choices=[(0, 'Resume Booster India'), (1, 'Resume Booster International')], default=0, help_text='Recruiter type for booster service', verbose_name='Recruiter Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
