# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_usercertificate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='provider',
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Vendor'),
        ),
    ]
