# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-27 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_boosterrecruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('pixel_slug', models.CharField(help_text='Pixel Slug', max_length=255)),
                ('conversion_urls', models.TextField(help_text='conversion_page_url')),
                ('landing_urls', models.TextField(help_text='landing_page_urls')),
                ('days', models.IntegerField(help_text='No. of days for tracking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
