# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-03 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_boosterrecruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='certificate_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
