# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_auto_20190116_1640'),
        ('partner', '0011_boosterrecruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificateOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('op_type', models.IntegerField(choices=[(0, 'Certificate Added'), (2, 'Badging Done on Shine'), (1, 'Certificate Updated On Shine'), (3, 'Certificate Expired')], default=0)),
                ('last_op_type', models.IntegerField(choices=[(0, 'Certificate Added'), (2, 'Badging Done on Shine'), (1, 'Certificate Updated On Shine'), (3, 'Certificate Expired')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='certificate_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_certificates', to='order.Order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Certificate Added'), (2, 'Badging Done on Shine'), (1, 'Certificate Updated On Shine'), (3, 'Certificate Expired')], default=0),
        ),
        migrations.AddField(
            model_name='usercertificateoperations',
            name='user_certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.UserCertificate'),
        ),
    ]
