# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-04 11:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20190516_1324'),
        ('partner', '0012_pixeltracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('vendor_text', models.CharField(blank=True, max_length=255, null=True)),
                ('assesment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_id', models.CharField(blank=True, help_text='Candidate_id', max_length=60, verbose_name='Candidate_id')),
                ('candidate_email', models.EmailField(help_text='Candidate Email Address', max_length=255, verbose_name='Email')),
                ('extra_info', models.TextField(blank=True, default='', help_text='Extra Info', verbose_name='Extra Info')),
                ('report', models.TextField(blank=True)),
                ('overallScore', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('vendor_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('third_party_skill_id', models.PositiveIntegerField(default=0)),
                ('primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_productskills', to='shop.Product', verbose_name='Product')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_productskills', to='shop.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Product Skill',
                'verbose_name_plural': 'Product Skills',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('score_type', models.PositiveSmallIntegerField(choices=[(1, 'Marks'), (2, 'CGPA'), (3, 'Percent')], default=0)),
                ('max_score', models.CharField(max_length=255)),
                ('score_obtained', models.IntegerField(default=0)),
                ('assesment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Assesment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCertificateOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('op_type', models.IntegerField(choices=[(0, 'Certificate Added'), (1, 'Certificate Updated On Shine'), (2, 'Badging Done on Shine'), (3, 'Certificate Expired')], default=0)),
                ('last_op_type', models.IntegerField(choices=[(0, 'Certificate Added'), (1, 'Certificate Updated On Shine'), (2, 'Badging Done on Shine'), (3, 'Certificate Expired')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='product',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_certificate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='certificate_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_certificate_orderitem', to='order.OrderItem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Certificate Added'), (1, 'Certificate Updated On Shine'), (2, 'Badging Done on Shine'), (3, 'Certificate Expired')], default=0),
        ),
        migrations.AddField(
            model_name='usercertificateoperations',
            name='user_certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.UserCertificate'),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='assesment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Assesment'),
        ),
        migrations.AlterUniqueTogether(
            name='productskill',
            unique_together=set([('product', 'skill')]),
        ),
    ]
