# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-09 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20190418_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('vendor_text', models.CharField(blank=True, max_length=255, null=True)),
                ('assesment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_id', models.CharField(blank=True, help_text='Candidate_id', max_length=60, verbose_name='Candidate_id')),
                ('candidate_email', models.EmailField(help_text='Candidate Email Address', max_length=255, verbose_name='Email')),
                ('extra_info', models.TextField(blank=True, default='', help_text='Extra Info', verbose_name='Extra Info')),
                ('report', models.TextField(blank=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Certificate')),
                ('vendor_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('score_type', models.PositiveSmallIntegerField(choices=[(1, 'Marks'), (2, 'CGPA'), (3, 'Percent')], default=0)),
                ('max_score', models.CharField(max_length=255)),
                ('score_obtained', models.IntegerField(default=0)),
                ('assesment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Assesment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_certificates', to='order.Order', verbose_name='Order'),
        ),
    ]
