# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20180323_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificate',
            name='candidate_id',
            field=models.CharField(blank=True, help_text='Candidate ID', max_length=20, verbose_name='Candidate ID'),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Created By', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
