# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-03 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20190409_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='vendor_certificate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
