# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_merge_20190613_2055'),
        ('partner', '0013_auto_20190606_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesment', to='order.OrderItem', verbose_name='Order Item'),
        ),
    ]
