# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20180329_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificate',
            name='candidate_id',
            field=models.CharField(blank=True, help_text='Candidate ID', max_length=30, verbose_name='Candidate ID'),
        ),
    ]
