# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-03 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20190521_1258'),
        ('partner', '0012_pixeltracker'),
    ]

    operations = [
    ]
