# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-09 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_auto_20190503_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='product',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Certificate Added'), (1, 'Certificate Updated On Shine'), (2, 'Badging Done on Shine'), (3, 'Certificate Expired')], default=0),
        ),
        migrations.AlterField(
            model_name='usercertificateoperations',
            name='last_op_type',
            field=models.IntegerField(choices=[(0, 'Certificate Added'), (1, 'Certificate Updated On Shine'), (2, 'Badging Done on Shine'), (3, 'Certificate Expired')], default=0),
        ),
        migrations.AlterField(
            model_name='usercertificateoperations',
            name='op_type',
            field=models.IntegerField(choices=[(0, 'Certificate Added'), (1, 'Certificate Updated On Shine'), (2, 'Badging Done on Shine'), (3, 'Certificate Expired')], default=0),
        ),
    ]
