# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-03 10:03
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_merge_20190603_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='overallScore',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
