# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import shop.functions


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_assesment_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='badge_image',
        ),
        migrations.AddField(
            model_name='vendor',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_badge_file, verbose_name='Banner Image'),
        ),
    ]
