# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import shop.functions


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_auto_20191004_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='mobile_banner_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=shop.functions.get_upload_path_mobile_banner_file, verbose_name='Mobile Banner Image'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='banner_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=shop.functions.get_upload_path_badge_file, verbose_name='Banner Image'),
        ),
    ]
