# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20190516_1324'),
        ('partner', '0015_auto_20190509_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('third_party_skill_id', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_productskills', to='shop.Product', verbose_name='Product')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_productskills', to='shop.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Product Skill',
                'verbose_name_plural': 'Product Skills',
            },
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='overallScore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productskill',
            unique_together=set([('product', 'skill')]),
        ),
    ]
