# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-07 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_auto_20191004_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='banner_visibility',
            field=models.BooleanField(default=True, verbose_name='Banner Visibility'),
        ),
    ]
