# Generated by Django 2.2.10 on 2020-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_vendor_banner_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificate',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2020, null=True),
        ),
    ]
