export const FETCH_HOME_DATA = "FETCH_HOME_DATA";

export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';

export const STORE_USER_INFO = 'STORE_USER_INFO';

export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';