export const FETCH_HOME_DATA = "FETCH_HOME_DATA";

export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';

export const STORE_USER_INFO = 'STORE_USER_INFO';

export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

export const SAVE_USER_EXPERIENCES = 'SAVE_USER_EXPERIENCES';

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';

export const SAVE_USER_EDUCATION = 'SAVE_USER_EDUCATION';

export const ADD_EDUCATION = 'ADD_EDUCATION';

export const SAVE_USER_CERTIFICATION = 'SAVE_USER_CERTIFICATION';

export const ADD_CERTIFICATION = 'ADD_CERTIFICATION';

export const SAVE_USER_REFERENCE = 'SAVE_USER_REFERENCE';

export const ADD_REFERENCE = 'ADD_REFERENCE';

export const SAVE_USER_PROJECT = 'SAVE_USER_PROJECT';

export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL';

export const ADD_PROJECT = 'ADD_PROJECT';

export const SAVE_USER_SKILL = 'SAVE_USER_SKILL';

export const ADD_SKILL = 'ADD_SKILL';

export const SAVE_USER_ACHIEVEMENT = 'SAVE_USER_ACHIEVEMENT';

export const ADD_ACHIEVEMENT = 'ADD_ACHIEVEMENT';

export const FETCH_SKILL_LIST = 'FETCH_SKILL_LIST';

export const FETCH_DEFAULT_SKILL_LIST = 'FETCH_DEFAULT_SKILL_LIST';

export const SAVE_DEFAULT_SKILL_LIST = 'SAVE_DEFAULT_SKILL_LIST';

export const ADD_TO_CART = 'ADD_TO_CART';

export const SHOW_RESUME_PREVIEW = 'SHOW_RESUME_PREVIEW';

