export const FETCH_COURSES_AND_ASSESSMENTS = "FETCH_COURSES_AND_ASSESSMENTS"

export const COURSES_AND_ASSESSMENTS_FETCHED = 'COURSES_AND_ASSESSMENTS_FETCHED'

export const FETCH_RECENTLY_ADDED_COURSES = 'FETCH_RECENTLY_ADDED_COURSES'

export const RECENTLY_ADDED_COURSES_FETCHED = 'RECENTLY_ADDED_COURSES_FETCHED'

export const FETCH_POPULAR_SERVICES = 'FETCH_POPULAR_SERVICES'

export const POPULAR_SERVICES_FETCHED = 'POPULAR_SERVICES_FETCHED'

export const FETCH_TRENDING_CATEGORIES = 'FETCH_TRENDING_CATEGORIES'

export const TRENDING_CATEGORIES_FETCHED = 'TRENDING_CATEGORIES_FETCHED'