# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 12:34
from __future__ import unicode_literals

import console.operations.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.PositiveSmallIntegerField(choices=[(0, 'Vendor Document Upload')], default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('operation_changed_from', models.PositiveSmallIntegerField(choices=[(0, 'Vendor Document Upload')], default=0)),
                ('uploaded_document', models.FileField(upload_to=console.operations.functions.get_upload_path_order_item_operation)),
            ],
        ),
    ]
