# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-21 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_candidateagentinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateagentinteraction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
