# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_auto_20190821_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateagentinteraction',
            name='connected',
            field=models.BooleanField(default=False, verbose_name='Is Call Connected'),
        ),
    ]
