export const FETCH_USER_EXPERIENCE = 'FETCH_USER_EXPERIENCE';
export const SAVE_USER_EXPERIENCE = 'SAVE_USER_EXPERIENCE';
export const UPDATE_USER_EXPERIENCE = 'UPDATE_USER_EXPERIENCE';
export const DELETE_USER_EXPERIENCE = 'DELETE_USER_EXPERIENCE';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
export const BULK_UPDATE_USER_EXPERIENCE = 'BULK_UPDATE_USER_EXPERIENCE';
