# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.functions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170831_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('gstin', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('writer_type', models.PositiveIntegerField(choices=[(0, 'Select Type'), (1, 'Starter'), (2, 'Runner'), (3, 'Expert'), (4, 'Veteran')], default=0)),
                ('po_number', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('user_invoice', models.FileField(blank=True, max_length=255, null=True, upload_to=users.functions.get_upload_path_user_invoice)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
