# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180125_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
