# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180208_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_writer_type',
            field=models.PositiveIntegerField(choices=[(0, 'Select Type'), (1, 'Starter'), (2, 'Runner'), (3, 'Expert'), (4, 'Veteran')], default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wt_changed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Writer Type Update Date'),
        ),
    ]
