# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190528_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
