# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190529_1209'),
      #  ('users', '0008_auto_20190528_1617'),
    ]

    operations = [
    ]
