# Generated by Django 2.2.10 on 2020-04-20 05:46

from django.db import migrations, models
import users.functions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20190704_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedIn_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.functions.get_upload_path_user_profile_photo, verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user                 should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
