# Generated by Django 2.2.10 on 2021-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer ID')),
                ('intent', models.PositiveSmallIntegerField(choices=[(0, 'career_change'), (1, 'career_progress'), (2, 'findjob'), (3, 'improve_profile')], default=0)),
                ('current_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_role', models.TextField(blank=True, null=True)),
                ('preferred_location', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
