# Generated by Django 2.2.10 on 2021-03-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer ID')),
                ('intent', models.PositiveSmallIntegerField(choices=[(0, 'career_change'), (1, 'career_progress'), (2, 'findjob'), (3, 'improve_profile')], default=0)),
                ('recommendation_relevant', models.BooleanField(default=False)),
                ('recommended_products', models.TextField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer ID')),
                ('intent', models.PositiveSmallIntegerField(choices=[(0, 'career_change'), (1, 'career_progress'), (2, 'findjob'), (3, 'improve_profile')], default=0)),
                ('current_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_role', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
