
export const FETCH_PERSONAL_INFO  = 'FETCH_PERSONAL_INFO';

export const UPDATE_PERSONAL_INFO  = 'UPDATE_PERSONAL_INFO';

export const SAVE_USER_INFO  = 'SAVE_USER_INFO';

export const FETCH_IMAGE_URL = 'FETCH_IMAGE_URL';

export const UPDATE_ENTITY_PREFERENCE = 'UPDATE_ENTITY_PREFERENCE'



