# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 06:18
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.PositiveIntegerField(choices=[(1, 1), (2, 2)])),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('candidate_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_comment_created_by', related_query_name='cms_comments', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_comment_last_modified_by', related_query_name='cms_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='careerplus/download/'), upload_to='', verbose_name='Document')),
                ('is_active', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='IndexColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.PositiveIntegerField(choices=[(1, 1), (2, 2)])),
                ('url', models.CharField(blank=True, help_text='provide full url including https://', max_length=2048, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndexerWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_indexerwidget_created_by', related_query_name='cms_indexerwidgets', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_indexerwidget_last_modified_by', related_query_name='cms_indexerwidgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_desc', models.TextField(blank=True, default='', verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='Keywords')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='H1')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Image Alt')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='The H1 heading for the page.', max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('total_download', models.PositiveIntegerField(default=0)),
                ('total_share', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('show_menu', models.BooleanField(default=False)),
                ('allow_comment', models.BooleanField(default=False)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_page_created_by', related_query_name='cms_pages', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_page_last_modified_by', related_query_name='cms_pages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='Parent')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_period', models.DateField()),
                ('no_views', models.PositiveIntegerField(default=0)),
                ('no_downloads', models.PositiveIntegerField(default=0)),
                ('no_shares', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'ordering': ['-count_period'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('widget_type', models.PositiveIntegerField(choices=[(1, 'Text article'), (2, 'Format download'), (3, 'Related blog'), (4, 'Practice Test'), (5, 'Expert section'), (6, 'Call Back'), (7, 'BannerLink'), (8, 'Indexer Widget')])),
                ('heading', models.CharField(blank=True, max_length=1024, null=True)),
                ('redirect_url', models.URLField(blank=True, help_text='Append http://.', null=True, verbose_name='Re-directing Url')),
                ('image', models.FileField(blank=True, help_text='use this for Resume help', max_length=200, null=True, upload_to='images/cms/widget/', verbose_name='Image')),
                ('image_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('document_upload', models.FileField(blank=True, max_length=200, null=True, upload_to='documents/cms/widget/', verbose_name='Document')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('writer_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_external', models.BooleanField(default=False)),
                ('is_pop_up', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_widget_created_by', related_query_name='cms_widgets', to=settings.AUTH_USER_MODEL)),
                ('iw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.IndexerWidget', verbose_name='Indexer Widget')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_widget_last_modified_by', related_query_name='cms_widgets', to=settings.AUTH_USER_MODEL)),
                ('related_article', models.ManyToManyField(blank=True, to='blog.Blog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='widgets',
            field=models.ManyToManyField(blank=True, to='cms.Widget', verbose_name='Widgets'),
        ),
        migrations.AddField(
            model_name='indexcolumn',
            name='indexer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.IndexerWidget'),
        ),
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.Comment'),
        ),
        migrations.AddField(
            model_name='columnheading',
            name='indexer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.IndexerWidget'),
        ),
        migrations.AlterUniqueTogether(
            name='pagecounter',
            unique_together=set([('page', 'count_period')]),
        ),
    ]
