# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_widget_created_by', related_query_name='cms_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widget',
            name='iw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.IndexerWidget', verbose_name='Indexer Widget'),
        ),
        migrations.AddField(
            model_name='widget',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_widget_last_modified_by', related_query_name='cms_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widget',
            name='related_article',
            field=models.ManyToManyField(blank=True, to='blog.Blog'),
        ),
        migrations.AddField(
            model_name='widget',
            name='user',
            field=models.ForeignKey(blank=True, help_text='for user or writer', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_pagewidget_created_by', related_query_name='cms_pagewidgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_pagewidget_last_modified_by', related_query_name='cms_pagewidgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Widget'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_page_created_by', related_query_name='cms_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_page_last_modified_by', related_query_name='cms_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='page',
            name='widgets',
            field=models.ManyToManyField(blank=True, through='cms.PageWidget', to='cms.Widget', verbose_name='Widgets'),
        ),
        migrations.AddField(
            model_name='indexerwidget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_indexerwidget_created_by', related_query_name='cms_indexerwidgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indexerwidget',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_indexerwidget_last_modified_by', related_query_name='cms_indexerwidgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indexcolumn',
            name='indexer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.IndexerWidget'),
        ),
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_comment_created_by', related_query_name='cms_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_comment_last_modified_by', related_query_name='cms_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.Comment'),
        ),
        migrations.AddField(
            model_name='columnheading',
            name='indexer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.IndexerWidget'),
        ),
        migrations.AlterUniqueTogether(
            name='pagewidget',
            unique_together=set([('page', 'widget')]),
        ),
        migrations.AlterUniqueTogether(
            name='pagecounter',
            unique_together=set([('page', 'count_period')]),
        ),
    ]
