# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagewidget',
            options={'ordering': ['section', 'ranking']},
        ),
        migrations.AddField(
            model_name='comment',
            name='candidate_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
