# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('section', models.CharField(choices=[('left', 'LEFT'), ('right', 'RIGHT')], help_text='determine section of widget', max_length=255)),
                ('ranking', models.IntegerField(default=0, help_text='determine ranking of widget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_pagewidget_created_by', related_query_name='cms_pagewidgets', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_pagewidget_last_modified_by', related_query_name='cms_pagewidgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', '-ranking'],
            },
        ),
        migrations.RemoveField(
	    model_name='page',
    	    name='widgets',
	),
	migrations.AddField(
            model_name='page',
            name='widgets',
            field=models.ManyToManyField(blank=True, through='cms.PageWidget', to='cms.Widget', verbose_name='Widgets'),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='pagewidget',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Widget'),
        ),
        migrations.AlterUniqueTogether(
            name='pagewidget',
            unique_together=set([('page', 'widget')]),
        ),
    ]
