# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170426_1145'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='related_article',
            field=models.ManyToManyField(blank=True, to='blog.Blog'),
        ),
    ]
