# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170712_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcolumn',
            name='url',
            field=models.CharField(blank=True, help_text='provide full url with valid protocol https:// or http://', max_length=2048, null=True),
        ),
    ]
