# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170403_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcolumn',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
