# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pagecategory',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='pagecategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='indexerwidget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='related_pages',
        ),
        migrations.RemoveField(
            model_name='page',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='page',
            name='status',
        ),
        migrations.RemoveField(
            model_name='page',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='upload_template',
        ),
        migrations.AlterField(
            model_name='columnheading',
            name='column',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2)]),
        ),
        migrations.AlterField(
            model_name='indexcolumn',
            name='column',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2)]),
        ),
        migrations.DeleteModel(
            name='PageCategory',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
