# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170927_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagewidget',
            options={'ordering': ['section', 'ranking']},
        ),
    ]
