# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170404_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagewidget',
            options={'ordering': ['section', '-ranking']},
        ),
        migrations.AlterField(
            model_name='widget',
            name='template_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.PositiveIntegerField(choices=[(3, 'Text article'), (4, 'Resume download'), (6, 'Related blog'), (7, 'Testimonial'), (10, 'Expert section'), (12, 'Call Back'), (15, 'AdLink'), (16, 'Indexer Widget')]),
        ),
    ]
