# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170406_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecounter',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
