# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20171009_1045'),
        ('cms', '0004_auto_20171008_1805'),
    ]

    operations = [
    ]
