# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170404_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='iw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.IndexerWidget', verbose_name='Indexer Widget'),
        ),
    ]
