# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_pagecounter_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='template_name',
        ),
        migrations.AddField(
            model_name='page',
            name='heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_desc',
            field=models.TextField(blank=True, default='', verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 4, 8, 9, 55, 56, 230684, tzinfo=utc), help_text='The H1 heading for the page.', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.PositiveIntegerField(choices=[(1, 'Text article'), (2, 'Format download'), (3, 'Related blog'), (4, 'Practice Test'), (5, 'Expert section'), (6, 'Call Back'), (7, 'BannerLink'), (8, 'Indexer Widget')]),
        ),
    ]
