# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_merge_20171009_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='name for slug change', max_length=255, verbose_name='Name'),
        ),
    ]
