# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20170408_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='The H1 heading for the page.', max_length=255, verbose_name='Name'),
        ),
    ]
