# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20171107_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexcolumn',
            options={'ordering': ['ranking']},
        ),
        migrations.AddField(
            model_name='indexcolumn',
            name='ranking',
            field=models.IntegerField(default=0, help_text='determine ranking indexer url'),
        ),
    ]
