# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20170408_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
