# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20171220_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnheading',
            name='column',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='indexcolumn',
            name='column',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
