# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 05:20
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20180201_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(max_length=200, upload_to=cms.models.get_upload_path_cms_doc, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.PositiveIntegerField(choices=[(1, 'Text article'), (2, 'Format download'), (3, 'Related blog'), (4, 'Practice Test'), (5, 'Expert section'), (6, 'Call Back'), (7, 'BannerLink'), (8, 'Indexer Widget'), (9, 'Detail Page Widget')]),
        ),
    ]
