# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_skill',
            field=models.BooleanField(default=False, verbose_name='Is Skill'),
        ),
    ]
