# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='productkeyword', to='shop.Keyword', verbose_name='Product Keyword'),
        ),
    ]
