# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='Sort Order')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='siblings',
        ),
        migrations.AddField(
            model_name='variationproduct',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainproduct', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='variationproduct',
            name='sibling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblingproduct', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='variation',
            field=models.ManyToManyField(blank=True, related_name='_product_variation_+', through='shop.VariationProduct', to='shop.Product', verbose_name='Variation Product'),
        ),
    ]
