# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 06:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170419_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='About Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_shine',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Why Buy From Shine'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='email_cc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Email CC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mail_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Welcome Mail Description'),
        ),
        migrations.AlterField(
            model_name='productarchive',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='About Product'),
        ),
        migrations.AlterField(
            model_name='productarchive',
            name='buy_shine',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Why Buy From Shine'),
        ),
        migrations.AlterField(
            model_name='productarchive',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description Product'),
        ),
        migrations.AlterField(
            model_name='productarchive',
            name='email_cc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Email CC'),
        ),
        migrations.AlterField(
            model_name='productarchive',
            name='mail_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Welcome Mail Description'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value_ltext',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Value Large Text'),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='About Product'),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='buy_shine',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Why Buy From Shine'),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description Product'),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='email_cc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Email CC'),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='mail_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Welcome Mail Description'),
        ),
    ]
