# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20170511_1046'),
        ('shop', '0002_category_is_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='countryavailable', to='geolocation.Country', verbose_name='Country Available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(blank=True, through='shop.ProductPrice', to='geolocation.Currency', verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productprices', to='geolocation.Currency', verbose_name='Currency'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
