# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170718_1236'),
        ('shop', '0003_auto_20170720_1037'),
    ]

    operations = [
    ]
