# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170511_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryrelationship',
            options={'verbose_name': 'Relationship', 'verbose_name_plural': 'Relationships'},
        ),
        migrations.AlterModelOptions(
            name='variationproduct',
            options={'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
        migrations.AlterUniqueTogether(
            name='categoryrelationship',
            unique_together=set([('related_from', 'related_to')]),
        ),
        migrations.AlterUniqueTogether(
            name='variationproduct',
            unique_together=set([('main', 'sibling')]),
        ),
    ]
