# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170511_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_bg',
            field=models.CharField(blank=True, max_length=10, verbose_name='Icon Background'),
        ),
        migrations.AddField(
            model_name='productarchive',
            name='image_bg',
            field=models.CharField(blank=True, max_length=10, verbose_name='Icon Background'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='image_bg',
            field=models.CharField(blank=True, max_length=10, verbose_name='Icon Background'),
        ),
    ]
