# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_merge_20170721_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='type_service',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type_service',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flow_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_service',
        ),
        migrations.RemoveField(
            model_name='productscreen',
            name='flow_image',
        ),
        migrations.RemoveField(
            model_name='productscreen',
            name='type_service',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type_attribute',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('richtext', 'Rich Text'), ('date', 'Date'), ('option', 'Option'), ('entity', 'Entity'), ('file', 'File'), ('image', 'Image')], default='text', max_length=20, verbose_name='Type'),
        ),
    ]
