# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 05:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170419_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Welcome Call Description'),
        ),
        migrations.AddField(
            model_name='productarchive',
            name='call_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Welcome Call Description'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='call_desc',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Welcome Call Description'),
        ),
    ]
