# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170420_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productarchive',
            old_name='combo',
            new_name='childs',
        ),
        migrations.RenameField(
            model_name='productscreen',
            old_name='combo',
            new_name='childs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='combo',
        ),
        migrations.AddField(
            model_name='product',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='_product_childs_+', through='shop.ChildProduct', to='shop.Product', verbose_name='Child Product'),
        ),
    ]
