# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170515_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_bg',
            field=models.PositiveSmallIntegerField(choices=[(1, '#cfbabd'), (2, '#75dac2'), (3, '#d2db86'), (4, '#a69cba'), (5, '#8cb3f6'), (6, '#9ac7e5'), (7, '#ad9c7f'), (8, '#80d7ff'), (9, '#a48e96'), (10, '#b4e4fc'), (11, '#d7ccc8'), (12, '#a3e77d'), (13, '#ebdcc9'), (14, '#9fdbd6'), (15, '#a19f9c'), (16, '#deae9e'), (17, '#73a4d4'), (18, '#cba5bf'), (19, '#9099c6'), (20, '#d9bee7'), (21, '#cddb3a'), (22, '#81c783'), (23, '#afbec6'), (24, '#cdac98'), (25, '#c5cbe9'), (26, '#d5d5d5'), (27, '#e39b71'), ('#c8b98d', '#c8b98d')], default=0, verbose_name='Icon Background'),
        ),
        migrations.AlterField(
            model_name='productarchive',
            name='image_bg',
            field=models.PositiveSmallIntegerField(choices=[(1, '#cfbabd'), (2, '#75dac2'), (3, '#d2db86'), (4, '#a69cba'), (5, '#8cb3f6'), (6, '#9ac7e5'), (7, '#ad9c7f'), (8, '#80d7ff'), (9, '#a48e96'), (10, '#b4e4fc'), (11, '#d7ccc8'), (12, '#a3e77d'), (13, '#ebdcc9'), (14, '#9fdbd6'), (15, '#a19f9c'), (16, '#deae9e'), (17, '#73a4d4'), (18, '#cba5bf'), (19, '#9099c6'), (20, '#d9bee7'), (21, '#cddb3a'), (22, '#81c783'), (23, '#afbec6'), (24, '#cdac98'), (25, '#c5cbe9'), (26, '#d5d5d5'), (27, '#e39b71'), ('#c8b98d', '#c8b98d')], default=0, verbose_name='Icon Background'),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='image_bg',
            field=models.PositiveSmallIntegerField(choices=[(1, '#cfbabd'), (2, '#75dac2'), (3, '#d2db86'), (4, '#a69cba'), (5, '#8cb3f6'), (6, '#9ac7e5'), (7, '#ad9c7f'), (8, '#80d7ff'), (9, '#a48e96'), (10, '#b4e4fc'), (11, '#d7ccc8'), (12, '#a3e77d'), (13, '#ebdcc9'), (14, '#9fdbd6'), (15, '#a19f9c'), (16, '#deae9e'), (17, '#73a4d4'), (18, '#cba5bf'), (19, '#9099c6'), (20, '#d9bee7'), (21, '#cddb3a'), (22, '#81c783'), (23, '#afbec6'), (24, '#cdac98'), (25, '#c5cbe9'), (26, '#d5d5d5'), (27, '#e39b71'), ('#c8b98d', '#c8b98d')], default=0, verbose_name='Icon Background'),
        ),
    ]
