# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 06:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170727_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('heading', models.CharField(max_length=255, verbose_name='chapter')),
                ('answer', ckeditor.fields.RichTextField(blank=True, help_text='The answer text.', verbose_name='answer')),
                ('ordering', models.PositiveSmallIntegerField(default=1, help_text='An integer used to order the chapter             amongst others related to the same chapter. If not given this             chapter will be last in the list.', verbose_name='ordering')),
                ('status', models.BooleanField(default=False, help_text="Only questions with 'Active' will be displayed.", verbose_name='status')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_product', to='shop.Product')),
            ],
            options={
                'permissions': (('console_add_chapter', 'Can Add Product Chapter From Console'), ('console_change_chapter', 'Can Change Product Chapter From Console'), ('console_moderate_chapter', 'Can Moderate Product Chapter From Console')),
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='ScreenChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('heading', models.CharField(max_length=255, verbose_name='chapter')),
                ('answer', ckeditor.fields.RichTextField(blank=True, help_text='The answer text.', verbose_name='answer')),
                ('ordering', models.PositiveSmallIntegerField(default=1, help_text='An integer used to order the chapter             amongst others related to the same chapter. If not given this             chapter will be last in the list.', verbose_name='ordering')),
                ('status', models.BooleanField(default=False, help_text="Only questions with 'Active' will be displayed.", verbose_name='status')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_product', to='shop.ProductScreen')),
            ],
            options={
                'verbose_name': 'Screen Chapter',
                'verbose_name_plural': 'Screen Chapters',
            },
        ),
    ]
