# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170421_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_jobs',
            field=models.PositiveIntegerField(default=0, verbose_name='Buy Count'),
        ),
    ]
