# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_num_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productfaqs', to='shop.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='faqproduct',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productfaqs', to='faq.FAQuestion', verbose_name='FAQuestion'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productattributes', to='shop.Attribute', verbose_name='Attribute'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productattributes', to='shop.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategories', to='shop.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategories', to='shop.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productkeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productkeywords', to='shop.Keyword', verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='productkeyword',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productkeywords', to='shop.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productprices', to='shop.Currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productprices', to='shop.Product', verbose_name='Product'),
        ),
    ]
