# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170728_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='code',
            field=models.CharField(default='ss', max_length=4, verbose_name='Option Code'),
            preserve_default=False,
        ),
    ]
