# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170801_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cp_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='CP Variation'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='cp_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='CP Variation'),
        ),
    ]
