# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_attributeoption_code'),
        ('shop', '0008_auto_20170801_1221'),
    ]

    operations = [
    ]
