# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20170424_1618'),
        ('shop', '0008_auto_20170424_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productvendor', to='partner.Vendor', verbose_name='Product Vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_jobs',
            field=models.PositiveIntegerField(default=0, verbose_name='Num Jobs'),
        ),
    ]
