# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170809_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpv_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='CP Variation'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='cpv_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='CP Variation'),
        ),
    ]
