# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170424_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.BooleanField(default=True, verbose_name='Give Certification'),
        ),
        migrations.AddField(
            model_name='product',
            name='course_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Basic'), (2, 'Intermediate'), (3, 'Expert')], default=0, verbose_name='Course Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='study_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Online'), (2, 'Classroom'), (3, 'Online + Classroom')], default=0, verbose_name='Study Mode'),
        ),
        migrations.AddField(
            model_name='productarchive',
            name='certification',
            field=models.BooleanField(default=True, verbose_name='Give Certification'),
        ),
        migrations.AddField(
            model_name='productarchive',
            name='course_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Basic'), (2, 'Intermediate'), (3, 'Expert')], default=0, verbose_name='Course Type'),
        ),
        migrations.AddField(
            model_name='productarchive',
            name='study_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Online'), (2, 'Classroom'), (3, 'Online + Classroom')], default=0, verbose_name='Study Mode'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='certification',
            field=models.BooleanField(default=True, verbose_name='Give Certification'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='course_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Basic'), (2, 'Intermediate'), (3, 'Expert')], default=0, verbose_name='Course Type'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='study_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Online'), (2, 'Classroom'), (3, 'Online + Classroom')], default=0, verbose_name='Study Mode'),
        ),
    ]
