# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170810_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archive_json',
            field=models.TextField(blank=True, editable=False, verbose_name='Archive Jason'),
        ),
    ]
