# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_merge_20170808_1637'),
        ('shop', '0011_product_archive_json'),
    ]

    operations = [
    ]
