# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_merge_20170811_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Delivery Type')),
                ('inr_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='INR Price')),
                ('usd_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='USD Price')),
                ('aed_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='AED Price')),
                ('gbp_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='GBP Price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='productextrainfo',
            name='info_type',
            field=models.CharField(choices=[('default', 'Default'), ('profile_update', 'Profile Update Country'), ('delivery_service', 'Delivery Service')], max_length=256, verbose_name='Type'),
        ),
    ]
