# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_merge_20170811_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cp_page_view',
            field=models.IntegerField(default=0, verbose_name='CP Page View'),
        ),
        migrations.AlterField(
            model_name='product',
            name='archive_json',
            field=models.TextField(blank=True, editable=False, verbose_name='Archive JSON'),
        ),
        migrations.AlterField(
            model_name='productextrainfo',
            name='info_type',
            field=models.CharField(choices=[('default', 'Default'), ('profile_update', 'Profile Update Country')], max_length=256, verbose_name='Type'),
        ),
    ]
