# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170818_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='code',
            field=models.CharField(max_length=4, unique=True, verbose_name='Option Code'),
        ),
        migrations.AlterField(
            model_name='productextrainfo',
            name='info_type',
            field=models.CharField(choices=[('default', 'Default'), ('profile_update', 'Profile Update Country'), ('delivery_service', 'Delivery Service')], max_length=256, verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together=set([('group', 'code')]),
        ),
    ]
