# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170818_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservice',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
