# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_merge_20170828_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profile_country',
        ),
    ]
