# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_profile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeoptiongroup',
            options={'verbose_name': 'Attribute Option Group', 'verbose_name_plural': 'Attribute Option Groups'},
        ),
    ]
