# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20170911_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FA',
                'verbose_name_plural': 'FAs',
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'created',
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
        migrations.CreateModel(
            name='ProductFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productfas', to='shop.FunctionalArea', verbose_name='FA')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productfas', to='shop.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product FA',
                'verbose_name_plural': 'Product FAs',
            },
        ),
        migrations.CreateModel(
            name='ProductSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productskills', to='shop.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Skill',
                'verbose_name_plural': 'Product Skills',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True)),
                ('skillproducts', models.ManyToManyField(blank=True, through='shop.ProductSkill', to='shop.Product', verbose_name='Skill Product')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'created',
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
        migrations.AddField(
            model_name='productskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productskills', to='shop.Skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='functionalarea',
            name='faproducts',
            field=models.ManyToManyField(blank=True, through='shop.ProductFA', to='shop.Product', verbose_name='FA Product'),
        ),
        migrations.AlterUniqueTogether(
            name='productskill',
            unique_together=set([('product', 'skill')]),
        ),
        migrations.AlterUniqueTogether(
            name='productfa',
            unique_together=set([('product', 'fa')]),
        ),
    ]
