# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20170911_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservice',
            name='slug',
            field=models.CharField(default=datetime.datetime(2017, 9, 19, 8, 51, 31, 875490, tzinfo=utc), help_text='Unique slug', max_length=250, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryservice',
            name='name',
            field=models.CharField(help_text='Name will be unique to decide slug', max_length=200, verbose_name='Delivery Service Name'),
        ),
    ]
