# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170919_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryservice',
            name='slug',
            field=models.CharField(help_text='Unique slug', max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
