# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20170919_1434'),
        ('shop', '0018_auto_20170918_2026'),
    ]

    operations = [
    ]
