# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_merge_20170925_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fixed_slug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='fixed_slug',
            field=models.BooleanField(default=False),
        ),
    ]
