# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-31 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20171007_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryservice',
            name='name',
            field=models.CharField(help_text='Name will be unique to decide slug', max_length=200, verbose_name='Name'),
        ),
    ]
