# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 10:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20171031_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attend',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Who Should Attend'),
        ),
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='attend',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Who Should Attend'),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
