# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20180503_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenProductSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenskills', to='shop.ProductScreen', verbose_name='Product')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenskills', to='shop.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Product Skill',
                'verbose_name_plural': 'Product Skills',
            },
        ),
        migrations.AlterUniqueTogether(
            name='screenproductskill',
            unique_together=set([('product', 'skill')]),
        ),
    ]
