# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-14 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20180503_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Show as a Service Page'),
        ),
    ]
