# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-21 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_category_is_service'),
        ('shop', '0025_auto_20180806_1450'),
    ]

    operations = [
    ]
