# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_initial_university_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'get_latest_by': 'created', 'ordering': ('-modified', '-created'), 'permissions': (('console_add_faculty', 'Can Add Faculty From Console'), ('console_change_faculty', 'Can Change Faculty From Console'), ('console_view_faculty', 'Can View Faculty From Console')), 'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculty'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.IntegerField(choices=[(0, '--Select Role--'), (1, 'Teacher'), (2, 'Principal')], default=0),
        ),
    ]
