# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-04 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20181001_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycoursedetail',
            name='attendees_criteria',
            field=models.CharField(blank=True, help_text='who shoule attend this course', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='universitycoursedetail',
            name='eligibility_criteria',
            field=models.CharField(blank=True, help_text='semi-colon(;) separated designations, e.g. Managers, Decision makers; Line Managers; ...', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='universitycoursedetailscreen',
            name='attendees_criteria',
            field=models.CharField(blank=True, help_text='who shoule attend this course', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='universitycoursedetailscreen',
            name='eligibility_criteria',
            field=models.CharField(blank=True, help_text='semi-colon(;) separated designations, e.g. Managers, Decision makers; Line Managers; ...', max_length=500, null=True),
        ),
    ]
