# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_university_course_detail_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycoursedetail',
            name='payment_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Payment Deadline'),
        ),
        migrations.AddField(
            model_name='universitycoursedetailscreen',
            name='payment_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Payment Deadline'),
        ),
    ]
