# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-11 09:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_add_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='universitycoursedetail',
            name='assesment',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description of Assesment and Evaluation', verbose_name='assesment'),
        ),
        migrations.AlterField(
            model_name='universitycoursedetailscreen',
            name='assesment',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description of Assesment and Evaluation', verbose_name='assesment'),
        ),
    ]
