# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20181011_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycoursedetail',
            name='highlighted_benefits',
            field=models.CharField(blank=True, help_text='semi-colon(;) separated designations, e.g. Managers, Decision makers; Line Managers; ...', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='universitycoursedetailscreen',
            name='highlighted_benefits',
            field=models.CharField(blank=True, help_text='semi-colon(;) separated designations, e.g. Managers, Decision makers; Line Managers; ...', max_length=500, null=True),
        ),
    ]
