# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20181012_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycoursedetail',
            name='apply_last_date',
            field=models.DateField(blank=True, help_text='Last date to apply for this univeristy course', null=True),
        ),
        migrations.AlterField(
            model_name='universitycoursedetail',
            name='batch_launch_date',
            field=models.DateField(blank=True, help_text='This university course launch date', null=True),
        ),
        migrations.AlterField(
            model_name='universitycoursedetail',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Deadline'),
        ),
        migrations.AlterField(
            model_name='universitycoursedetailscreen',
            name='apply_last_date',
            field=models.DateField(blank=True, help_text='Last date to apply for this univeristy course', null=True),
        ),
        migrations.AlterField(
            model_name='universitycoursedetailscreen',
            name='batch_launch_date',
            field=models.DateField(blank=True, help_text='This university course launch date', null=True),
        ),
        migrations.AlterField(
            model_name='universitycoursedetailscreen',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Deadline'),
        ),
    ]
