# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-16 04:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20181015_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
