# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20181016_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (601, 'Fiurst'), (602, 'Second')], default=-1),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (601, 'Fiurst'), (602, 'Second')], default=-1),
        )
    ]
