# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-26 07:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20181016_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycoursedetail',
            name='late_fee',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description of Late Fee', verbose_name='late_fee'),
        ),
        migrations.AddField(
            model_name='universitycoursedetailscreen',
            name='late_fee',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description of Late Fee', verbose_name='late_fee'),
 ),
        migrations.AlterField(
            model_name='product',
            name='type_flow',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Resume Writing India'), (2, 'Courses'), (3, 'Resume Critique'), (4, 'International Profile Update'), (5, 'Featured Profile'), (6, 'IDfy Assessment'), (7, 'Resume Booster'), (8, 'Linkedin'), (9, 'Round One'), (10, 'StudyMate'), (11, 'TSSC'), (12, 'Country Specific Resume'), (13, 'Executive Bio,Portfolio,Visual Resume,Cover Letter,Second Regular Resume'), (14, 'Premium Courses')], default=0, verbose_name='Flow'),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='type_flow',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Resume Writing India'), (2, 'Courses'), (3, 'Resume Critique'), (4, 'International Profile Update'), (5, 'Featured Profile'), (6, 'IDfy Assessment'), (7, 'Resume Booster'), (8, 'Linkedin'), (9, 'Round One'), (10, 'StudyMate'), (11, 'TSSC'), (12, 'Country Specific Resume'), (13, 'Executive Bio,Portfolio,Visual Resume,Cover Letter,Second Regular Resume'), (14, 'Premium Courses')], default=0, verbose_name='Flow'),
        ),
    ]
