# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import shop.functions


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20190313_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShineProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_feature_profile_file, verbose_name='Image')),
                ('type_flow', models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Resume Writing India'), (2, 'Courses'), (3, 'Resume Critique'), (4, 'International Profile Update'), (5, 'Featured Profile'), (6, 'IDfy Assessment'), (7, 'Resume Booster'), (8, 'Linkedin'), (9, 'Round One'), (10, 'StudyMate'), (11, 'TSSC'), (12, 'Country Specific Resume'), (13, 'Executive Bio,Portfolio,Visual Resume,Cover Letter,Second Regular Resume'), (14, 'University Courses'), (15, 'Resume Booster International')], verbose_name='Flow')),
                ('sub_type_flow', models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant')], unique=True)),
                ('booster_value', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
