# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', 'fixed_migration_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Delhi'), (1, 'Mumbai'), (2, 'Pune'), (3, 'Hyderabad'), (4, 'Kolkata')], default=0, verbose_name='location'),
        ),
    ]
