# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-07 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20190306_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Image Alt'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_desc',
            field=models.TextField(blank=True, default='', verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Url'),
        ),
    ]
