# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-03 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20190320_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shineprofiledata',
            name='booster_value',
        ),
        migrations.AddField(
            model_name='shineprofiledata',
            name='priority_value',
            field=models.PositiveIntegerField(default=1),
        )
    ]
