# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20190307_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='product_mapped',
            field=models.CharField(blank=True, help_text='Product Mapping', max_length=100, null=True, verbose_name='products'),
        ),
    ]
