# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-03 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20190403_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='shineprofiledata',
            name='action',
            field=models.IntegerField(choices=[(1, 'Highlight'), (2, 'Booster')], default=-1),
        )
    ]
