# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-11 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_remove_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(blank=True, help_text='Unique slug', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
