# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-10 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20190403_1345'),
        ('shop', '0042_remove_subcategory_name'),
    ]

    operations = [
    ]
