# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-26 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_remove_subcategory_name'),
        ('shop', '0035_auto_20190308_1525'),
    ]

    operations = [
    ]
