# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20190403_1345'),
        ('shop', '0043_merge_20190326_1737'),
    ]

    operations = [
    ]
