# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_merge_20190410_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitycoursedetail',
            name='late_fee',
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant')], default=-1),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant')], default=-1),
        ),
    ]
