# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20190411_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Delhi'), (1, 'Mumbai'), (2, 'Pune'), (3, 'Hyderabad'), (4, 'Kolkata'), (5, 'Noida'), (6, 'Gurgaon'), (7, 'Chandigarh'), (8, 'Nagpur'), (9, 'Jaipur'), (10, 'Bangalore'), (11, 'Gurugram')], default=0, verbose_name='location'),
        ),
    ]
