# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-13 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20190516_1324'),
        ('shop', '0046_merge_20190522_1538'),
    ]

    operations = [
    ]
