# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20190528_1617'),
        ('shop', '0047_auto_20190703_1944'),
    ]

    operations = [
    ]
