# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-24 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20190524_1529'),
        ('shop', '0047_merge_20190613_2055'),
    ]

    operations = [
    ]
