# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20190704_1842'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='jobslinks',
        #     name='link',
        #     field=models.URLField(max_length=2000),
        # ),
    ]
