# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_auto_20190711_1316'),
        ('shop', '0047_merge_20190613_2055'),
    ]

    operations = [
    ]
