# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20190711_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productuserprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productuserprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=8, verbose_name='Average Rating'),
        ),
    ]
