# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20190716_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.CharField(max_length=100, verbose_name='Customer Email')),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile number')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Name')),
                ('test_data', models.TextField(blank=True, null=True, verbose_name='test_data')),
                ('is_boarded', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='order.OrderItem', verbose_name='Order Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
