# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-30 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20190716_1851'),
        ('shop', '0048_auto_20190725_1243'),
    ]

    operations = [
    ]
