# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_practicetestinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetestinfo',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='order.OrderItem', verbose_name='Order Item'),
        ),
    ]
