# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-09 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_auto_20190731_1236'),
        ('shop', '0052_merge_20190729_1340'),
    ]

    operations = [
    ]
