# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_merge_20190729_1340'),
        ('shop', '0053_auto_20190806_1253'),
        ('shop', '0054_auto_20190731_1236'),
    ]

    operations = [
    ]
