# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-08 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_practicetestinfo'),
        ('shop', '0055_merge_20190807_1231'),
    ]

    operations = [
    ]
