# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_merge_20190808_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
