# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-20 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_merge_20190809_1454'),
        ('shop', '0057_auto_20190809_1142'),
    ]

    operations = [
    ]
