# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-27 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20190816_1959'),
        ('shop', '0056_merge_20190809_1454'),
    ]

    operations = [
    ]
