# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_merge_20190827_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserprofile',
            name='force_update_links_count',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test')], default=-1),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test')], default=-1),
        ),
        migrations.AlterField(
            model_name='shineprofiledata',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test')]),
        ),
    ]
