# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-28 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_merge_20190827_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserprofile',
            name='manual_change',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Update Pending Links Count')], null=True),
        ),
        migrations.AddField(
            model_name='productuserprofile',
            name='manual_changes_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test')], default=-1),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test')], default=-1),
        ),
        migrations.AlterField(
            model_name='shineprofiledata',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test')]),
        ),
    ]
