# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-09 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_merge_20190821_1538'),
        ('shop', '0055_merge_20190809_1152'),
        ('shop', '0061_auto_20190828_1446'),
    ]

    operations = [
    ]
