# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-27 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_merge_20190909_1615'),
        ('shop', '0064_auto_20190912_1852'),
    ]

    operations = [
    ]
