# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-29 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20191010_2006'),
        ('shop', '0066_auto_20191011_1141'),
    ]

    operations = [
    ]
