# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-04 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_merge_20191029_1052'),
    ]

    operations = [

        migrations.AddField(
            model_name='subheadercategory',
            name='heading_choices',
            field=models.SmallIntegerField(choices=[(1, 'objective'), (2, 'who-should-learn'), (3, 'Test-your-skills'), (4, 'our-impact'), (5, 'faq')], default=-1),
        ),
    ]
