# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-14 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_merge_20191029_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='productskill',
            name='relation_type',
            field=models.PositiveIntegerField(choices=[(1, 'Product Skill'), (2, 'Required Skill')], default=1, help_text='Describes the type of relation between product and skill'),
        ),
        migrations.AddField(
            model_name='screenproductskill',
            name='relation_type',
            field=models.PositiveIntegerField(choices=[(1, 'Product Skill'), (2, 'Required Skill')], default=1, help_text='Describes the type of relation between product and skill'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test'), (200, 'Default'), (201, 'Certificate Product'), (100, 'Default'), (101, 'Expert Assistance')], default=-1),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test'), (200, 'Default'), (201, 'Certificate Product'), (100, 'Default'), (101, 'Expert Assistance')], default=-1),
        ),
        migrations.AlterField(
            model_name='shineprofiledata',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test'), (200, 'Default'), (201, 'Certificate Product'), (100, 'Default'), (101, 'Expert Assistance')]),
        ),
    ]
