# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-22 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_auto_20191114_1726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productskill',
            unique_together=set([('product', 'skill', 'relation_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='screenproductskill',
            unique_together=set([('product', 'skill', 'relation_type')]),
        ),
    ]
