# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_auto_20191122_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productskill',
            name='relation_type',
            field=models.PositiveIntegerField(choices=[(1, 'Product Skill'), (2, 'User Skill')], default=1, help_text='Describes the type of relation between product and skill'),
        ),
        migrations.AlterField(
            model_name='screenproductskill',
            name='relation_type',
            field=models.PositiveIntegerField(choices=[(1, 'Product Skill'), (2, 'User Skill')], default=1, help_text='Describes the type of relation between product and skill'),
        ),
    ]
