# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_auto_20191216_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.SmallIntegerField(choices=[(1, 'Bestseller'), (2, 'Newly Added')], default=0),
        ),
    ]
