# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_auto_20191122_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_keywords',
        ),
        migrations.AddField(
            model_name='product',
            name='job_title',
            field=models.TextField(blank=True, default='', verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='visible_on_crm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productscreen',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(1601, 'Free Test'), (1602, 'Paid Test'), (100, 'Default'), (101, 'Expert Assistance'), (200, 'Default'), (201, 'Certificate Product'), (501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant')], default=-1),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(1601, 'Free Test'), (1602, 'Paid Test'), (100, 'Default'), (101, 'Expert Assistance'), (200, 'Default'), (201, 'Certificate Product'), (501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant')], default=-1),
        ),
        migrations.AlterField(
            model_name='shineprofiledata',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(1601, 'Free Test'), (1602, 'Paid Test'), (100, 'Default'), (101, 'Expert Assistance'), (200, 'Default'), (201, 'Certificate Product'), (501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant')]),
        ),
    ]
