# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_auto_20191205_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='job_title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Job Title'),
        ),
    ]
