# Generated by Django 2.2.10 on 2020-05-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_auto_20191218_1522'),
        ('shop', '0070_product_product_tag'),
        ('shop', '0072_auto_20191230_1324'),
    ]

    operations = [
    ]
