# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-02 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0093_merge_20191230_1325'),
        ('shop', '0072_auto_20191230_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobslinks',
            name='oi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_link', to='order.OrderItem', verbose_name='Order Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicetestinfo',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='order.OrderItem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='productuserprofile',
            name='order_item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_profile_orderitem', to='order.OrderItem', verbose_name='Order Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='job_title',
            field=models.TextField(blank=True, null=True, verbose_name='Job Title'),
        ),
    ]
