# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_auto_20200102_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductJobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, help_text='Job title', max_length=100, null=True, verbose_name='Job Title')),
                ('product', models.ManyToManyField(null=True, related_name='jobtitle', to='shop.Product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
