# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_productjobtitle'),
        ('shop', '0070_product_product_tag'),
    ]

    operations = [
    ]
