# Generated by Django 2.2.10 on 2020-04-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_productjobtitle'),
        ('shop', '0070_product_product_tag'),
        ('shop', '0071_auto_20191218_1522'),
    ]

    operations = [
    ]
