# Generated by Django 2.2.10 on 2020-06-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_auto_20200521_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='product image class'),
        ),
    ]
