# Generated by Django 2.2.10 on 2020-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_auto_20200420_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='section',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Product'),
        ),
    ]
