# Generated by Django 2.2.10 on 2020-04-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_auto_20200420_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer',
            new_name='offers',
        ),
    ]
