# Generated by Django 2.2.10 on 2020-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_auto_20200606_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsVidhyaRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('AV_Id', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=100, verbose_name='Customer Email')),
                ('name', models.CharField(help_text='Unique name going to decide the slug', max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Contact number')),
                ('price', models.CharField(max_length=50, verbose_name='price')),
                ('price_currency', models.CharField(default='INR', max_length=50, verbose_name='price_currency')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'user_activation_pending'), (2, 'enrollment_pending'), (3, 'enrollment_done'), (4, 'enrollment_error')], default=0)),
                ('status_msg', models.CharField(max_length=100, verbose_name='status message')),
                ('remarks', models.CharField(max_length=200, verbose_name='remarks')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
