# Generated by Django 2.2.10 on 2020-04-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0076_merge_20200430_1635'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Bestseller'), (2, 'Newly Added')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test'), (200, 'Default'), (201, 'Certificate Product'), (100, 'Default'), (101, 'Expert Assistance'), (1700, 'Default'), (1701, 'Subscription')], default=-1),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test'), (200, 'Default'), (201, 'Certificate Product'), (100, 'Default'), (101, 'Expert Assistance'), (1700, 'Default'), (1701, 'Subscription')], default=-1),
        ),
        migrations.AlterField(
            model_name='shineprofiledata',
            name='sub_type_flow',
            field=models.IntegerField(choices=[(501, 'Featured Profile'), (502, 'Jobs on the Move'), (503, 'Priority Applicant'), (1601, 'Free Test'), (1602, 'Paid Test'), (200, 'Default'), (201, 'Certificate Product'), (100, 'Default'), (101, 'Expert Assistance'), (1700, 'Default'), (1701, 'Subscription')]),
        ),
     
    ]
