# Generated by Django 2.2.10 on 2020-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_auto_20200420_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sub_section',
            field=models.ManyToManyField(blank=True, null=True, to='shop.SubSection'),
        ),
    ]
