# Generated by Django 2.2.10 on 2020-07-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_analyticsvidhyarecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsvidhyarecord',
            name='product_id',
            field=models.CharField(default=1, max_length=10, verbose_name='product id'),
            preserve_default=False,
        ),
    ]
