# Generated by Django 2.2.10 on 2020-04-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_section_sub_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-priority']},
        ),
    ]
