# Generated by Django 2.2.10 on 2020-05-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_auto_20200514_1311'),
        ('shop', '0078_auto_20200505_1324'),
    ]

    operations = [
    ]
