# Generated by Django 2.2.10 on 2020-07-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_analyticsvidhyarecord_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsvidhyarecord',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='remarks'),
        ),
    ]
