# Generated by Django 2.2.10 on 2020-04-22 08:27

from django.db import migrations, models
import shop.functions


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_auto_20200422_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_product_offer_icon, verbose_name='offer icon'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'features'), (2, 'why-choose-us'), (3, 'how-it-works'), (4, 'product-banner-widget')], default=0),
        ),
    ]
