# Generated by Django 2.2.10 on 2020-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_auto_20200422_1357'),
        ('shop', '0078_auto_20200505_1324'),
    ]

    operations = [
    ]
