# Generated by Django 2.2.10 on 2020-08-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_auto_20200821_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ex_cour',
            field=models.TextField(default='[]'),
        ),
    ]
