# Generated by Django 2.2.10 on 2020-10-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_auto_20200925_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserprofile',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productuserprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
