# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-06 09:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import shop.functions


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20181026_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Unique name going to decide the slug', max_length=100, verbose_name='Name')),
                ('location', models.PositiveSmallIntegerField(choices=[(0, 'Delhi'), (1, 'Mumbai'), (2, 'Pune'), (3, 'Hyderabad'), (4, 'Kolkata')], default=0, verbose_name='Level')),
                ('slug', models.CharField(help_text='Unique slug', max_length=100, unique=True, verbose_name='Slug')),
                ('video_link', models.CharField(blank=True, max_length=200, verbose_name='Video Link')),
                ('career_outcomes', models.CharField(blank=True, help_text='semi-colon(;) separated designations, e.g. Project Engineer; Software Engineer; ...', max_length=500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_category, verbose_name='Banner')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_category, verbose_name='Graph Image')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_category, verbose_name='Image')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_category, verbose_name='Icon')),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='type_flow',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Resume Writing India'), (2, 'Courses'), (3, 'Resume Critique'), (4, 'International Profile Update'), (5, 'Featured Profile'), (6, 'IDfy Assessment'), (7, 'Resume Booster'), (8, 'Linkedin'), (9, 'Round One'), (10, 'StudyMate'), (11, 'TSSC'), (12, 'Country Specific Resume'), (13, 'Executive Bio,Portfolio,Visual Resume,Cover Letter,Second Regular Resume'), (14, 'University Courses'), (15, 'Resume Booster International')], default=0, verbose_name='Flow'),
        ),
        migrations.AlterField(
            model_name='productscreen',
            name='type_flow',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Resume Writing India'), (2, 'Courses'), (3, 'Resume Critique'), (4, 'International Profile Update'), (5, 'Featured Profile'), (6, 'IDfy Assessment'), (7, 'Resume Booster'), (8, 'Linkedin'), (9, 'Round One'), (10, 'StudyMate'), (11, 'TSSC'), (12, 'Country Specific Resume'), (13, 'Executive Bio,Portfolio,Visual Resume,Cover Letter,Second Regular Resume'), (14, 'University Courses'), (15, 'Resume Booster International')], default=0, verbose_name='Flow'),
        ),
    ]
