export const FETCH_USER_COURSE = 'FETCH_USER_COURSE';
export const SAVE_USER_COURSE = 'SAVE_USER_COURSE';
export const UPDATE_USER_COURSE = 'UPDATE_USER_COURSE';
export const DELETE_USER_COURSE = 'DELETE_USER_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const HANDLE_COURSE_SWAP = 'HANDLE_COURSE_SWAP';
export const BULK_U_C_USER_COURSE = 'BULK_U_C_USER_COURSE';
