# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170707_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk'], 'permissions': (('can_show_midout_queue', 'Can Show Midout Queue'), ('can_upload_candidate_resume', 'Can Upload Candidate resume'), ('can_show_inbox_queue', 'Can Show Inbox Queue'), ('can_view_extra_field_inbox', 'Can View Extra Fields Of Inbox'), ('can_show_assigned_inbox', 'Can Show Only Assigned Inbox'), ('can_show_unassigned_inbox', 'Can Show Only Unassigned Inbox'), ('writer_assignment_action', 'Writer Assignment Action permission'), ('can_assigned_to_writer', 'Can Assigned To This Writer'), ('can_view_order_item_detail', 'Can View Order Item Detail'), ('writer_assignment_linkedin_action', 'Can Assign to Other linkedin writer'), ('can_assigned_to_linkedin_writer', 'Can Assigned To This linkedin Writer'), ('can_show_linkedinrejectedbyadmin_queue', 'Can View Linkedin Rejected By Admin Queue'), ('can_show_linkedinrejectedbycandidate_queue', 'Can View LinkedinRejected By Candidate Queue'), ('can_show_linkedin_approval_queue', 'Can View Linkedin Approval Queue'), ('can_show_approval_queue', 'Can View Approval Queue'), ('can_view_all_approval_list', 'Can View All Approval List'), ('can_view_only_assigned_approval_list', 'Can View Only Assigned Approval List'), ('can_approve_or_reject_draft', 'Can Approve Or Reject Draft'), ('can_show_approved_queue', 'Can View Approved Queue'), ('can_view_all_approved_list', 'Can View All Approved List'), ('can_view_only_assigned_approved_list', 'Can View Only Assigned Approved List'), ('can_show_rejectedbyadmin_queue', 'Can View Rejected By Admin Queue'), ('can_view_all_rejectedbyadmin_list', 'Can View All Rejected by Admin List'), ('can_view_only_assigned_rejectedbyadmin_list', 'Can View Only Assigned Rejected By Admin List'), ('can_show_rejectedbycandidate_queue', 'Can View Rejected By Candidate Queue'), ('can_view_all_rejectedbycandidate_list', 'Can View All Rejected By Candidate List'), ('can_view_only_assigned_rejectedbycandidate_list', 'Can View Only Assigned Rejected By Candidate List'), ('can_show_allocated_queue', 'Can Show Allocated Queue'), ('can_view_all_allocated_list', 'Can View All Allocated List'), ('can_view_only_assigned_allocated_list', 'Can View Only Assigned Allocated List'), ('can_show_booster_queue', 'Can Show Booster Queue'), ('can_show_domestic_profile_update_queue', 'Can Show Domestic Profile Update Queue'), ('domestic_profile_update_assigner', 'Domestic Profile Update Assigner'), ('domestic_profile_update_assignee', 'Domestic Profile Update Assignee'), ('can_show_domestic_profile_approval_queue', 'Can Show Domestic Profile Approval Queue'), ('can_show_international_profile_update_queue', 'Can Show International Profile Update Queue'), ('international_profile_update_assigner', 'International Profile Update Assigner'), ('international_profile_update_assignee', 'International Profile Update Assignee'), ('can_show_international_profile_approval_queue', 'Can Show International Profile Approval Queue'), ('can_show_closed_oi_queue', 'Can Show Closed Orderitem Queue'), ('can_view_all_closed_oi_list', 'Can View All Closed Orderitem List'), ('can_view_only_assigned_closed_oi_list', 'Can View Only Assigned Closed Orderitem List'), ('oi_action_permission', 'OrderItem Action Permission'), ('oi_export_as_csv_permission', 'Order Item Export As CSV Permission')), 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
