# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        ('order', '0003_auto_20170718_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterNationalProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('Password', models.CharField(max_length=100, verbose_name='Password')),
                ('candidateid', models.CharField(max_length=100, verbose_name='CandidateId')),
                ('profile_status', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Country')),
                ('oi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
            ],
        ),
    ]
