# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_country_profile_url'),
        ('order', '0004_internationalprofileuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalProfileCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('Password', models.CharField(max_length=100, verbose_name='Password')),
                ('candidateid', models.CharField(max_length=100, verbose_name='CandidateId')),
                ('candidate_email', models.CharField(max_length=100, verbose_name='Candidate Email')),
                ('site_url', models.CharField(blank=True, max_length=100, verbose_name='Site Url')),
                ('profile_status', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='internationalprofileuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='internationalprofileuser',
            name='oi',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='last_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume Not Uploaded'), (3, 'Resume Uploded'), (4, 'Closed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Profile Update'), (43, 'Linkedin Draft Create'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (61, 'Will start once resume is made'), (62, 'Resume Boosted')], default=0, verbose_name='Last Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume Not Uploaded'), (3, 'Resume Uploded'), (4, 'Closed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Profile Update'), (43, 'Linkedin Draft Create'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (61, 'Will start once resume is made'), (62, 'Resume Boosted')], default=0, verbose_name='Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='last_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume Not Uploaded'), (3, 'Resume Uploded'), (4, 'Closed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Profile Update'), (43, 'Linkedin Draft Create'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (61, 'Will start once resume is made'), (62, 'Resume Boosted')], default=0, verbose_name='Last Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume Not Uploaded'), (3, 'Resume Uploded'), (4, 'Closed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Profile Update'), (43, 'Linkedin Draft Create'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (61, 'Will start once resume is made'), (62, 'Resume Boosted')], default=0, verbose_name='Operation Status'),
        ),
        migrations.DeleteModel(
            name='InterNationalProfileUser',
        ),
        migrations.AddField(
            model_name='internationalprofilecredential',
            name='oi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem'),
        ),
    ]
