# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20170720_1035'),
        ('order', '0003_auto_20170720_1221'),
    ]

    operations = [
    ]
