# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170723_1711'),
        ('order', '0007_auto_20170728_1211'),
    ]

    operations = [
    ]
