# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import order.functions


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170727_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=order.functions.get_upload_path_order_invoice),
        ),
    ]
