# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_invoice'),
        ('order', '0007_auto_20170728_1211'),
    ]

    operations = [
    ]
