# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20170801_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalprofilecredential',
            old_name='Password',
            new_name='password',
        ),
    ]
