# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20170804_1325'),
        ('order', '0008_merge_20170801_1827'),
    ]

    operations = [
    ]
