# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20170821_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orderitems', to='shop.DeliveryService'),
        ),
    ]
