# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20170821_1322'),
        ('order', '0014_auto_20170818_1128'),
    ]

    operations = [
    ]
