# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20170821_1322'),
        ('order', '0016_merge_20170823_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Coupon Code')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Value')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon', verbose_name='Coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
