# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_merge_20170823_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOrderItemOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('email_oi_status', models.PositiveIntegerField(choices=[(0, 'default'), (1, 'Sent Payment Pending Email'), (2, 'Sent Pending Item Email'), (3, 'Sent Process Mailers'), (4, 'Sent Welcome Email'), (5, 'Sent Forgot Email'), (6, 'Sent Feedback Email'), (7, 'Sent Feedback Coupon Email'), (8, 'Sent Payment Realisation Email'), (21, 'Sent Service Closed Email'), (22, 'Sent Draft Reminder Email'), (23, 'Sent Service Closed Email'), (24, 'Sent International Profile Updated Email')], default=0, verbose_name='Email Operation Status')),
                ('draft_counter', models.PositiveIntegerField(default=0)),
                ('oi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
