# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_couponorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_config',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
