# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_payment_date'),
        ('order', '0017_emailorderitemoperation'),
    ]

    operations = [
    ]
