# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0021_merge_20170901_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('type_refund', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], default='full', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount (incl. tax)')),
                ('oi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_items', to='order.OrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Ops Head Approval'), (2, 'Ops Head Rejected'), (3, 'Business Head Approval'), (4, 'Business Head Rejected'), (5, 'Dept. Head Approval'), (6, 'Dept. Head Rejected'), (7, 'Approved'), (8, 'Refunded'), (9, 'Request Updated')], default=0, verbose_name='Status')),
                ('last_status', models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Ops Head Approval'), (2, 'Ops Head Rejected'), (3, 'Business Head Approval'), (4, 'Business Head Rejected'), (5, 'Dept. Head Approval'), (6, 'Dept. Head Rejected'), (7, 'Approved'), (8, 'Refunded'), (9, 'Request Updated')], default=0, verbose_name='Last Status')),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, max_length=255, null=True, upload_to='refund/refund_ops/')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_ops_added_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, max_length=255, null=True, upload_to='refund/refund_request/')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Ops Head Approval'), (2, 'Ops Head Rejected'), (3, 'Business Head Approval'), (4, 'Business Head Rejected'), (5, 'Dept. Head Approval'), (6, 'Dept. Head Rejected'), (7, 'Approved'), (8, 'Refunded'), (9, 'Request Updated')], default=0, verbose_name='Status')),
                ('last_status', models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Ops Head Approval'), (2, 'Ops Head Rejected'), (3, 'Business Head Approval'), (4, 'Business Head Rejected'), (5, 'Dept. Head Approval'), (6, 'Dept. Head Rejected'), (7, 'Approved'), (8, 'Refunded'), (9, 'Request Updated')], default=0, verbose_name='Last Status')),
                ('refund_mode', models.CharField(choices=[('neft', 'NEFT'), ('cheque', 'CHEQUE'), ('dd', 'DD')], default='neft', max_length=255)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Refund Amount (incl. tax)')),
                ('txn_no', models.CharField(blank=True, help_text='transaction no. in case of neft and serial no. in case cheque/dd', max_length=255, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_request_added_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Order')),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
        migrations.AddField(
            model_name='refundoperation',
            name='refund_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.RefundRequest'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='refund_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.RefundRequest'),
        ),
    ]
