# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20170904_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='oi_price_excl_tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='oi_price_incl_tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price_excl_tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price_incl_tax',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price before discounts (Site Price)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Discount (incl. Wallet)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Selling Price (incl. tax)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='tax amount'),
        ),
    ]
