# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20170905_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archive_json',
            field=models.TextField(blank=True, editable=False, verbose_name='Archive JSON'),
        ),
        migrations.AddField(
            model_name='order',
            name='co_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='CP Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='conv_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Convienance Charges'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Country'),
        ),
    ]
