# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20170906_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.PositiveIntegerField(choices=[(0, 'Rs.'), (1, '$'), (2, 'AED'), (3, 'GBP')], default=0, verbose_name='Currency'),
        ),
    ]
