# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20170908_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'ordering': ('-modified',), 'permissions': (('can_view_refund_request_queue', 'Can View Refund Request Queue'), ('can_view_refund_approval_queue', 'Can View Refund Approval Queue'))},
        ),
    ]
