# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20170906_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Order number'),
        ),
    ]
