# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20170907_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='archive_json',
            field=models.TextField(blank=True, editable=False, verbose_name='Archive JSON'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coi_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='CP Order'),
        ),
    ]
