# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20170911_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='refund_mode',
            field=models.CharField(choices=[('select', 'Select Refund Mode'), ('neft', 'NEFT'), ('cheque', 'CHEQUE'), ('dd', 'DD')], default='select', max_length=255),
        ),
    ]
