# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20170911_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
