# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_auto_20170918_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='oio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderItemOperation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='oi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem'),
        ),
    ]
