# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20170918_1227'),
        ('order', '0031_auto_20170918_1121'),
    ]

    operations = [
    ]
