# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_auto_20170918_1121'),
        ('order', '0032_auto_20170918_1537'),
    ]

    operations = [
    ]
