# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_merge_20170918_1606'),
        ('order', '0032_merge_20170918_1434'),
    ]

    operations = [
    ]
