# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_auto_20171004_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalprofilecredential',
            name='candidateid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CandidateId'),
        ),
        migrations.AlterField(
            model_name='internationalprofilecredential',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocation.Country'),
        ),
        migrations.AlterField(
            model_name='internationalprofilecredential',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='internationalprofilecredential',
            name='site_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Url'),
        ),
    ]
