# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_auto_20171004_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='crm_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crm_sales_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_user_info',
            field=models.TextField(default=''),
        ),
    ]
