# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_auto_20171004_1333'),
        ('order', '0037_auto_20171005_1307'),
    ]

    operations = [
    ]
