# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_merge_20171006_1045'),
        ('order', '0039_auto_20171005_1606'),
    ]

    operations = [
    ]
