# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_merge_20171006_1617'),
        ('order', '0040_merge_20171007_1314'),
    ]

    operations = [
    ]
