# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_merge_20171007_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sales_user_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
