# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20171009_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='oi_draft',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/resumes/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_resume',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to='uploads/resumes/'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='oi_draft',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/resumes/'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='oi_resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/resumes/'),
        ),
    ]
