# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_auto_20171017_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='oi_draft',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='shinelearning/resumes/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_resume',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to='shinelearning/resumes/'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='oi_draft',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='shinelearning/resumes/'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='oi_resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='shinelearning/resumes/'),
        ),
    ]
