# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-31 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_auto_20171023_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailorderitemoperation',
            options={'ordering': ['-created']},
        ),
    ]
