# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20171031_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsorderitemoperation',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='emailorderitemoperation',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailorderitemoperation',
            name='to_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='To Email'),
        ),
        migrations.AddField(
            model_name='smsorderitemoperation',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsorderitemoperation',
            name='to_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
