# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_auto_20171207_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buy_count_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailorderitemoperation',
            name='email_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'default'), (1, 'Sent Payment Pending Email'), (2, 'Sent Process Mailers'), (3, 'Sent Welcome Email'), (4, 'Sent Forgot Email'), (5, 'Sent Feedback Email'), (6, 'Sent Feedback Coupon Email'), (7, 'Sent Payment Realisation Email'), (8, 'Sent Cart Drop Out Mailer'), (9, 'Sent Closer Mailer'), (21, 'Sent Flow1 Pending Resume Email'), (22, 'Sent First Draft Email'), (23, 'Sent Second Draft Email'), (24, 'Sent Final Draft Email'), (25, 'Sent Flow1 Process Mailer'), (26, 'Sent Reminder Draft1 Email'), (27, 'Sent Reminder Draft2 Email'), (28, 'Sent Flow1 Allocated Writer Email'), (41, 'Sent Resume Critique Pending Resume Email'), (42, 'Sent Resume Critique Allocated To Writer Email'), (43, 'Sent Resume Critique Closed Email'), (44, 'Sent Resume Critique Process Mailer'), (61, 'Sent International Profile Pending Resume Email'), (62, 'Sent International profile updated Email'), (63, 'Sent International profile Writer Assignment Email'), (64, 'Sent International profile Process Mailer'), (71, 'Sent Feature Profile Pending Resume Email'), (72, 'Sent Feature profile Updated Email'), (74, 'Sent Feature profile Process Mailer'), (91, 'Sent Resume Booster Pending Resume Email'), (92, 'Sent Resume Booster consultant/Recruiter Email'), (93, 'Sent Resume Booster Candidate Email'), (94, 'Sent Resume Booster Candidate Process Mailer'), (101, 'Sent Allocated To Writer Email For Linkedin'), (102, 'Sent Linkedin First Draft Email'), (103, 'Sent Linkedin Second Draft Email'), (104, 'Sent Linkedin Final Draft Email'), (105, 'Sent Linkedin Process Mailer'), (106, 'Sent Linkedin Draft1 Reminder Email'), (107, 'Sent Linkedin Draft2 Reminder Email'), (108, 'Sent Pending Counselling Form Email'), (109, 'Sent Linked In Tip 1'), (110, 'Sent Linked In Tip 2'), (111, 'Sent Linked In Tip 3'), (112, 'Sent Linked In Tip 4'), (113, 'Sent Linked In Tip 5'), (114, 'Sent Linked In Tip 6'), (121, 'Sent RoundOne Incomplete Profile Email'), (122, 'Sent RoundOne Process Mailer'), (131, 'Sent Pending Studymate Test Email'), (132, 'Sent Studymate Process Mailer'), (141, 'Sent Flow12 Pending Resume Email'), (142, 'Sent Flow12 First Draft Email'), (143, 'Sent Flow12 Second Draft Email'), (144, 'Sent Flow12 Final Draft Email'), (145, 'Sent Flow12 Process Mailer'), (146, 'Sent Flow12 Assignment Mailer'), (151, 'Sent Flow13 Pending Resume Email'), (152, 'Sent Flow13 First Draft Email'), (153, 'Sent Flow13 Second Draft Email'), (154, 'Sent Flow13 Final Draft Email'), (155, 'Sent Flow13 Process Mailer'), (156, 'Sent Flow13 Assignment Mailer'), (161, 'Sent Flow2 Process Mailer'), (171, 'Sent Flow6 Process Mailer'), (181, '')], default=0, verbose_name='Email Operation Status'),
        ),
    ]
