# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_auto_20180119_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
