# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_auto_20180119_1239'),
        ('order', '0050_auto_20180118_1039'),
    ]

    operations = [
    ]
