# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_orderitem_assigned_date'),
        ('order', '0051_merge_20180129_1714'),
    ]

    operations = [
    ]
