# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0052_merge_20180205_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeCallOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('wc_cat', models.PositiveIntegerField(choices=[(1, 'Process Order'), (2, 'Service Issue'), (3, 'Call Back')], default=0, verbose_name='Welcome Call Category')),
                ('wc_sub_cat', models.PositiveIntegerField(choices=[(1, 'No Issue'), (21, 'On Hold'), (22, 'Process order'), (23, 'Refund'), (24, 'Replacement Order'), (41, 'No answer'), (42, 'Not reachable'), (43, 'User is busy')], default=0, verbose_name='Welcome Call Sub-Category')),
                ('wc_status', models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'No Issue'), (20, 'On Hold'), (21, 'Process order'), (22, 'Refund'), (23, 'Replacement Order')], default=0, verbose_name='Welcome Call Status')),
                ('wc_follow_up', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcall_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='wc_cat',
            field=models.PositiveIntegerField(choices=[(1, 'Process Order'), (2, 'Service Issue'), (3, 'Call Back')], default=0, verbose_name='Welcome Call Category'),
        ),
        migrations.AddField(
            model_name='order',
            name='wc_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wc_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'No Issue'), (20, 'On Hold'), (21, 'Process order'), (22, 'Refund'), (23, 'Replacement Order')], default=0, verbose_name='Welcome Call Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(1, 'No Issue'), (21, 'On Hold'), (22, 'Process order'), (23, 'Refund'), (24, 'Replacement Order'), (41, 'No answer'), (42, 'Not reachable'), (43, 'User is busy')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wc_cat',
            field=models.PositiveIntegerField(choices=[(1, 'Process Order'), (2, 'Service Issue'), (3, 'Call Back')], default=0, verbose_name='Welcome Call Category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wc_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wc_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'No Issue'), (20, 'On Hold'), (21, 'Process order'), (22, 'Refund'), (23, 'Replacement Order')], default=0, verbose_name='Welcome Call Status'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(1, 'No Issue'), (21, 'On Hold'), (22, 'Process order'), (23, 'Refund'), (24, 'Replacement Order'), (41, 'No answer'), (42, 'Not reachable'), (43, 'User is busy')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='last_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume upload is pending'), (3, 'Resume Uploaded'), (4, 'Closed'), (5, 'Service is under progress'), (6, 'Service has been processed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (12, 'Unhold by Vendor'), (13, 'Shine Resume'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Service has been processed and Document is finalized'), (28, 'Feature profile initiated'), (29, 'Feature profile expired'), (30, 'Feature profile updated'), (42, 'Counselling Form Submitted'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (49, 'Couselling form is pending'), (61, 'Service will be initiated once resume is finalized'), (62, 'Resume Boosted'), (81, 'Pending Verification Reports'), (82, 'Service is initiated'), (101, 'To start learning , it is mandatory to take this test'), (121, 'Service has been processed and Final document is ready'), (141, 'Your profile to be shared with interviewer is pending'), (142, 'Round one is not expired'), (143, 'Round one is expired'), (161, 'Refund initiated'), (162, 'Refund under progress'), (163, 'Refunded'), (181, 'Waiting for input')], default=0, verbose_name='Last Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume upload is pending'), (3, 'Resume Uploaded'), (4, 'Closed'), (5, 'Service is under progress'), (6, 'Service has been processed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (12, 'Unhold by Vendor'), (13, 'Shine Resume'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Service has been processed and Document is finalized'), (28, 'Feature profile initiated'), (29, 'Feature profile expired'), (30, 'Feature profile updated'), (42, 'Counselling Form Submitted'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (49, 'Couselling form is pending'), (61, 'Service will be initiated once resume is finalized'), (62, 'Resume Boosted'), (81, 'Pending Verification Reports'), (82, 'Service is initiated'), (101, 'To start learning , it is mandatory to take this test'), (121, 'Service has been processed and Final document is ready'), (141, 'Your profile to be shared with interviewer is pending'), (142, 'Round one is not expired'), (143, 'Round one is expired'), (161, 'Refund initiated'), (162, 'Refund under progress'), (163, 'Refunded'), (181, 'Waiting for input')], default=0, verbose_name='Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='last_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume upload is pending'), (3, 'Resume Uploaded'), (4, 'Closed'), (5, 'Service is under progress'), (6, 'Service has been processed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (12, 'Unhold by Vendor'), (13, 'Shine Resume'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Service has been processed and Document is finalized'), (28, 'Feature profile initiated'), (29, 'Feature profile expired'), (30, 'Feature profile updated'), (42, 'Counselling Form Submitted'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (49, 'Couselling form is pending'), (61, 'Service will be initiated once resume is finalized'), (62, 'Resume Boosted'), (81, 'Pending Verification Reports'), (82, 'Service is initiated'), (101, 'To start learning , it is mandatory to take this test'), (121, 'Service has been processed and Final document is ready'), (141, 'Your profile to be shared with interviewer is pending'), (142, 'Round one is not expired'), (143, 'Round one is expired'), (161, 'Refund initiated'), (162, 'Refund under progress'), (163, 'Refunded'), (181, 'Waiting for input')], default=0, verbose_name='Last Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume upload is pending'), (3, 'Resume Uploaded'), (4, 'Closed'), (5, 'Service is under progress'), (6, 'Service has been processed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (12, 'Unhold by Vendor'), (13, 'Shine Resume'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Service has been processed and Document is finalized'), (28, 'Feature profile initiated'), (29, 'Feature profile expired'), (30, 'Feature profile updated'), (42, 'Counselling Form Submitted'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (49, 'Couselling form is pending'), (61, 'Service will be initiated once resume is finalized'), (62, 'Resume Boosted'), (81, 'Pending Verification Reports'), (82, 'Service is initiated'), (101, 'To start learning , it is mandatory to take this test'), (121, 'Service has been processed and Final document is ready'), (141, 'Your profile to be shared with interviewer is pending'), (142, 'Round one is not expired'), (143, 'Round one is expired'), (161, 'Refund initiated'), (162, 'Refund under progress'), (163, 'Refunded'), (181, 'Waiting for input')], default=0, verbose_name='Operation Status'),
        ),
        migrations.AddField(
            model_name='welcomecalloperation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Order'),
        ),
    ]
