# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-22 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20180223_1733'),
        ('order', '0053_auto_20180306_1229'),
    ]

    operations = [
    ]
