# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_merge_20180322_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wc_cat',
            field=models.PositiveIntegerField(choices=[(21, 'Process Order'), (22, 'Service Issue'), (23, 'Call Back')], default=0, verbose_name='Welcome Call Category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wc_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Re Allocated'), (21, 'No Issue'), (61, 'Service Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy')], default=0, verbose_name='Welcome Call Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wc_cat',
            field=models.PositiveIntegerField(choices=[(21, 'Process Order'), (22, 'Service Issue'), (23, 'Call Back')], default=0, verbose_name='Welcome Call Category'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wc_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Re Allocated'), (21, 'No Issue'), (61, 'Service Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy')], default=0, verbose_name='Welcome Call Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
        migrations.AlterField(
            model_name='welcomecalloperation',
            name='wc_cat',
            field=models.PositiveIntegerField(choices=[(21, 'Process Order'), (22, 'Service Issue'), (23, 'Call Back')], default=0, verbose_name='Welcome Call Category'),
        ),
        migrations.AlterField(
            model_name='welcomecalloperation',
            name='wc_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Re Allocated'), (21, 'No Issue'), (61, 'Service Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy')], default=0, verbose_name='Welcome Call Status'),
        ),
        migrations.AlterField(
            model_name='welcomecalloperation',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
    ]
