# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_auto_20180329_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsorderitemoperation',
            name='sms_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'default'), (1, 'Sent Offline Payment Sms'), (2, 'Sent Online Payment Sms'), (3, 'Sent Resume Auto Closer Sms'), (4, 'Sent Closer Sms'), (5, 'Sent Sms For Paid Order day1'), (6, 'Sent Sms For Paid Order day2'), (21, 'Sent Flow1 Pending Resume Sms'), (22, 'Sent First Draft Sms'), (23, 'Sent Second Draft Sms'), (24, 'Sent Final Draft Sms'), (25, 'Sent Reminder Draft1 Sms'), (26, 'Sent Reminder Draft2 Sms'), (27, 'Sent Flow1 Online Payment Sms'), (41, 'Sent Resume Critique Pending Resume Sms'), (42, 'Sent Resume Critique Closed Sms'), (43, 'Sent Flow3 Online Payment Sms'), (61, 'Sent International Profile Pending Resume Sms'), (62, 'Sent Flow4 Online Payment Sms'), (71, 'Sent Feature Profile Pending Resume Sms'), (72, 'Sent Flow5 Online Payment Sms'), (91, 'Sent Resume Booster Pending Resume Sms'), (92, 'Sent Resume Booster consultant/Recruiter Sms'), (93, 'Sent Resume Booster Candidate Sms'), (94, 'Sent Flow7 Online Payment Sms'), (101, 'Sent Allocated To Writer Sms For Linkedin'), (102, 'Sent Linkedin First Draft Sms'), (103, 'Sent Linkedin Second Draft Sms'), (104, 'Sent Linkedin Final Draft Sms'), (105, 'Sent Flow8 Online Payment Sms'), (106, 'Sent Linkedin Draft1 Reminder Sms'), (107, 'Sent Linkedin Draft2 Reminder Sms'), (108, 'Sent Pending Counselling Form Sms'), (121, 'Sent RoundOne Incomplete Profile Sms'), (122, 'Sent Flow9 Online Payment Sms'), (131, 'Sent Pending Studymate Test Sms'), (132, 'Sent Flow10 Online Payment Sms'), (133, 'Sent Flow10 Service Initiation Sms'), (141, 'Sent Flow12 Pending Resume Sms'), (142, 'Sent Flow12 First Draft Sms'), (143, 'Sent Flow12 Second Draft Sms'), (144, 'Sent Flow12 Final Draft Sms'), (145, 'Sent Flow12 Online Payment Sms'), (151, 'Sent Flow13 Pending Resume Sms'), (152, 'Sent Flow13 First Draft Sms'), (153, 'Sent Flow13 Second Draft Sms'), (154, 'Sent Flow13 Final Draft Sms'), (155, 'Sent Flow13 Online Payment Sms'), (161, 'Sent Flow2 Process Sms'), (162, 'Sent Flow2 Service Initiation Sms'), (171, 'Sent Flow6 Process Sms'), (172, 'Sent Flow6 Service Initiation Sms')], default=0, verbose_name='SMS Operation Status'),
        ),
    ]
