# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_auto_20180712_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailorderitemoperation',
            name='email_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'default'), (1, 'Sent Payment Pending Email'), (2, 'Sent Process Mailers'), (3, 'Sent Welcome Email'), (4, 'Sent Forgot Email'), (5, 'Sent Feedback Email'), (6, 'Sent Feedback Coupon Email'), (7, 'Sent Payment Realisation Email'), (8, 'Sent Cart Drop Out Mailer'), (9, 'Sent Closer Mailer'), (21, 'Sent Flow1 Pending Resume Email'), (22, 'Sent First Draft Email'), (23, 'Sent Second Draft Email'), (24, 'Sent Final Draft Email'), (25, 'Sent Flow1 Process Mailer'), (26, 'Sent Reminder Draft1 Email'), (27, 'Sent Reminder Draft2 Email'), (28, 'Sent Flow1 Allocated Writer Email'), (41, 'Sent Resume Critique Pending Resume Email'), (42, 'Sent Resume Critique Allocated To Writer Email'), (43, 'Sent Resume Critique Closed Email'), (44, 'Sent Resume Critique Process Mailer'), (61, 'Sent International Profile Pending Resume Email'), (62, 'Sent International profile updated Email'), (63, 'Sent International profile Writer Assignment Email'), (64, 'Sent International profile Process Mailer'), (71, 'Sent Feature Profile Pending Resume Email'), (72, 'Sent Feature profile Updated Email'), (74, 'Sent Feature profile Process Mailer'), (91, 'Sent Resume Booster Pending Resume Email'), (92, 'Sent Resume Booster consultant/Recruiter Email'), (93, 'Sent Resume Booster Candidate Email'), (94, 'Sent Resume Booster Candidate Process Mailer'), (101, 'Sent Allocated To Writer Email For Linkedin'), (102, 'Sent Linkedin First Draft Email'), (103, 'Sent Linkedin Second Draft Email'), (104, 'Sent Linkedin Final Draft Email'), (105, 'Sent Linkedin Process Mailer'), (106, 'Sent Linkedin Draft1 Reminder Email'), (107, 'Sent Linkedin Draft2 Reminder Email'), (108, 'Sent Pending Counselling Form Email'), (109, 'Sent Linked In Tip 1'), (110, 'Sent Linked In Tip 2'), (111, 'Sent Linked In Tip 3'), (112, 'Sent Linked In Tip 4'), (113, 'Sent Linked In Tip 5'), (114, 'Sent Linked In Tip 6'), (121, 'Sent RoundOne Incomplete Profile Email'), (122, 'Sent RoundOne Process Mailer'), (131, 'Sent Pending Studymate Test Email'), (132, 'Sent Studymate Process Mailer'), (141, 'Sent Flow12 Pending Resume Email'), (142, 'Sent Flow12 First Draft Email'), (143, 'Sent Flow12 Second Draft Email'), (144, 'Sent Flow12 Final Draft Email'), (145, 'Sent Flow12 Process Mailer'), (146, 'Sent Flow12 Assignment Mailer'), (151, 'Sent Flow13 Pending Resume Email'), (152, 'Sent Flow13 First Draft Email'), (153, 'Sent Flow13 Second Draft Email'), (154, 'Sent Flow13 Final Draft Email'), (155, 'Sent Flow13 Process Mailer'), (156, 'Sent Flow13 Assignment Mailer'), (161, 'Sent Flow2 Process Mailer'), (171, 'Sent Flow6 Process Mailer'), (181, ''), (191, 'Sent Flow14 Process Mailer'), (192, 'Sent Flow14 Service Initiation Mailer')], default=0, verbose_name='Email Operation Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wc_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Re Allocated'), (41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (61, 'Service Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy')], default=0, verbose_name='Welcome Call Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wc_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Re Allocated'), (41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (61, 'Service Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy')], default=0, verbose_name='Welcome Call Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
        migrations.AlterField(
            model_name='smsorderitemoperation',
            name='sms_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'default'), (1, 'Sent Offline Payment Sms'), (2, 'Sent Online Payment Sms'), (3, 'Sent Resume Auto Closer Sms'), (4, 'Sent Closer Sms'), (5, 'Sent Sms For Paid Order day1'), (6, 'Sent Sms For Paid Order day2'), (21, 'Sent Flow1 Pending Resume Sms'), (22, 'Sent First Draft Sms'), (23, 'Sent Second Draft Sms'), (24, 'Sent Final Draft Sms'), (25, 'Sent Reminder Draft1 Sms'), (26, 'Sent Reminder Draft2 Sms'), (27, 'Sent Flow1 Online Payment Sms'), (41, 'Sent Resume Critique Pending Resume Sms'), (42, 'Sent Resume Critique Closed Sms'), (43, 'Sent Flow3 Online Payment Sms'), (61, 'Sent International Profile Pending Resume Sms'), (62, 'Sent Flow4 Online Payment Sms'), (71, 'Sent Feature Profile Pending Resume Sms'), (72, 'Sent Flow5 Online Payment Sms'), (91, 'Sent Resume Booster Pending Resume Sms'), (92, 'Sent Resume Booster consultant/Recruiter Sms'), (93, 'Sent Resume Booster Candidate Sms'), (94, 'Sent Flow7 Online Payment Sms'), (101, 'Sent Allocated To Writer Sms For Linkedin'), (102, 'Sent Linkedin First Draft Sms'), (103, 'Sent Linkedin Second Draft Sms'), (104, 'Sent Linkedin Final Draft Sms'), (105, 'Sent Flow8 Online Payment Sms'), (106, 'Sent Linkedin Draft1 Reminder Sms'), (107, 'Sent Linkedin Draft2 Reminder Sms'), (108, 'Sent Pending Counselling Form Sms'), (121, 'Sent RoundOne Incomplete Profile Sms'), (122, 'Sent Flow9 Online Payment Sms'), (131, 'Sent Pending Studymate Test Sms'), (132, 'Sent Flow10 Online Payment Sms'), (133, 'Sent Flow10 Service Initiation Sms'), (141, 'Sent Flow12 Pending Resume Sms'), (142, 'Sent Flow12 First Draft Sms'), (143, 'Sent Flow12 Second Draft Sms'), (144, 'Sent Flow12 Final Draft Sms'), (145, 'Sent Flow12 Online Payment Sms'), (151, 'Sent Flow13 Pending Resume Sms'), (152, 'Sent Flow13 First Draft Sms'), (153, 'Sent Flow13 Second Draft Sms'), (154, 'Sent Flow13 Final Draft Sms'), (155, 'Sent Flow13 Online Payment Sms'), (161, 'Sent Flow2 Process Sms'), (162, 'Sent Flow2 Service Initiation Sms'), (171, 'Sent Flow6 Process Sms'), (172, 'Sent Flow6 Service Initiation Sms'), (191, 'Sent Flow14 Process Sms'), (192, 'Sent Flow14 Service Initiation Sms')], default=0, verbose_name='SMS Operation Status'),
        ),
        migrations.AlterField(
            model_name='welcomecalloperation',
            name='wc_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Re Allocated'), (41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (61, 'Service Issue'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy')], default=0, verbose_name='Welcome Call Status'),
        ),
        migrations.AlterField(
            model_name='welcomecalloperation',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replacement Order'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
    ]
