# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0063_auto_20190314_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='replacement_order_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Replacement Order number'),
        ),
    ]
