# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-10 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0063_auto_20190314_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='welcome_call_records',
            field=models.TextField(blank=True, verbose_name='Call Recording'),
        ),
    ]
