# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_order_welcome_call_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='welcome_call_records',
            field=models.TextField(blank=True, null=True, verbose_name='Call Recording'),
        ),
    ]
