# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-27 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_auto_20190411_1731'),
        ('order', '0064_orderitem_replacement_order_id'),
    ]

    operations = [
    ]
