# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-09 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0066_merge_20190503_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='autologin_url',
            field=models.TextField(blank=True, null=True, verbose_name='Auto Login Url'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replace Item'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='last_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume upload is pending'), (3, 'Resume Uploaded'), (4, 'Closed'), (5, 'Service is under progress'), (6, 'Service has been processed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (12, 'Unhold by Vendor'), (13, 'Shine Resume'), (14, 'Cancelled'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Service has been processed and Document is finalized'), (28, 'Feature profile initiated'), (29, 'Feature profile expired'), (30, 'Feature profile updated'), (42, 'Counselling Form Submitted'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (49, 'Couselling form is pending'), (61, 'Service will be initiated once resume is finalized'), (62, 'Resume Boosted'), (81, 'Pending Verification Reports'), (82, 'Service is initiated'), (101, 'To start learning , it is mandatory to take this test'), (121, 'Service has been processed and Final document is ready'), (141, 'Your profile to be shared with interviewer is pending'), (142, 'Round one is not expired'), (143, 'Round one is expired'), (161, 'Refund initiated'), (162, 'Refund under progress'), (163, 'Refunded'), (164, 'Replaced'), (181, 'Waiting for input')], default=0, verbose_name='Last Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume upload is pending'), (3, 'Resume Uploaded'), (4, 'Closed'), (5, 'Service is under progress'), (6, 'Service has been processed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (12, 'Unhold by Vendor'), (13, 'Shine Resume'), (14, 'Cancelled'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Service has been processed and Document is finalized'), (28, 'Feature profile initiated'), (29, 'Feature profile expired'), (30, 'Feature profile updated'), (42, 'Counselling Form Submitted'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (49, 'Couselling form is pending'), (61, 'Service will be initiated once resume is finalized'), (62, 'Resume Boosted'), (81, 'Pending Verification Reports'), (82, 'Service is initiated'), (101, 'To start learning , it is mandatory to take this test'), (121, 'Service has been processed and Final document is ready'), (141, 'Your profile to be shared with interviewer is pending'), (142, 'Round one is not expired'), (143, 'Round one is expired'), (161, 'Refund initiated'), (162, 'Refund under progress'), (163, 'Refunded'), (164, 'Replaced'), (181, 'Waiting for input')], default=0, verbose_name='Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replace Item'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='last_oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume upload is pending'), (3, 'Resume Uploaded'), (4, 'Closed'), (5, 'Service is under progress'), (6, 'Service has been processed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (12, 'Unhold by Vendor'), (13, 'Shine Resume'), (14, 'Cancelled'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Service has been processed and Document is finalized'), (28, 'Feature profile initiated'), (29, 'Feature profile expired'), (30, 'Feature profile updated'), (42, 'Counselling Form Submitted'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (49, 'Couselling form is pending'), (61, 'Service will be initiated once resume is finalized'), (62, 'Resume Boosted'), (81, 'Pending Verification Reports'), (82, 'Service is initiated'), (101, 'To start learning , it is mandatory to take this test'), (121, 'Service has been processed and Final document is ready'), (141, 'Your profile to be shared with interviewer is pending'), (142, 'Round one is not expired'), (143, 'Round one is expired'), (161, 'Refund initiated'), (162, 'Refund under progress'), (163, 'Refunded'), (164, 'Replaced'), (181, 'Waiting for input')], default=0, verbose_name='Last Operation Status'),
        ),
        migrations.AlterField(
            model_name='orderitemoperation',
            name='oi_status',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Assigned'), (2, 'Resume upload is pending'), (3, 'Resume Uploaded'), (4, 'Closed'), (5, 'Service is under progress'), (6, 'Service has been processed'), (10, 'On Hold by Vendor'), (11, 'Archived'), (12, 'Unhold by Vendor'), (13, 'Shine Resume'), (14, 'Cancelled'), (21, 'Upload Draft'), (22, 'Draft Uploaded'), (23, 'Pending Approval'), (24, 'Approved'), (25, 'Rejected By Admin'), (26, 'Rejected By Candidate'), (27, 'Service has been processed and Document is finalized'), (28, 'Feature profile initiated'), (29, 'Feature profile expired'), (30, 'Feature profile updated'), (42, 'Counselling Form Submitted'), (44, 'Linkedin Draft Created'), (45, 'Linkedin Pending Approval'), (46, 'Linkedin Approved'), (47, 'Linkedin Rejected By Admin'), (48, 'Linkedi Rejected By Candidate'), (49, 'Couselling form is pending'), (61, 'Service will be initiated once resume is finalized'), (62, 'Resume Boosted'), (81, 'Pending Verification Reports'), (82, 'Service is initiated'), (101, 'To start learning , it is mandatory to take this test'), (121, 'Service has been processed and Final document is ready'), (141, 'Your profile to be shared with interviewer is pending'), (142, 'Round one is not expired'), (143, 'Round one is expired'), (161, 'Refund initiated'), (162, 'Refund under progress'), (163, 'Refunded'), (164, 'Replaced'), (181, 'Waiting for input')], default=0, verbose_name='Operation Status'),
        ),
        migrations.AlterField(
            model_name='welcomecalloperation',
            name='wc_sub_cat',
            field=models.PositiveIntegerField(choices=[(41, 'No Issue'), (42, 'Order Processed After Final Reminder'), (62, 'On Hold'), (63, 'Process order'), (64, 'Refund'), (65, 'Replace Item'), (81, 'No answer'), (82, 'Not reachable'), (83, 'User is busy'), (61, 'Service Issue')], default=0, verbose_name='Welcome Call Sub-Category'),
        ),
    ]
