# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-03 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_auto_20190509_0921'),
        ('order', '0066_merge_20190527_1428'),
    ]

    operations = [
    ]
