# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_auto_20190606_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='autologin_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Auto Login Url'),
        ),
    ]
