# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-13 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_auto_20190606_1530'),
        ('order', '0066_merge_20190522_1538'),
    ]

    operations = [
    ]
