# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-24 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_merge_20190613_2055'),
        ('order', '0067_auto_20190524_1626'),
    ]

    operations = [
    ]
