# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0071_merge_20190613_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=100, verbose_name='Candidate Id')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Assigned'), (3, 'Closed')], default=1)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date')),
                ('comment', models.CharField(max_length=500, verbose_name='Feedback Comment')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Last Payment Date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(blank=True, choices=[(101, 'Rating'), (102, 'Referral'), (103, 'Shared Feedback'), (201, 'Unaware of the services'), (202, 'Login details not received'), (203, 'Draft not received'), (204, 'No relevancy'), (301, '100% job guarantee'), (302, 'Up-selling'), (303, 'Job&Interview guarantee'), (401, 'Call back scheduled'), (402, 'Not Responded')], null=True)),
                ('resolution', models.SmallIntegerField(blank=True, choices=[(1, 'Shared the service details'), (2, 'Shared the login details'), (3, 'Shared the drafts'), (4, 'Swapping of the services'), (5, 'Complimentary service'), (6, 'Educate about the services')], null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Feedback Comment')),
                ('customer_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.CustomerFeedback')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemFeedbackOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.SmallIntegerField(blank=True, choices=[(101, 'Rating'), (102, 'Referral'), (103, 'Shared Feedback'), (201, 'Unaware of the services'), (202, 'Login details not received'), (203, 'Draft not received'), (204, 'No relevancy'), (301, '100% job guarantee'), (302, 'Up-selling'), (303, 'Job&Interview guarantee'), (401, 'Call back scheduled'), (402, 'Not Responded')], null=True)),
                ('resolution', models.SmallIntegerField(blank=True, choices=[(1, 'Shared the service details'), (2, 'Shared the login details'), (3, 'Shared the drafts'), (4, 'Swapping of the services'), (5, 'Complimentary service'), (6, 'Educate about the services')], null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Feedback Comment')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CustomerFeedback')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
            ],
        ),
    ]
