# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_customerfeedback_orderitemfeedback_orderitemfeedbackoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
    ]
