# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_auto_20190704_1223'),
        ('order', '0071_merge_20190613_2055'),
    ]

    operations = [
    ]
