# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_customerfeedback_orderitemfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Assigned'), (3, 'Closed')], default=1),
        ),
    ]
