# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0073_auto_20190725_1745'),
        ('order', '0073_merge_20190711_2002'),
    ]

    operations = [
    ]
