# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-29 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0073_auto_20190726_1308'),
        ('order', '0073_merge_20190711_2002'),
    ]

    operations = [
    ]
