# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0074_auto_20190714_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderITemFeedbackOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.SmallIntegerField(choices=[(101, 'Rating'), (102, 'Referral'), (103, 'Shared Feedback'), (201, 'Unaware of the services'), (202, 'Login details not received'), (203, 'Draft not received'), (204, 'No relevancy'), (301, '100% job guarantee'), (302, 'Up-selling'), (303, 'Job&Interview guarantee'), (401, 'Call back scheduled'), (402, 'Not Responded')])),
                ('resolution', models.SmallIntegerField(choices=[(1, 'Shared the service details'), (2, 'Shared the login details'), (3, 'Shared the drafts'), (4, 'Swapping of the services'), (5, 'Complimentary service'), (6, 'Educate about the services')])),
                ('comment', models.CharField(max_length=500, verbose_name='Feedback Comment')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='ltv',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='LTV'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
