# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0075_auto_20190717_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemfeedbackoperation',
            name='customer_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CustomerFeedback'),
        ),
        migrations.AddField(
            model_name='orderitemfeedbackoperation',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem'),
        ),
    ]
