# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0075_auto_20190731_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='ltv',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
