# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-19 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20190718_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemfeedback',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Feedback Comment'),
        ),
    ]
