# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-31 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20190731_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='ltv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
