# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-02 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20190801_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback Comment'),
        ),
        migrations.AlterField(
            model_name='orderitemfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback Comment'),
        ),
        migrations.AlterField(
            model_name='orderitemfeedbackoperation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback Comment'),
        ),
    ]
