# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_orderitemfeedback_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemfeedbackoperation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
