# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20190802_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='service_resume_upload_shine',
            field=models.BooleanField(default=True),
        ),
    ]
