# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20190802_1211'),
        ('order', '0075_auto_20190806_1253'),
    ]

    operations = [
    ]
