# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-12 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_orderitem_auto_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='service_resume_upload_shine',
            field=models.BooleanField(default=False),
        ),
    ]
