# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-09 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_auto_20190816_1836'),
        ('order', '0079_auto_20190821_1559'),
        ('order', '0078_auto_20190826_1733'),
    ]

    operations = [
    ]
