# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_auto_20190723_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
    ]
