# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-23 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0080_merge_20190905_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTVMonthlyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltv_bracket', models.SmallIntegerField(choices=[(0, '0-5k'), (1, '5-10k'), (2, '10-20k'), (3, '20-40k'), (4, '40-60k'), (5, '60-80k'), (6, '80-100k'), (7, '100-125k'), (8, '125-150k'), (9, '150-175k'), (10, '175k+')])),
                ('total_users', models.IntegerField()),
                ('total_order_count', models.IntegerField()),
                ('total_item_count', models.IntegerField()),
                ('crm_order_count', models.IntegerField()),
                ('crm_item_count', models.IntegerField()),
                ('learning_order_count', models.IntegerField()),
                ('learning_item_count', models.IntegerField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018)])),
                ('month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('candidate_id_ltv_mapping', models.TextField()),
            ],
        ),
    ]
