# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-07 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0082_merge_20190927_1721'),
        ('order', '0081_auto_20191004_1210'),
    ]

    operations = [
    ]
