# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-09 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0083_merge_20191009_1542'),
    ]

    operations = [
    #     migrations.AddField(
    #         model_name='ltvmonthlyrecord',
    #         name='crm_users',
    #         field=models.IntegerField(default=0),
    #     ),
    #     migrations.AddField(
    #         model_name='ltvmonthlyrecord',
    #         name='learning_users',
    #         field=models.IntegerField(default=0),
    #     ),
    ]
