# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-11 06:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0085_auto_20191010_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLTVRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltv_bracket', models.SmallIntegerField(choices=[(0, '0-5k'), (1, '5-10k'), (2, '10-20k'), (3, '20-40k'), (4, '40-60k'), (5, '60-80k'), (6, '80-100k'), (7, '100-125k'), (8, '125-150k'), (9, '150-175k'), (10, '175k+')])),
                ('crm_order_ids', models.TextField()),
                ('learning_order_ids', models.TextField()),
                ('crm_item_count', models.IntegerField()),
                ('learning_item_count', models.IntegerField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018)])),
                ('month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('candidate_ids', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ltvmonthlyrecord',
            name='crm_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ltvmonthlyrecord',
            name='learning_users',
            field=models.IntegerField(default=0),
        ),
    ]
