# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0085_auto_20191010_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltvmonthlyrecord',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ltvmonthlyrecord',
            name='learning_order_ids',
            field=models.TextField(default=True),
        ),
    ]
