# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-29 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20191011_1141'),
        ('order', '0083_merge_20191007_1557'),
    ]

    operations = [
    ]
