# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20191011_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='category',
            field=models.SmallIntegerField(blank=True, choices=[(101, 'Service Utilized'), (102, 'Not Utilized'), (103, 'In process'), (104, 'Annoyed'), (105, 'Call Back'), (201, 'Not Connected')], null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='resolution',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Shared the service details'), (2, 'Shared the login details'), (3, 'Shared the drafts'), (4, 'Swapping of the services'), (5, 'Complimentary service'), (6, 'Educate about the services')], null=True),
        ),
        migrations.AddField(
            model_name='orderitemfeedbackoperation',
            name='feedback_category',
            field=models.SmallIntegerField(choices=[(101, 'Service Utilized'), (102, 'Not Utilized'), (103, 'In process'), (104, 'Annoyed'), (105, 'Call Back'), (201, 'Not Connected')], default=-1),
        ),
        migrations.AddField(
            model_name='orderitemfeedbackoperation',
            name='feedback_resolution',
            field=models.SmallIntegerField(choices=[(1, 'Shared the service details'), (2, 'Shared the login details'), (3, 'Shared the drafts'), (4, 'Swapping of the services'), (5, 'Complimentary service'), (6, 'Educate about the services')], default=-1),
        ),
        migrations.AddField(
            model_name='orderitemfeedbackoperation',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
        migrations.AlterField(
            model_name='orderitemfeedbackoperation',
            name='oi_type',
            field=models.SmallIntegerField(choices=[(1, 'Order Item Updated'), (2, 'Feedback Message Updated'), (3, 'Assigned'), (4, 'Reassigned'), (5, 'Follow Up')], default=-1),
        ),
    ]
