# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0083_merge_20191007_1557'),
        ('order', '0087_auto_20191017_1455'),
    ]

    operations = [
    ]
