# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-04 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0088_merge_20191104_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemfeedbackoperation',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
        migrations.AlterField(
            model_name='orderitemfeedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitemfeedbackoperation',
            name='oi_type',
            field=models.SmallIntegerField(choices=[(1, 'Order Item Updated'), (2, 'Feedback Message Updated'), (3, 'Assigned'), (4, 'Reassigned'), (5, 'Follow Up'), (6, 'Customer Category Updated'), (7, 'Customer Resolution Updated')], default=-1),
        ),
    ]
