# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-21 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_auto_20191104_1318'),
        ('order', '0087_merge_20191029_1052'),
    ]

    operations = [
    ]
