# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-17 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_merge_20191121_1839'),
        # ('order', '0091_auto_20191205_1153'),
    ]

    operations = [
    ]
