# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-17 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_merge_20191204_1503'),
        ('order', '0091_auto_20191218_1522'),
        ('order', '0093_merge_20191230_1325'),
    ]

    operations = [
    ]
