# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('order', '0093_merge_20191230_1325'),
        ('order', '0090_merge_20191204_1503'),
    ]

    operations = [
    ]
