# Generated by Django 2.2.10 on 2020-05-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('order', '0097_auto_20200505_1324'),
        # ('order', '0096_auto_20200430_1649'),
        # ('order', '0095_merge_20200430_1635'),
        # ('order', '0097_auto_20200203_1200'),
        # ('order', '0096_auto_20200203_1200'),
        # ('order', '0095_merge_20200129_1416'),
        # ('order', '0079_orderitem_service_resume_upload_shine'),
        # ('order', '0078_orderitem_auto_upload'),
        # ('order', '0095_merge_20200129_1432'),
        ('order', '0094_merge_20200109_1056'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='orderitem',
        #     name='is_resume_candidate_upload',
        #     field=models.BooleanField(default=False),
        # ),
    ]
