# Generated by Django 2.2.10 on 2020-05-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_merge_20200109_1056'),
        # ('order', '0094_merge_20200110_1037'),
        # ('order', '0094_merge_20200117_1258'),
    ]

    operations = [
    ]
