# Generated by Django 2.2.10 on 2020-05-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_merge_20200109_1056'),
        ('order', '0091_auto_20191218_1522'),
        ('order', '0093_merge_20191230_1325'),
    ]

    operations = [
    ]
