# Generated by Django 2.2.10 on 2020-05-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0098_merge_20200519_1907'),
    ]

    operations = [
    ]
