# Generated by Django 2.2.10 on 2020-04-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_merge_20200117_1258'),
        ('order', '0094_merge_20200109_1056'),
        ('order', '0094_merge_20200110_1037'),
    ]

    operations = [
    ]
