# Generated by Django 2.2.10 on 2020-05-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_merge_20200521_1552'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='GazettedHoliday',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('holiday_date', models.DateField(unique=True)),
        #         ('holiday_type', models.CharField(blank=True, max_length=25, null=True)),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='orderitem',
        #     name='is_resume_candidate_upload',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='order',
            name='site',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Shinelearning'), (1, 'Cpcrm'), (2, 'ResumeShine.com')], default=0),
        ),
    ]
