# Generated by Django 2.2.10 on 2020-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_merge_20200430_1635'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='GazettedHolidays',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('holiday_date', models.DateTimeField(blank=True, null=True, verbose_name='Holiday Date')),
        #         ('holiday_type', models.CharField(blank=True, max_length=20, null=True)),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='orderitem',
        #     name='is_resume_candidate_upload',
        #     field=models.BooleanField(default=False),
        # ),
    ]
