# Generated by Django 2.2.10 on 2020-04-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_merge_20200420_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_resume_candidate_upload',
            field=models.BooleanField(default=False),
        ),
    ]
