# Generated by Django 2.2.10 on 2020-06-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0096_auto_20200521_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazettedHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_resume_candidate_upload',
            field=models.BooleanField(default=False),
        ),
    ]
