# Generated by Django 2.2.10 on 2020-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0096_auto_20200430_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='GazettedHoliday',
            fields=[
                ('holiday_date', models.DateField(primary_key=True, serialize=False)),
                ('holiday_type', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_resume_candidate_upload',
            field=models.BooleanField(default=False),
        ),
    ]
