# Generated by Django 2.2.10 on 2020-05-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0097_auto_20200505_1324'),
        ('order', '0096_orderitem_is_resume_candidate_upload'),
    ]

    operations = [
    ]
