# Generated by Django 2.2.10 on 2020-06-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0097_auto_20200605_1025'),
        ('order', '0091_auto_20191218_1522'),
    ]

    operations = [
    ]
