# Generated by Django 2.2.10 on 2020-07-10 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0098_merge_20200609_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsVidhyaRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('AV_Id', models.CharField(max_length=255, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'user_activation_pending'), (2, 'enrollment_pending'), (3, 'enrollment_done'), (4, 'enrollment_error')], default=0)),
                ('status_msg', models.CharField(max_length=100, verbose_name='status message')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='remarks')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='av_orders', to='order.OrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
