# Generated by Django 2.2.10 on 2020-07-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0099_order_ref_order'),
        ('order', '0099_analyticsvidhyarecord'),
    ]

    operations = [
    ]
