# Generated by Django 2.2.10 on 2020-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0101_auto_20200825_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='approved_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
