import { resumeShineSiteDomain, siteDomain } from './domains';


const freeResourcesList = [
    { 
        name: 'Resume Formats', 
        url: `${resumeShineSiteDomain}/cms/resume-format/1/`, 
        id: 'resume_formats',
        sideNavType: 'freeResources',
        children: [
            { name: 'Freshers', url: `${resumeShineSiteDomain}/cms/resume-format/freshers-2/2/`, id:'freshers' },
            { name: 'Banking Freshers', url: `${resumeShineSiteDomain}/cms/resume-format/banking-freshers/4/`, id:'banking_freshers' },
            { name: 'Experienced Professional', url: `${resumeShineSiteDomain}/cms/resume-format/experienced-professionals/6/`, id:'experienced_professionals' },
            { name: 'Engineers', url: `${resumeShineSiteDomain}/cms/resume-format/engineers-2/20/`, id:'engineers' },
            { name: 'IT', url: `${resumeShineSiteDomain}/cms/resume-format/it/53/`, id:'it'},
            { name: 'View all', url:`${resumeShineSiteDomain}/cms/resume-format/1/`, id:'view_all'},
        ]
    },
    {
        name: 'Resignation Letter Formats',
        url: `${resumeShineSiteDomain}/cms/resignation-letter-formats-samples/3/`, 
        id:'resignation_formats',
        sideNavType: 'freeResources',
        children:[
            { name: 'With Notice Period', url: `${resumeShineSiteDomain}/cms/resignation-letter-formats-samples/notice-period/5/`, id:'with_notice_period' },
            { name: 'Personal Reasons', url: `${resumeShineSiteDomain}/cms/resignation-letter-formats-samples/personal-reasons/15/`, id:'personal_reasons' },
            { name: 'Higher Studies', url: `${resumeShineSiteDomain}/cms/resignation-letter-formats-samples/higher-studies-or-going-abroad/49/`, id:'higher_studies' },
            { name: 'Without Notice Period', url: `${resumeShineSiteDomain}/cms/resignation-letter-formats-samples/without-notice-period/17/`, id:'without_notice_period' },
            { name: 'Family Illness', url: `${resumeShineSiteDomain}/cms/resignation-letter-formats-samples/family-illness/18/`, id:'family_illness'},
            { name: 'View all', url:`${resumeShineSiteDomain}/cms/resignation-letter-formats-samples/3/`, id:'view_all'}
        ]
    },
    { 
        name: 'Cover Letter Formats', 
        url: `${resumeShineSiteDomain}/cms/cover-letter-format/7/`, 
        id: 'cover_letter',
        sideNavType: 'freeResources',
        children: [
            { name: 'Freshers', url: `${resumeShineSiteDomain}/cms/cover-letter-format/freshers/8/`, id:'freshers' },
            { name: 'Engineers', url: `${resumeShineSiteDomain}/cms/cover-letter-format/engineers/9/`, id:'engineers' },
            { name: 'View all', url:`${resumeShineSiteDomain}/cms/cover-letter-format/7/`, id:'view_all'}
        ]
    },
    { 
        name: 'Resume Templates', 
        url: `${resumeShineSiteDomain}/cms/resume-samples-and-templates/50/`, 
        id: 'resume_templates',
        sideNavType: 'freeResources',
        children: [
            { name: 'Pharma', url: `${resumeShineSiteDomain}/cms/resume-samples-and-templates/pharma/34/`, id:'pharma' },
            { name: 'Freshers', url: `${resumeShineSiteDomain}/cms/resume-samples-and-templates/freshers-3/55/`, id:'freshers' },
            { name: 'View all', url:`${resumeShineSiteDomain}/cms/resume-samples-and-templates/50/`, id:'view_all'}
        ]
    }, 
    { 
        name: 'LinkedIn Summary Example', 
        url:`${resumeShineSiteDomain}/cms/linkedin-summary-examples/43/`, 
        id: 'linkedin_summary',
        sideNavType: 'freeResources',
        children: [
            { name: 'HR Professionals', url: `${resumeShineSiteDomain}/cms/linkedin-summary-examples/hr-professional/36/`, id:'hr_professional' },
            { name: 'View all', url:`${resumeShineSiteDomain}/cms/linkedin-summary-examples/43/`, id:'view_all'}
        ]
    },
    { 
        name: 'Relieving Letter', 
        url:`${resumeShineSiteDomain}/cms/relieving-letter-format/58/`, 
        id: 'relieving_letter',
        sideNavType: 'freeResources',
        children: []
    },
]
 

const jobAssistanceList = [
    { name: 'Resume Writing', url: `${resumeShineSiteDomain}`, id: 'resume_writing'},
    { name: 'International Resume', url: `${resumeShineSiteDomain}/product/entry-level-freshers-4/2553/`, id: 'international_resume' },
    { name: 'Visual Resume', url: `${resumeShineSiteDomain}/product/entry-level-freshers/2052/`, id: 'visual_resume' },
    { name: 'Jobs On The Move',  url: `${resumeShineSiteDomain}/product/jobs-on-the-move-3/3411/`, id: 'jobs_move' },
    { name: 'LinkedIn Profile', url: `${resumeShineSiteDomain}/product/linkedin-profile-writing/fresher-level/1925/`, id: 'linkedin_profile' },
    { name: 'Featured Profile', url: `${resumeShineSiteDomain}/product/featured-profile-10/1939/`, id: 'featured_profile' },
    { name: 'Application Highlighter', url: `${resumeShineSiteDomain}/product/application-highlighter-3/4117/`, id: 'application_highlighter' },
    { name: 'Resume Score Checker', url: `${resumeShineSiteDomain}/resume-score-checker/`, id: 'score_checker' },
]

const categoryList = [
    { 
        name: 'Sales And Marketing', 
        url: `${siteDomain}/courses/sales-and-marketing/17/`, 
        id: 'sales_marketing',
        sideNavType: 'allCourses',
        children: [
            { name: 'Digital Marketing', url: `/courses/sales-and-marketing/digital-marketing/32/`, id:'digital_marketing', sideNavType: 'courses' },
            { name: 'Sales', url: `/courses/sales-and-marketing/sales/18/`, id:'sales', sideNavType: 'courses' },
            { name: 'Retail', url: `/courses/sales-and-marketing/retail/35/`, id:'retail', sideNavType: 'courses' },
            { name: 'Product Management', url: `/courses/sales-and-marketing/product-marketing/24/`, id:'product_management', sideNavType: 'courses' },
            { name: 'Service Management', url: `/courses/sales-and-marketing/service-marketing/30/`, id:'service_management', sideNavType: 'courses'},
        ]
    },
    {
        name: 'Operation Management',
        url: `${siteDomain}/courses/operation-management/19/`,
        id:'operation_management',
        sideNavType: 'allCourses',
        children:[
            { name: 'Six Sigma', url: `/courses/operation-management/six-sigma/193/`, id:'six_sigma', sideNavType: 'courses' },
            { name: 'Project Management', url: `/courses/operation-management/project-management/123/`, id:'project_management', sideNavType: 'courses' },
            { name: 'Logistic and Supply Chain', url: `/courses/operation-management/logistics-and-supply-chain/135/`, id:'logistic_and_supply_chain', sideNavType: 'courses' },
            { name: 'Service Quality', url: `/courses/operation-management/service-quality/316/`, id:'service_quality', sideNavType: 'courses' },
            { name: 'Production', url: `/courses/operation-management/production/39/`, id:'production', sideNavType: 'courses'},
            { name: 'Customer Care', url:`/courses/operation-management/customer-care/37/`, id:'customer_care', sideNavType: 'courses'}
        ]
    },
    { 
        name: 'Banking & Finance', 
        url: `${siteDomain}/courses/banking-and-finance/20/`,
        id: 'banking_finance',
        sideNavType: 'allCourses',
        children: [
            { name: 'Advanced Accounting', url: `/courses/banking-finance/advanced-accounting/114/`, id:'advanced_accounting', sideNavType: 'courses'},
            { name: 'Banking', url: `/courses/banking-finance/banking/113/`, id:'banking', sideNavType: 'courses' },
            { name: 'Risk Management', url:`/courses/banking-finance/risk-management/95/`, id:'risk_management', sideNavType: 'courses'},
            { name: 'Stock Market Training', url: `/courses/banking-finance/stock-trading/94/`, id:'stock_market_training', sideNavType: 'courses' },
            { name: 'Financial Resporting and Management', url: `/courses/banking-finance/financial-reporting-and-management/103/`, id:'financial_reporting_and_management', sideNavType: 'courses' },
            { name: 'Commercial Operation', url:`/courses/banking-finance/commercial-operation/112/`, id:'commercial_operation', sideNavType: 'courses'},
            { name: 'Investment Banking', url:`/courses/banking-finance/investment-banking/100/`, id:'investment_banking', sideNavType: 'courses'},
            { name: 'GST', url: `/courses/banking-finance/gst-2/507/`, id:'gst', sideNavType: 'courses' },
        ]
    },
    { 
        name: 'Information Technology', 
        url: `${siteDomain}/courses/it-information-technology/22/`, 
        id: 'informaton_technology',
        sideNavType: 'allCourses',
        children: [
            { name: 'Big Data', url: `/courses/it-information-technology/big-data/84/`, id:'big_data', sideNavType: 'courses' },
            { name: 'Project Management', url: `/courses/operation-management/project-management/123/`, id:'project_management', sideNavType: 'courses' },
            { name: 'IT Software', url:`/courses/it-information-technology/it-software/53/`, id:'it_software', sideNavType: 'courses'},
            { name: 'Graphic Design', url: `/courses/it-information-technology/graphic-design/54/`, id:'graphic_design', sideNavType: 'courses' },
            { name: 'Cloud Computing', url: `/courses/it-information-technology/cloud-computing/82/`, id:'cloud_computing', sideNavType: 'courses' },
            { name: 'MS Skills', url:`/courses/it-information-technology/ms-skills/98/`, id:'ms_skills', sideNavType: 'courses'},
            { name: 'IT Language', url: `/courses/it-information-technology/it-language/80/`, id:'it_language', sideNavType: 'courses' },
            { name: 'Blockchain', url: `/courses/it-information-technology/blockchain/496/`, id:'blockchain', sideNavType: 'courses' },
            { name: 'Data Science', url:`/courses/it-information-technology/data-science/497/`, id:'data_science', sideNavType: 'courses'}
        ]
    }, 
    { 
        name: 'Human Resources', 
        url:`${siteDomain}/courses/hr-human-resource/25/`, 
        id: 'human_resources',
        sideNavType: 'allCourses',
        children: [
            { name: 'Talent Aquisition', url: `/courses/hr-human-resource/talent-acquisition/93/`, id:'talent_acquisition', sideNavType: 'courses' },
            { name: 'Organisational Structure', url:`/courses/hr-human-resource/organizational-structure/97/`, id:'organisational_structure', sideNavType: 'courses'},
            { name: 'Training & Development', url: `/courses/hr-human-resource/training-and-development/91/`, id:'training_and_development', sideNavType: 'courses' },
            { name: 'Compensation', url:`/courses/hr-human-resource/compensation-2/110/`, id:'compensation', sideNavType: 'courses'}
        ]
    },
    { 
        name: 'Management', 
        url:`${siteDomain}/courses/management/27/`, 
        id: 'management',
        sideNavType: 'allCourses',
        children: [
            { name: 'General Management', url: `/courses/management/general-management/102/`, id:'general_management', sideNavType: 'courses' },
            { name: 'Business Analyst', url: `/courses/management/business-analyst/58/`, id:'business_analyst', sideNavType: 'courses' },
            { name: 'Corporate Governance', url:`/courses/management/corporate-governance/59/`, id:'corporate_governance', sideNavType: 'courses'},
        ]
    },
    { 
        name: 'Mass Communication', 
        url: `${siteDomain}/courses/mass-communication/29/`, 
        id: 'mass_communication',
        sideNavType: 'allCourses',
        children: [
            { name: 'Content', url: `/courses/mass-communication/content/46/`, id:'content', sideNavType: 'courses' },
            { name: 'Public Relations', url: `/courses/mass-communication/public-relations/96/`, id:'public_relations', sideNavType: 'courses' },
            { name: 'Editor', url:`/courses/mass-communication/editor/106/`, id:'editor', sideNavType: 'courses'},
            { name: 'journalism', url:`/courses/mass-communication/journalism/99/`, id:'journalism', sideNavType: 'courses'}
        ]
    },
    { 
        name: 'Personal Development', 
        url: `${siteDomain}/courses/personal-development/21/`, 
        id: 'personal_development',
        sideNavType: 'allCourses',
        children: [
            { name: 'Language Learning', url: `/courses/personal-development/language-learning/40/`, id:'language_learning', sideNavType: 'courses' },
            { name: 'Leadership', url: `/courses/personal-development/leadership/41/`, id:'leadership', sideNavType: 'courses' },
            { name: 'Personal Development', url:`/courses/personal-development/personality-development/42/`, id:'personality_development', sideNavType: 'courses'},
            { name: 'Interview Preparation', url:`/courses/personal-development/interview-preparation/38/`, id:'interview_preparation', sideNavType: 'courses'},
            { name: 'Communication Development', url:`/courses/personal-development/communication-development/36/`,id:'communication_development', sideNavType: 'courses'}
        ]
    },
    { 
        name: 'Law', 
        url: `${siteDomain}/courses/law/23/`,
        id: 'law',
        sideNavType: 'allCourses',
        children: [
            { name: 'Cyber Law', url: `/courses/law/cyber-law/107/`, id:'cyber_law', sideNavType: 'courses' },
            { name: 'Criminal Law', url: `/courses/law/criminal-law/108/`, id:'criminal_law', sideNavType: 'courses' },
            { name: 'Company Law', url:`/courses/law/company-law/111/`, id:'company_law', sideNavType: 'courses'}
        ]
    },
    { 
        name: 'Course Catalogue', 
        url: `/online-courses.html`, 
        id: 'course_catalogue',
        sideNavType: 'allCourses',
        children: []
    },
]


const navSkillList = [
    { name : 'Digital Marketing', url: '/courses/sales-and-marketing/digital-marketing/32/', id:'digital_marketing' },
    { name: 'Six Sigma', url: '/courses/operation-management/six-sigma/193/', id:'six_sigma' },
    { name: 'Project Management', url: '/courses/operation-management/project-management/123/', id:'project_management'},
    { name: 'Big Data', url: '/courses/it-information-technology/big-data/84/', id:'big_data'},
    { name: 'IT Software', url: '/courses/it-information-technology/it-software/53/', id:'it_software' },
    { name: 'Data Science', url: '/courses/it-information-technology/data-science/497/', id:'data_science' },
    { name: 'Cloud Computing', url: '/courses/it-information-technology/cloud-computing/82/', id:'cloud_computing'}
]

const contactData = {
    'contactNo' : '08047105151',
    'contactEmail' : 'resume@shine.com',
    'contactTimings' : '9:00am to 6:30pm (Mon - Sat)',
}

const TrendingCategoryList = [
    { 
        name: 'Sales And Marketing', 
        url: `${siteDomain}/courses/sales-and-marketing/17/`,
    },
    {
        name: 'Information Technology', 
        url: `${siteDomain}/courses/it-information-technology/22/`, 
    },
    { 
        name: 'Banking & Finance', 
        url: `${siteDomain}/courses/banking-and-finance/20/`,
    },
]

const categoryTabs = [
    { name : 'All', id: '-1'},
    { name: 'Banking & Finance', id: '20'},
    { name: 'Sales & Marketing', id: '17'},
    { name: 'HR', id: '25'},
    { name: 'Operations', id: '19'},
    { name: 'Personal Development', id: '21'},
    { name: 'IT', id: '22'},
    { name: 'Mass comm', id: '29'},
    { name: 'Management', id: '27'},
    { name: 'Law', id: '23'}
]

const populartabType = [
    { visible: "Master's", slug: "master", id: '0'},
    { visible: "Certifications", slug: "certifications", id: '1'}
]


const IndianState = [
	"Achalpur",
  "Achhnera",
  "Adalaj",
  "Adilabad",
  "Adityapur",
  "Adoni",
  "Adoor",
  "Adra",
  "Adyar",
  "Afzalpur",
  "Agartala",
  "Agra",
  "Ahmedabad",
  "Ahmednagar",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Akot",
  "Alappuzha",
  "Aligarh",
  "AlipurdUrban Agglomerationr",
  "Alirajpur",
  "Allahabad",
  "Alwar",
  "Amalapuram",
  "Amalner",
  "Ambejogai",
  "Ambikapur",
  "Amravati",
  "Amreli",
  "Amritsar",
  "Amroha",
  "Anakapalle",
  "Anand",
  "Anantapur",
  "Anantnag",
  "Anjangaon",
  "Anjar",
  "Ankleshwar",
  "Arakkonam",
  "Arambagh",
  "Araria",
  "Arrah",
  "Arsikere",
  "Aruppukkottai",
  "Arvi",
  "Arwal",
  "Asansol",
  "Asarganj",
  "Ashok Nagar",
  "Athni",
  "Attingal",
  "Aurangabad",
  "Aurangabad",
  "Azamgarh",
  "Bagaha",
  "Bageshwar",
  "Bahadurgarh",
  "Baharampur",
  "Bahraich",
  "Balaghat",
  "Balangir",
  "Baleshwar Town",
  "Ballari",
  "Balurghat",
  "Bankura",
  "Bapatla",
  "Baramula",
  "Barbil",
  "Bargarh",
  "Barh",
  "Baripada Town",
  "Barmer",
  "Barnala",
  "Barpeta",
  "Batala",
  "Bathinda",
  "Begusarai",
  "Belagavi",
  "Bellampalle",
  "Belonia",
  "Bengaluru",
  "Bettiah",
  "BhabUrban Agglomeration",
  "Bhadrachalam",
  "Bhadrak",
  "Bhagalpur",
  "Bhainsa",
  "Bharatpur",
  "Bharuch",
  "Bhatapara",
  "Bhavnagar",
  "Bhawanipatna",
  "Bheemunipatnam",
  "Bhilai Nagar",
  "Bhilwara",
  "Bhimavaram",
  "Bhiwandi",
  "Bhiwani",
  "Bhongir",
  "Bhopal",
  "Bhubaneswar",
  "Bhuj",
  "Bikaner",
  "Bilaspur",
  "Bobbili",
  "Bodhan",
  "Bokaro Steel City",
  "Bongaigaon City",
  "Brahmapur",
  "Buxar",
  "Byasanagar",
  "Chaibasa",
  "Chalakudy",
  "Chandausi",
  "Chandigarh",
  "Changanassery",
  "Charkhi Dadri",
  "Chatra",
  "Chennai",
  "Cherthala",
  "Chhapra",
  "Chhapra",
  "Chikkamagaluru",
  "Chilakaluripet",
  "Chirala",
  "Chirkunda",
  "Chirmiri",
  "Chittoor",
  "Chittur-Thathamangalam",
  "Coimbatore",
  "Cuttack",
  "Dalli-Rajhara",
  "Darbhanga",
  "Darjiling",
  "Davanagere",
  "Deesa",
  "Dehradun",
  "Dehri-on-Sone",
  "Delhi",
  "Deoghar",
  "Dhamtari",
  "Dhanbad",
  "Dharmanagar",
  "Dharmavaram",
  "Dhenkanal",
  "Dhoraji",
  "Dhubri",
  "Dhule",
  "Dhuri",
  "Dibrugarh",
  "Dimapur",
  "Diphu",
  "Dumka",
  "Dumraon",
  "Durg",
  "Eluru",
  "English Bazar",
  "Erode",
  "Etawah",
  "Faridabad",
  "Faridkot",
  "Farooqnagar",
  "Fatehabad",
  "Fatehpur Sikri",
  "Fazilka",
  "Firozabad",
  "Firozpur Cantt.",
  "Firozpur",
  "Forbesganj",
  "Gadwal",
  "Gandhinagar",
  "Gangarampur",
  "Ganjbasoda",
  "Gaya",
  "Giridih",
  "Goalpara",
  "Gobichettipalayam",
  "Gobindgarh",
  "Godhra",
  "Gohana",
  "Gokak",
  "Gooty",
  "Gopalganj",
  "Gudivada",
  "Gudur",
  "Gumia",
  "Guntakal",
  "Guntur",
  "Gurdaspur",
  "Gurgaon",
  "Guruvayoor",
  "Guwahati",
  "Gwalior",
  "Habra",
  "Hajipur",
  "Haldwani-cum-Kathgodam",
  "Hansi",
  "Hapur",
  "Hardoi ",
  "Hardwar",
  "Hazaribag",
  "Hindupur",
  "Hisar",
  "Hoshiarpur",
  "Hubli-Dharwad",
  "Hugli-Chinsurah",
  "Hyderabad",
  "Ichalkaranji",
  "Imphal",
  "Indore",
  "Itarsi",
  "Jabalpur",
  "Jagdalpur",
  "Jaggaiahpet",
  "Jagraon",
  "Jagtial",
  "Jaipur",
  "Jalandhar Cantt.",
  "Jalandhar",
  "Jalpaiguri",
  "Jamalpur",
  "Jammalamadugu",
  "Jammu",
  "Jamnagar",
  "Jamshedpur",
  "Jamui",
  "Jangaon",
  "Jatani",
  "Jehanabad",
  "Jhansi",
  "Jhargram",
  "Jharsuguda",
  "Jhumri Tilaiya",
  "Jind",
  "Jodhpur",
  "Jorhat",
  "Kadapa",
  "Kadi",
  "Kadiri",
  "Kagaznagar",
  "Kailasahar",
  "Kaithal",
  "Kakinada",
  "Kalimpong",
  "Kalpi",
  "Kalyan-Dombivali",
  "Kamareddy",
  "Kancheepuram",
  "Kandukur",
  "Kanhangad",
  "Kannur",
  "Kanpur",
  "Kapadvanj",
  "Kapurthala",
  "Karaikal",
  "Karimganj",
  "Karimnagar",
  "Karjat",
  "Karnal",
  "Karur",
  "Karwar",
  "Kasaragod",
  "Kashipur",
  "KathUrban Agglomeration",
  "Katihar",
  "Kavali",
  "Kayamkulam",
  "Kendrapara",
  "Kendujhar",
  "Keshod",
  "Khair",
  "Khambhat",
  "Khammam",
  "Khanna",
  "Kharagpur",
  "Kharar",
  "Khowai",
  "Kishanganj",
  "Kochi",
  "Kodungallur",
  "Kohima",
  "Kolar",
  "Kolkata",
  "Kollam",
  "Koratla",
  "Korba",
  "Kot Kapura",
  "Kota",
  "Kothagudem",
  "Kottayam",
  "Kovvur",
  "Koyilandy",
  "Kozhikode",
  "Kunnamkulam",
  "Kurnool",
  "Kyathampalle",
  "Lachhmangarh",
  "Ladnu",
  "Ladwa",
  "Lahar",
  "Laharpur",
  "Lakheri",
  "Lakhimpur",
  "Lakhisarai",
  "Lakshmeshwar",
  "Lal Gopalganj Nindaura",
  "Lalganj",
  "Lalganj",
  "Lalgudi",
  "Lalitpur",
  "Lalsot",
  "Lanka",
  "Lar",
  "Lathi",
  "Latur",
  "Lilong",
  "Limbdi",
  "Lingsugur",
  "Loha",
  "Lohardaga",
  "Lonar",
  "Lonavla",
  "Longowal",
  "Loni",
  "Losal",
  "Lucknow",
  "Ludhiana",
  "Lumding",
  "Lunawada",
  "Lunglei",
  "Macherla",
  "Machilipatnam",
  "Madanapalle",
  "Maddur",
  "Madhepura",
  "Madhubani",
  "Madhugiri",
  "Madhupur",
  "Madikeri",
  "Madurai",
  "Magadi",
  "Mahad",
  "Mahalingapura",
  "Maharajganj",
  "Maharajpur",
  "Mahasamund",
  "Mahbubnagar",
  "Mahe",
  "Mahemdabad",
  "Mahendragarh",
  "Mahesana",
  "Mahidpur",
  "Mahnar Bazar",
  "Mahuva",
  "Maihar",
  "Mainaguri",
  "Makhdumpur",
  "Makrana",
  "Malaj Khand",
  "Malappuram",
  "Malavalli",
  "Malda",
  "Malegaon",
  "Malerkotla",
  "Malkangiri",
  "Malkapur",
  "Malout",
  "Malpura",
  "Malur",
  "Manachanallur",
  "Manasa",
  "Manavadar",
  "Manawar",
  "Mancherial",
  "Mandalgarh",
  "Mandamarri",
  "Mandapeta",
  "Mandawa",
  "Mandi Dabwali",
  "Mandi",
  "Mandideep",
  "Mandla",
  "Mandsaur",
  "Mandvi",
  "Mandya",
  "Manendragarh",
  "Maner",
  "Mangaldoi",
  "Mangaluru",
  "Mangalvedhe",
  "Manglaur",
  "Mangrol",
  "Mangrol",
  "Mangrulpir",
  "Manihari",
  "Manjlegaon",
  "Mankachar",
  "Manmad",
  "Mansa",
  "Mansa",
  "Manuguru",
  "Manvi",
  "Manwath",
  "Mapusa",
  "Margao",
  "Margherita",
  "Marhaura",
  "Mariani",
  "Marigaon",
  "Markapur",
  "Marmagao",
  "Masaurhi",
  "Mathabhanga",
  "Mathura",
  "Mattannur",
  "Mauganj",
  "Mavelikkara",
  "Mavoor",
  "Mayang Imphal",
  "Medak",
  "Medininagar (Daltonganj)",
  "Medinipur",
  "Meerut",
  "Mehkar",
  "Memari",
  "Merta City",
  "Mhaswad",
  "Mhow Cantonment",
  "Mhowgaon",
  "Mihijam",
  "Mira-Bhayandar",
  "Mirganj",
  "Miryalaguda",
  "Modasa",
  "Modinagar",
  "Moga",
  "Mohali",
  "Mokameh",
  "Mokokchung",
  "Monoharpur",
  "Moradabad",
  "Morena",
  "Morinda, India",
  "Morshi",
  "Morvi",
  "Motihari",
  "Motipur",
  "Mount Abu",
  "Mudabidri",
  "Mudalagi",
  "Muddebihal",
  "Mudhol",
  "Mukerian",
  "Mukhed",
  "Muktsar",
  "Mul",
  "Mulbagal",
  "Multai",
  "Mumbai",
  "Mundargi",
  "Mundi",
  "Mungeli",
  "Munger",
  "Murliganj",
  "Murshidabad",
  "Murtijapur",
  "Murwara (Katni)",
  "Musabani",
  "Mussoorie",
  "Muvattupuzha",
  "Muzaffarpur",
  "Mysore",
  "Nabadwip",
  "Nabarangapur",
  "Nabha",
  "Nadbai",
  "Nadiad",
  "Nagaon",
  "Nagapattinam",
  "Nagar",
  "Nagari",
  "Nagarkurnool",
  "Nagaur",
  "Nagda",
  "Nagercoil",
  "Nagina",
  "Nagla",
  "Nagpur",
  "Nahan",
  "Naharlagun",
  "Naidupet",
  "Naihati",
  "Naila Janjgir",
  "Nainital",
  "Nainpur",
  "Najibabad",
  "Nakodar",
  "Nakur",
  "Nalbari",
  "Namagiripettai",
  "Namakkal",
  "Nanded-Waghala",
  "Nandgaon",
  "Nandivaram-Guduvancheri",
  "Nandura",
  "Nandurbar",
  "Nandyal",
  "Nangal",
  "Nanjangud",
  "Nanjikottai",
  "Nanpara",
  "Narasapuram",
  "Narasaraopet",
  "Naraura",
  "Narayanpet",
  "Nargund",
  "Narkatiaganj",
  "Narkhed",
  "Narnaul",
  "Narsinghgarh",
  "Narsinghgarh",
  "Narsipatnam",
  "Narwana",
  "Nashik",
  "Nasirabad",
  "Natham",
  "Nathdwara",
  "Naugachhia",
  "Naugawan Sadat",
  "Nautanwa",
  "Navalgund",
  "Navsari",
  "Nawabganj",
  "Nawada",
  "Nawanshahr",
  "Nawapur",
  "Nedumangad",
  "Neem-Ka-Thana",
  "Neemuch",
  "Nehtaur",
  "Nelamangala",
  "Nellikuppam",
  "Nellore",
  "Nepanagar",
  "New Delhi",
  "Neyveli (TS)",
  "Neyyattinkara",
  "Nidadavole",
  "Nilambur",
  "Nilanga",
  "Nimbahera",
  "Nirmal",
  "Niwai",
  "Niwari",
  "Nizamabad",
  "Nohar",
  "Noida",
  "Nokha",
  "Nokha",
  "Nongstoin",
  "Noorpur",
  "North Lakhimpur",
  "Nowgong",
  "Nowrozabad (Khodargama)",
  "Nuzvid",
  "O' Valley",
  "Obra",
  "Oddanchatram",
  "Ongole",
  "Orai",
  "Osmanabad",
  "Ottappalam",
  "Ozar",
  "P.N.Patti",
  "Pachora",
  "Pachore",
  "Pacode",
  "Padmanabhapuram",
  "Padra",
  "Padrauna",
  "Paithan",
  "Pakaur",
  "Palacole",
  "Palai",
  "Palakkad",
  "Palampur",
  "Palani",
  "Palanpur",
  "Palasa Kasibugga",
  "Palghar",
  "Pali",
  "Pali",
  "Palia Kalan",
  "Palitana",
  "Palladam",
  "Pallapatti",
  "Pallikonda",
  "Palwal",
  "Palwancha",
  "Panagar",
  "Panagudi",
  "Panaji",
  "Panamattom",
  "Panchkula",
  "Panchla",
  "Pandharkaoda",
  "Pandharpur",
  "Pandhurna",
  "PandUrban Agglomeration",
  "Panipat",
  "Panna",
  "Panniyannur",
  "Panruti",
  "Panvel",
  "Pappinisseri",
  "Paradip",
  "Paramakudi",
  "Parangipettai",
  "Parasi",
  "Paravoor",
  "Parbhani",
  "Pardi",
  "Parlakhemundi",
  "Parli",
  "Partur",
  "Parvathipuram",
  "Pasan",
  "Paschim Punropara",
  "Pasighat",
  "Patan",
  "Pathanamthitta",
  "Pathankot",
  "Pathardi",
  "Pathri",
  "Patiala",
  "Patna",
  "Patratu",
  "Pattamundai",
  "Patti",
  "Pattran",
  "Pattukkottai",
  "Patur",
  "Pauni",
  "Pauri",
  "Pavagada",
  "Pedana",
  "Peddapuram",
  "Pehowa",
  "Pen",
  "Perambalur",
  "Peravurani",
  "Peringathur",
  "Perinthalmanna",
  "Periyakulam",
  "Periyasemur",
  "Pernampattu",
  "Perumbavoor",
  "Petlad",
  "Phagwara",
  "Phalodi",
  "Phaltan",
  "Phillaur",
  "Phulabani",
  "Phulera",
  "Phulpur",
  "Phusro",
  "Pihani",
  "Pilani",
  "Pilibanga",
  "Pilibhit",
  "Pilkhuwa",
  "Pindwara",
  "Pinjore",
  "Pipar City",
  "Pipariya",
  "Piriyapatna",
  "Piro",
  "Pithampur",
  "Pithapuram",
  "Pithoragarh",
  "Pollachi",
  "Polur",
  "Pondicherry",
  "Ponnani",
  "Ponneri",
  "Ponnur",
  "Porbandar",
  "Porsa",
  "Port Blair",
  "Powayan",
  "Prantij",
  "Pratapgarh",
  "Pratapgarh",
  "Prithvipur",
  "Proddatur",
  "Pudukkottai",
  "Pudupattinam",
  "Pukhrayan",
  "Pulgaon",
  "Puliyankudi",
  "Punalur",
  "Punch",
  "Pune",
  "Punganur",
  "Punjaipugalur",
  "Puranpur",
  "Puri",
  "Purna",
  "Purnia",
  "PurqUrban Agglomerationzi",
  "Purulia",
  "Purwa",
  "Pusad",
  "Puthuppally",
  "Puttur",
  "Puttur",
  "Qadian",
  "Raayachuru",
  "Rabkavi Banhatti",
  "Radhanpur",
  "Rae Bareli",
  "Rafiganj",
  "Raghogarh-Vijaypur",
  "Raghunathganj",
  "Raghunathpur",
  "Rahatgarh",
  "Rahuri",
  "Raiganj",
  "Raigarh",
  "Raikot",
  "Raipur",
  "Rairangpur",
  "Raisen",
  "Raisinghnagar",
  "Rajagangapur",
  "Rajahmundry",
  "Rajakhera",
  "Rajaldesar",
  "Rajam",
  "Rajampet",
  "Rajapalayam",
  "Rajauri",
  "Rajgarh (Alwar)",
  "Rajgarh (Churu)",
  "Rajgarh",
  "Rajgir",
  "Rajkot",
  "Rajnandgaon",
  "Rajpipla",
  "Rajpura",
  "Rajsamand",
  "Rajula",
  "Rajura",
  "Ramachandrapuram",
  "Ramagundam",
  "Ramanagaram",
  "Ramanathapuram",
  "Ramdurg",
  "Rameshwaram",
  "Ramganj Mandi",
  "Ramgarh",
  "Ramnagar",
  "Ramnagar",
  "Ramngarh",
  "Rampur Maniharan",
  "Rampur",
  "Rampura Phul",
  "Rampurhat",
  "Ramtek",
  "Ranaghat",
  "Ranavav",
  "Ranchi",
  "Ranebennuru",
  "Rangia",
  "Rania",
  "Ranibennur",
  "Ranipet",
  "Rapar",
  "Rasipuram",
  "Rasra",
  "Ratangarh",
  "Rath",
  "Ratia",
  "Ratlam",
  "Ratnagiri",
  "Rau",
  "Raurkela",
  "Raver",
  "Rawatbhata",
  "Rawatsar",
  "Raxaul Bazar",
  "Rayachoti",
  "Rayadurg",
  "Rayagada",
  "Reengus",
  "Rehli",
  "Renigunta",
  "Renukoot",
  "Reoti",
  "Repalle",
  "Revelganj",
  "Rewa",
  "Rewari",
  "Rishikesh",
  "Risod",
  "Robertsganj",
  "Robertson Pet",
  "Rohtak",
  "Ron",
  "Roorkee",
  "Rosera",
  "Rudauli",
  "Rudrapur",
  "Rudrapur",
  "Rupnagar",
  "Sabalgarh",
  "Sadabad",
  "Sadalagi",
  "Sadasivpet",
  "Sadri",
  "Sadulpur",
  "Sadulshahar",
  "Safidon",
  "Safipur",
  "Sagar",
  "Sagara",
  "Sagwara",
  "Saharanpur",
  "Saharsa",
  "Sahaspur",
  "Sahaswan",
  "Sahawar",
  "Sahibganj",
  "Sahjanwa",
  "Saidpur",
  "Saiha",
  "Sailu",
  "Sainthia",
  "Sakaleshapura",
  "Sakti",
  "Salaya",
  "Salem",
  "Salur",
  "Samalkha",
  "Samalkot",
  "Samana",
  "Samastipur",
  "Sambalpur",
  "Sambhal",
  "Sambhar",
  "Samdhan",
  "Samthar",
  "Sanand",
  "Sanawad",
  "Sanchore",
  "Sandi",
  "Sandila",
  "Sanduru",
  "Sangamner",
  "Sangareddy",
  "Sangaria",
  "Sangli",
  "Sangole",
  "Sangrur",
  "Sankarankovil",
  "Sankari",
  "Sankeshwara",
  "Santipur",
  "Sarangpur",
  "Sardarshahar",
  "Sardhana",
  "Sarni",
  "Sarsod",
  "Sasaram",
  "Sasvad",
  "Satana",
  "Satara",
  "Sathyamangalam",
  "Satna",
  "Sattenapalle",
  "Sattur",
  "Saunda",
  "Saundatti-Yellamma",
  "Sausar",
  "Savanur",
  "Savarkundla",
  "Savner",
  "Sawai Madhopur",
  "Sawantwadi",
  "Sedam",
  "Sehore",
  "Sendhwa",
  "Seohara",
  "Seoni",
  "Seoni-Malwa",
  "Shahabad",
  "Shahabad, Hardoi",
  "Shahabad, Rampur",
  "Shahade",
  "Shahbad",
  "Shahdol",
  "Shahganj",
  "Shahjahanpur",
  "Shahpur",
  "Shahpura",
  "Shahpura",
  "Shajapur",
  "Shamgarh",
  "Shamli",
  "Shamsabad, Agra",
  "Shamsabad, Farrukhabad",
  "Shegaon",
  "Sheikhpura",
  "Shendurjana",
  "Shenkottai",
  "Sheoganj",
  "Sheohar",
  "Sheopur",
  "Sherghati",
  "Sherkot",
  "Shiggaon",
  "Shikaripur",
  "Shikarpur, Bulandshahr",
  "Shikohabad",
  "Shillong",
  "Shimla",
  "Shirdi",
  "Shirpur-Warwade",
  "Shirur",
  "Shishgarh",
  "Shivamogga",
  "Shivpuri",
  "Sholavandan",
  "Sholingur",
  "Shoranur",
  "Shrigonda",
  "Shrirampur",
  "Shrirangapattana",
  "Shujalpur",
  "Siana",
  "Sibsagar",
  "Siddipet",
  "Sidhi",
  "Sidhpur",
  "Sidlaghatta",
  "Sihor",
  "Sihora",
  "Sikanderpur",
  "Sikandra Rao",
  "Sikandrabad",
  "Sikar",
  "Silao",
  "Silapathar",
  "Silchar",
  "Siliguri",
  "Sillod",
  "Silvassa",
  "Simdega",
  "Sindagi",
  "Sindhagi",
  "Sindhnur",
  "Singrauli",
  "Sinnar",
  "Sira",
  "Sircilla",
  "Sirhind Fatehgarh Sahib",
  "Sirkali",
  "Sirohi",
  "Sironj",
  "Sirsa",
  "Sirsaganj",
  "Sirsi",
  "Sirsi",
  "Siruguppa",
  "Sitamarhi",
  "Sitapur",
  "Sitarganj",
  "Sivaganga",
  "Sivagiri",
  "Sivakasi",
  "Siwan",
  "Sohagpur",
  "Sohna",
  "Sojat",
  "Solan",
  "Solapur",
  "Sonamukhi",
  "Sonepur",
  "Songadh",
  "Sonipat",
  "Sopore",
  "Soro",
  "Soron",
  "Soyagaon",
  "Sri Madhopur",
  "Srikakulam",
  "Srikalahasti",
  "Srinagar",
  "Srinagar",
  "Srinivaspur",
  "Srirampore",
  "Srisailam Project (Right Flank Colony) Township",
  "Srivilliputhur",
  "Sugauli",
  "Sujangarh",
  "Sujanpur",
  "Sullurpeta",
  "Sultanganj",
  "Sultanpur",
  "Sumerpur",
  "Sumerpur",
  "Sunabeda",
  "Sunam",
  "Sundargarh",
  "Sundarnagar",
  "Supaul",
  "Surandai",
  "Surapura",
  "Surat",
  "Suratgarh",
  "SUrban Agglomerationr",
  "Suri",
  "Suriyampalayam",
  "Suryapet",
  "Tadepalligudem",
  "Tadpatri",
  "Takhatgarh",
  "Taki",
  "Talaja",
  "Talcher",
  "Talegaon Dabhade",
  "Talikota",
  "Taliparamba",
  "Talode",
  "Talwara",
  "Tamluk",
  "Tanda",
  "Tandur",
  "Tanuku",
  "Tarakeswar",
  "Tarana",
  "Taranagar",
  "Taraori",
  "Tarbha",
  "Tarikere",
  "Tarn Taran",
  "Tasgaon",
  "Tehri",
  "Tekkalakote",
  "Tenali",
  "Tenkasi",
  "Tenu dam-cum-Kathhara",
  "Terdal",
  "Tezpur",
  "Thakurdwara",
  "Thammampatti",
  "Thana Bhawan",
  "Thane",
  "Thanesar",
  "Thangadh",
  "Thanjavur",
  "Tharad",
  "Tharamangalam",
  "Tharangambadi",
  "Theni Allinagaram",
  "Thirumangalam",
  "Thirupuvanam",
  "Thiruthuraipoondi",
  "Thiruvalla",
  "Thiruvallur",
  "Thiruvananthapuram",
  "Thiruvarur",
  "Thodupuzha",
  "Thoubal",
  "Thrissur",
  "Thuraiyur",
  "Tikamgarh",
  "Tilda Newra",
  "Tilhar",
  "Tindivanam",
  "Tinsukia",
  "Tiptur",
  "Tirora",
  "Tiruchendur",
  "Tiruchengode",
  "Tiruchirappalli",
  "Tirukalukundram",
  "Tirukkoyilur",
  "Tirunelveli",
  "Tirupathur",
  "Tirupathur",
  "Tirupati",
  "Tiruppur",
  "Tirur",
  "Tiruttani",
  "Tiruvannamalai",
  "Tiruvethipuram",
  "Tiruvuru",
  "Tirwaganj",
  "Titlagarh",
  "Tittakudi",
  "Todabhim",
  "Todaraisingh",
  "Tohana",
  "Tonk",
  "Tuensang",
  "Tuljapur",
  "Tulsipur",
  "Tumkur",
  "Tumsar",
  "Tundla",
  "Tuni",
  "Tura",
  "Uchgaon",
  "Udaipur",
  "Udaipur",
  "Udaipurwati",
  "Udgir",
  "Udhagamandalam",
  "Udhampur",
  "Udumalaipettai",
  "Udupi",
  "Ujhani",
  "Ujjain",
  "Umarga",
  "Umaria",
  "Umarkhed",
  "Umbergaon",
  "Umred",
  "Umreth",
  "Una",
  "Unjha",
  "Unnamalaikadai",
  "Unnao",
  "Upleta",
  "Uran Islampur",
  "Uran",
  "Uravakonda",
  "Urmar Tanda",
  "Usilampatti",
  "Uthamapalayam",
  "Uthiramerur",
  "Utraula",
  "Vadakkuvalliyur",
  "Vadalur",
  "Vadgaon Kasba",
  "Vadipatti",
  "Vadnagar",
  "Vadodara",
  "Vaijapur",
  "Vaikom",
  "Valparai",
  "Valsad",
  "Vandavasi",
  "Vaniyambadi",
  "Vapi",
  "Vapi",
  "Varanasi",
  "Varkala",
  "Vasai-Virar",
  "Vatakara",
  "Vedaranyam",
  "Vellakoil",
  "Vellore",
  "Venkatagiri",
  "Veraval",
  "Vidisha",
  "Vijainagar, Ajmer",
  "Vijapur",
  "Vijayapura",
  "Vijayawada",
  "Vijaypur",
  "Vikarabad",
  "Vikramasingapuram",
  "Viluppuram",
  "Vinukonda",
  "Viramgam",
  "Virudhachalam",
  "Virudhunagar",
  "Visakhapatnam",
  "Visnagar",
  "Viswanatham",
  "Vita",
  "Vizianagaram",
  "Vrindavan",
  "Vyara",
  "Wadgaon Road",
  "Wadhwan",
  "Wadi",
  "Wai",
  "Wanaparthy",
  "Wani",
  "Wankaner",
  "Wara Seoni",
  "Warangal",
  "Wardha",
  "Warhapur",
  "Warisaliganj",
  "Warora",
  "Warud",
  "Washim",
  "Wokha",
  "Yadgir",
  "Yamunanagar",
  "Yanam",
  "Yavatmal",
  "Yawal",
  "Yellandu",
  "Yemmiganur",
  "Yerraguntla",
  "Yevla",
  "Zaidpur",
  "Zamania",
  "Zira",
  "Zirakpur",
  "Zunheboto",
]

export {
    freeResourcesList,
    jobAssistanceList,
    categoryList,
    navSkillList,
    contactData,
    TrendingCategoryList,
    categoryTabs,
    populartabType,
    IndianState
}