#python imports

#django imports

#local imports

#inter app imports

#third party imports

EDUCATION_PARENT_CHILD_HEIRARCHY_LIST = [{'child': [{'cdesc': 'Arts and Humanities', 'cid': 501},
                   {'cdesc': 'Commerce', 'cid': 502},
                   {'cdesc': 'Science', 'cid': 507},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': '10+2 or Below',
         'pid': 101},
        {'child': [{'cdesc': 'Arts and Humanities', 'cid': 501},
                   {'cdesc': 'English', 'cid': 510},
                   {'cdesc': 'Hindi', 'cid': 514},
                   {'cdesc': 'Maths', 'cid': 517},
                   {'cdesc': 'Economics', 'cid': 509},
                   {'cdesc': 'History', 'cid': 515},
                   {'cdesc': 'Political Science', 'cid': 519},
                   {'cdesc': 'Communication', 'cid': 508},
                   {'cdesc': 'Fine Arts', 'cid': 511},
                   {'cdesc': 'Geography', 'cid': 512},
                   {'cdesc': 'Graphics / Web designing', 'cid': 578},
                   {'cdesc': 'Journalism / Mass Communication', 'cid': 595},
                   {'cdesc': 'Philosophy', 'cid': 518},
                   {'cdesc': 'PR/Advertising', 'cid': 520},
                   {'cdesc': 'Psychology', 'cid': 521},
                   {'cdesc': 'Sanskrit', 'cid': 522},
                   {'cdesc': 'Sociology', 'cid': 523},
                   {'cdesc': 'Visual Arts', 'cid': 524},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'B.A',
         'pid': 102},
        {'child': [{'cdesc': 'Architecture', 'cid': 525}],
         'pdesc': 'B.Arch',
         'pid': 103},
        {'child': [{'cdesc': 'Marketing', 'cid': 527},
                   {'cdesc': 'Finance / Accounting', 'cid': 526},
                   {'cdesc': 'Management', 'cid': 505},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'B.B.A / B.M.S',
         'pid': 104},
        {'child': [{'cdesc': 'Computers', 'cid': 503}], 'pdesc': 'B.C.A', 'pid': 105},
        {'child': [{'cdesc': 'Commerce', 'cid': 502}], 'pdesc': 'B.Com', 'pid': 106},
        {'child': [{'cdesc': 'Education', 'cid': 528}], 'pdesc': 'B.Ed', 'pid': 107},
        {'child': [{'cdesc': 'Pharmacy', 'cid': 529}],
         'pdesc': 'B.Pharma',
         'pid': 108},
        {'child': [{'cdesc': 'Chemistry', 'cid': 536},
                   {'cdesc': 'Biology', 'cid': 533},
                   {'cdesc': 'Physics', 'cid': 542},
                   {'cdesc': 'Electronics/Telecommunication', 'cid': 551},
                   {'cdesc': 'Microbiology', 'cid': 541},
                   {'cdesc': 'Zoology', 'cid': 544},
                   {'cdesc': 'Agriculture', 'cid': 530},
                   {'cdesc': 'Anthropology', 'cid': 531},
                   {'cdesc': 'Biochemistry', 'cid': 532},
                   {'cdesc': 'Biomedical', 'cid': 534},
                   {'cdesc': 'Botany', 'cid': 535},
                   {'cdesc': 'Computers', 'cid': 503},
                   {'cdesc': 'Food Technology', 'cid': 538},
                   {'cdesc': 'Geology', 'cid': 539},
                   {'cdesc': 'Home Science', 'cid': 540},
                   {'cdesc': 'Maths', 'cid': 517},
                   {'cdesc': 'Statistics', 'cid': 543},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'B.Sc',
         'pid': 109},
        {'child': [{'cdesc': 'Computers', 'cid': 503},
                   {'cdesc': 'IT-Software', 'cid': 555},
                   {'cdesc': 'Mechanical', 'cid': 557},
                   {'cdesc': 'Electronics/Telecommunication', 'cid': 551},
                   {'cdesc': 'Electrical', 'cid': 550},
                   {'cdesc': 'Civil', 'cid': 549},
                   {'cdesc': 'Aeronautics', 'cid': 545},
                   {'cdesc': 'Agriculture', 'cid': 530},
                   {'cdesc': 'Architecture', 'cid': 525},
                   {'cdesc': 'Automobile', 'cid': 546},
                   {'cdesc': 'Biochemistry', 'cid': 532},
                   {'cdesc': 'Biomedical', 'cid': 534},
                   {'cdesc': 'Biotechnology', 'cid': 547},
                   {'cdesc': 'Chemical', 'cid': 548},
                   {'cdesc': 'Energy', 'cid': 552},
                   {'cdesc': 'Environmental', 'cid': 553},
                   {'cdesc': 'Instrumentation', 'cid': 554},
                   {'cdesc': 'Marine', 'cid': 556},
                   {'cdesc': 'Metallurgy', 'cid': 558},
                   {'cdesc': 'Mineral', 'cid': 559},
                   {'cdesc': 'Mining', 'cid': 560},
                   {'cdesc': 'Nuclear', 'cid': 561},
                   {'cdesc': 'Production/Industrial', 'cid': 563},
                   {'cdesc': 'Textile', 'cid': 564},
                   {'cdesc': 'Other Engineering', 'cid': 562}],
         'pdesc': 'B.Tech/B.E',
         'pid': 110},
        {'child': [{'cdesc': 'Dentistry', 'cid': 565}], 'pdesc': 'BDS', 'pid': 111},
        {'child': [{'cdesc': 'Hotel Management', 'cid': 566}],
         'pdesc': 'BHM',
         'pid': 112},
        {'child': [{'cdesc': 'Veterinary Science', 'cid': 567}],
         'pdesc': 'BVSC',
         'pid': 113},
        {'child': [{'cdesc': 'Chartered Accountant', 'cid': 568}],
         'pdesc': 'C.A',
         'pid': 114},
        {'child': [{'cdesc': 'Chartered Financial Analyst', 'cid': 569}],
         'pdesc': 'C.F.A',
         'pid': 115},
        {'child': [{'cdesc': 'Company Secretary', 'cid': 570}],
         'pdesc': 'C.S',
         'pid': 116},
        {'child': [{'cdesc': 'Arts and Humanities', 'cid': 501},
                   {'cdesc': 'Vocational Course', 'cid': 593},
                   {'cdesc': 'Anaesthesiology', 'cid': 571},
                   {'cdesc': 'Cardiology', 'cid': 572},
                   {'cdesc': 'Chemical', 'cid': 548},
                   {'cdesc': 'Civil', 'cid': 549},
                   {'cdesc': 'Commerce', 'cid': 502},
                   {'cdesc': 'Computers', 'cid': 503},
                   {'cdesc': 'Dentistry', 'cid': 565},
                   {'cdesc': 'Dermatology,Venereology & Leprosy', 'cid': 606},
                   {'cdesc': 'Electrical', 'cid': 550},
                   {'cdesc': 'Electronics/Telecommunication', 'cid': 551},
                   {'cdesc': 'Fashion Designing', 'cid': 575},
                   {'cdesc': 'Finance / Accounting', 'cid': 526},
                   {'cdesc': 'General Surgery', 'cid': 577},
                   {'cdesc': 'Graphics / Web designing', 'cid': 578},
                   {'cdesc': 'Hotel Management', 'cid': 566},
                   {'cdesc': 'Insurance', 'cid': 579},
                   {'cdesc': 'Management', 'cid': 505},
                   {'cdesc': 'Marketing', 'cid': 527},
                   {'cdesc': 'Maths', 'cid': 517},
                   {'cdesc': 'Mechanical', 'cid': 557},
                   {'cdesc': 'Neurology', 'cid': 580},
                   {'cdesc': 'Nursing', 'cid': 581},
                   {'cdesc': 'Nutrition & Dietetics', 'cid': 582},
                   {'cdesc': 'Obstetrics & Gynaecology', 'cid': 583},
                   {'cdesc': 'Ophthalmology', 'cid': 584},
                   {'cdesc': 'Orthopaedics', 'cid': 585},
                   {'cdesc': 'Pediatrics', 'cid': 613},
                   {'cdesc': 'Pathology', 'cid': 588},
                   {'cdesc': 'Pharmacy', 'cid': 529},
                   {'cdesc': 'Physiotherapy', 'cid': 589},
                   {'cdesc': 'Psychiatry', 'cid': 590},
                   {'cdesc': 'Radiology', 'cid': 591},
                   {'cdesc': 'Science', 'cid': 507},
                   {'cdesc': 'Tourism', 'cid': 592},
                   {'cdesc': 'Visual Arts', 'cid': 524},
                   {'cdesc': 'Other Engineering', 'cid': 562},
                   {'cdesc': 'Other Medicine', 'cid': 586},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'Diploma',
         'pid': 117},
        {'child': [{'cdesc': 'Cost Accountant', 'cid': 594}],
         'pdesc': 'ICWA / CMA',
         'pid': 118},
        {'child': [{'cdesc': 'Management', 'cid': 505},
                   {'cdesc': 'Journalism / Mass Communication', 'cid': 595},
                   {'cdesc': 'PR/Advertising', 'cid': 520},
                   {'cdesc': 'Tourism', 'cid': 592},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'Integrated PG',
         'pid': 119},
        {'child': [{'cdesc': 'Law', 'cid': 596}], 'pdesc': 'LL.M', 'pid': 120},
        {'child': [{'cdesc': 'Law', 'cid': 596}], 'pdesc': 'LLB', 'pid': 121},
        {'child': [{'cdesc': 'Arts and Humanities', 'cid': 501},
                   {'cdesc': 'English', 'cid': 510},
                   {'cdesc': 'Hindi', 'cid': 514},
                   {'cdesc': 'Maths', 'cid': 517},
                   {'cdesc': 'Economics', 'cid': 509},
                   {'cdesc': 'History', 'cid': 515},
                   {'cdesc': 'Political Science', 'cid': 519},
                   {'cdesc': 'Communication', 'cid': 508},
                   {'cdesc': 'Fine Arts', 'cid': 511},
                   {'cdesc': 'Geography', 'cid': 512},
                   {'cdesc': 'Graphics / Web designing', 'cid': 578},
                   {'cdesc': 'Journalism / Mass Communication', 'cid': 595},
                   {'cdesc': 'Philosophy', 'cid': 518},
                   {'cdesc': 'PR/Advertising', 'cid': 520},
                   {'cdesc': 'Psychology', 'cid': 521},
                   {'cdesc': 'Sanskrit', 'cid': 522},
                   {'cdesc': 'Sociology', 'cid': 523},
                   {'cdesc': 'Visual Arts', 'cid': 524},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'M.A',
         'pid': 122},
        {'child': [{'cdesc': 'Computers', 'cid': 503}], 'pdesc': 'M.C.A', 'pid': 123},
        {'child': [{'cdesc': 'Commerce', 'cid': 502}], 'pdesc': 'M.Com', 'pid': 124},
        {'child': [{'cdesc': 'Education', 'cid': 528}], 'pdesc': 'M.Ed', 'pid': 125},
        {'child': [{'cdesc': 'Pharmacy', 'cid': 529}],
         'pdesc': 'M.Pharma',
         'pid': 126},
        {'child': [{'cdesc': 'Chemistry', 'cid': 536},
                   {'cdesc': 'Biology', 'cid': 533},
                   {'cdesc': 'Physics', 'cid': 542},
                   {'cdesc': 'Electronics/Telecommunication', 'cid': 551},
                   {'cdesc': 'Microbiology', 'cid': 541},
                   {'cdesc': 'Zoology', 'cid': 544},
                   {'cdesc': 'Agriculture', 'cid': 530},
                   {'cdesc': 'Anthropology', 'cid': 531},
                   {'cdesc': 'Biochemistry', 'cid': 532},
                   {'cdesc': 'Biomedical', 'cid': 534},
                   {'cdesc': 'Botany', 'cid': 535},
                   {'cdesc': 'Computers', 'cid': 503},
                   {'cdesc': 'Food Technology', 'cid': 538},
                   {'cdesc': 'Geology', 'cid': 539},
                   {'cdesc': 'Home Science', 'cid': 540},
                   {'cdesc': 'Maths', 'cid': 517},
                   {'cdesc': 'Statistics', 'cid': 543},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'M.Sc',
         'pid': 127},
        {'child': [{'cdesc': 'Computers', 'cid': 503},
                   {'cdesc': 'IT-Software', 'cid': 555},
                   {'cdesc': 'Mechanical', 'cid': 557},
                   {'cdesc': 'Electronics/Telecommunication', 'cid': 551},
                   {'cdesc': 'Electrical', 'cid': 550},
                   {'cdesc': 'Civil', 'cid': 549},
                   {'cdesc': 'Aeronautics', 'cid': 545},
                   {'cdesc': 'Agriculture', 'cid': 530},
                   {'cdesc': 'Architecture', 'cid': 525},
                   {'cdesc': 'Automobile', 'cid': 546},
                   {'cdesc': 'Aviation', 'cid': 597},
                   {'cdesc': 'Biochemistry', 'cid': 532},
                   {'cdesc': 'Biomedical', 'cid': 534},
                   {'cdesc': 'Biotechnology', 'cid': 547},
                   {'cdesc': 'Chemical', 'cid': 548},
                   {'cdesc': 'Energy', 'cid': 552},
                   {'cdesc': 'Environmental', 'cid': 553},
                   {'cdesc': 'Instrumentation', 'cid': 554},
                   {'cdesc': 'Marine', 'cid': 556},
                   {'cdesc': 'Metallurgy', 'cid': 558},
                   {'cdesc': 'Mineral', 'cid': 559},
                   {'cdesc': 'Mining', 'cid': 560},
                   {'cdesc': 'Nuclear', 'cid': 561},
                   {'cdesc': 'Production/Industrial', 'cid': 563},
                   {'cdesc': 'Textile', 'cid': 564},
                   {'cdesc': 'Other Engineering', 'cid': 562}],
         'pdesc': 'M.Tech',
         'pid': 128},
        {'child': [{'cdesc': 'Marketing', 'cid': 527},
                   {'cdesc': 'Finance / Accounting', 'cid': 526},
                   {'cdesc': 'HR/ Industrial Relations', 'cid': 599},
                   {'cdesc': 'Operations', 'cid': 602},
                   {'cdesc': 'Advertising/Mass Communication', 'cid': 598},
                   {'cdesc': 'Information Technology', 'cid': 600},
                   {'cdesc': 'International Business', 'cid': 601},
                   {'cdesc': 'Other Management', 'cid': 603}],
         'pdesc': 'MBA/PGDM',
         'pid': 129},
        {'child': [{'cdesc': 'Medicine and Health Sciences', 'cid': 621}],
         'pdesc': 'MBBS',
         'pid': 130},
        {'child': [{'cdesc': 'General Medicine', 'cid': 609},
                   {'cdesc': 'Pathology', 'cid': 588},
                   {'cdesc': 'Radiology', 'cid': 591},
                   {'cdesc': 'General Surgery', 'cid': 577},
                   {'cdesc': 'Obstetrics & Gynaecology', 'cid': 583},
                   {'cdesc': 'Cardiology', 'cid': 572},
                   {'cdesc': 'Anaesthesiology', 'cid': 571},
                   {'cdesc': 'Anatomy', 'cid': 605},
                   {'cdesc': 'Biochemistry', 'cid': 532},
                   {'cdesc': 'Dermatology,Venereology & Leprosy', 'cid': 606},
                   {'cdesc': 'ENT', 'cid': 607},
                   {'cdesc': 'Forensic Medicine', 'cid': 608},
                   {'cdesc': 'Hospital Administration', 'cid': 610},
                   {'cdesc': 'Lab Medicine', 'cid': 611},
                   {'cdesc': 'Microbiology', 'cid': 541},
                   {'cdesc': 'Neurology', 'cid': 580},
                   {'cdesc': 'Ophthalmology', 'cid': 584},
                   {'cdesc': 'Orthopaedics', 'cid': 585},
                   {'cdesc': 'Pediatrics', 'cid': 613},
                   {'cdesc': 'Pharmacy', 'cid': 529},
                   {'cdesc': 'Physiology', 'cid': 615},
                   {'cdesc': 'Psychiatry', 'cid': 590},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'MD/MS',
         'pid': 131},
        {'child': [{'cdesc': 'Dentistry', 'cid': 565}], 'pdesc': 'MDS', 'pid': 132},
        {'child': [{'cdesc': 'Hotel Management', 'cid': 566}],
         'pdesc': 'MMH',
         'pid': 133},
        {'child': [{'cdesc': 'Philosophy', 'cid': 518}],
         'pdesc': 'MPHIL',
         'pid': 134},
        {'child': [{'cdesc': 'Veterinary Science', 'cid': 567}],
         'pdesc': 'MVSC',
         'pid': 135},
        {'child': [{'cdesc': 'Other', 'cid': 506}], 'pdesc': 'Other', 'pid': 136},
        {'child': [{'cdesc': 'Arts and Humanities', 'cid': 501},
                   {'cdesc': 'Vocational Course', 'cid': 593},
                   {'cdesc': 'Anaesthesiology', 'cid': 571},
                   {'cdesc': 'Cardiology', 'cid': 572},
                   {'cdesc': 'Chemical', 'cid': 548},
                   {'cdesc': 'Civil', 'cid': 549},
                   {'cdesc': 'Commerce', 'cid': 502},
                   {'cdesc': 'Computers', 'cid': 503},
                   {'cdesc': 'Dermatology,Venereology & Leprosy', 'cid': 606},
                   {'cdesc': 'Electrical', 'cid': 550},
                   {'cdesc': 'Electronics/Telecommunication', 'cid': 551},
                   {'cdesc': 'Fashion Designing', 'cid': 575},
                   {'cdesc': 'Finance / Accounting', 'cid': 526},
                   {'cdesc': 'General Surgery', 'cid': 577},
                   {'cdesc': 'Graphics / Web designing', 'cid': 578},
                   {'cdesc': 'Hotel Management', 'cid': 566},
                   {'cdesc': 'Insurance', 'cid': 579},
                   {'cdesc': 'Management', 'cid': 505},
                   {'cdesc': 'Marketing', 'cid': 527},
                   {'cdesc': 'Maths', 'cid': 517},
                   {'cdesc': 'Mechanical', 'cid': 557},
                   {'cdesc': 'Neurology', 'cid': 580},
                   {'cdesc': 'Nursing', 'cid': 581},
                   {'cdesc': 'Nutrition & Dietetics', 'cid': 582},
                   {'cdesc': 'Obstetrics & Gynaecology', 'cid': 583},
                   {'cdesc': 'Ophthalmology', 'cid': 584},
                   {'cdesc': 'Orthopaedics', 'cid': 585},
                   {'cdesc': 'Pediatrics', 'cid': 613},
                   {'cdesc': 'Pathology', 'cid': 588},
                   {'cdesc': 'Physiotherapy', 'cid': 589},
                   {'cdesc': 'Psychiatry', 'cid': 590},
                   {'cdesc': 'Radiology', 'cid': 591},
                   {'cdesc': 'Science', 'cid': 507},
                   {'cdesc': 'Tourism', 'cid': 592},
                   {'cdesc': 'Visual Arts', 'cid': 524},
                   {'cdesc': 'Other Medicine', 'cid': 586},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'PG Diploma',
         'pid': 137},
        {'child': [{'cdesc': 'Advertising/Mass Communication', 'cid': 598},
                   {'cdesc': 'Agriculture', 'cid': 530},
                   {'cdesc': 'Architecture', 'cid': 525},
                   {'cdesc': 'Arts and Humanities', 'cid': 501},
                   {'cdesc': 'Automobile', 'cid': 546},
                   {'cdesc': 'Aviation', 'cid': 597},
                   {'cdesc': 'Biochemistry', 'cid': 532},
                   {'cdesc': 'Biotechnology', 'cid': 547},
                   {'cdesc': 'Biology', 'cid': 533},
                   {'cdesc': 'Biomedical', 'cid': 534},
                   {'cdesc': 'Ceramics', 'cid': 618},
                   {'cdesc': 'Chemical', 'cid': 548},
                   {'cdesc': 'Chemistry', 'cid': 536},
                   {'cdesc': 'Civil', 'cid': 549},
                   {'cdesc': 'Commerce', 'cid': 502},
                   {'cdesc': 'Communication', 'cid': 508},
                   {'cdesc': 'Computers', 'cid': 503},
                   {'cdesc': 'Dermatology,Venereology & Leprosy', 'cid': 606},
                   {'cdesc': 'Economics', 'cid': 509},
                   {'cdesc': 'Electrical', 'cid': 550},
                   {'cdesc': 'Energy', 'cid': 552},
                   {'cdesc': 'Environmental', 'cid': 553},
                   {'cdesc': 'Fashion Designing', 'cid': 575},
                   {'cdesc': 'Finance / Accounting', 'cid': 526},
                   {'cdesc': 'Fine Arts', 'cid': 511},
                   {'cdesc': 'Food Technology', 'cid': 538},
                   {'cdesc': 'History', 'cid': 515},
                   {'cdesc': 'Hotel Management', 'cid': 566},
                   {'cdesc': 'HR/ Industrial Relations', 'cid': 599},
                   {'cdesc': 'Instrumentation', 'cid': 554},
                   {'cdesc': 'International Business', 'cid': 601},
                   {'cdesc': 'Journalism / Mass Communication', 'cid': 595},
                   {'cdesc': 'Law', 'cid': 596},
                   {'cdesc': 'Literature', 'cid': 620},
                   {'cdesc': 'Marketing', 'cid': 527},
                   {'cdesc': 'Maths', 'cid': 517},
                   {'cdesc': 'Mechanical', 'cid': 557},
                   {'cdesc': 'Medicine and Health Sciences', 'cid': 621},
                   {'cdesc': 'Microbiology', 'cid': 541},
                   {'cdesc': 'Nuclear', 'cid': 561},
                   {'cdesc': 'Pharmacy', 'cid': 529},
                   {'cdesc': 'Philosophy', 'cid': 518},
                   {'cdesc': 'Physics', 'cid': 542},
                   {'cdesc': 'Production/Industrial', 'cid': 563},
                   {'cdesc': 'Science', 'cid': 507},
                   {'cdesc': 'Sociology', 'cid': 523},
                   {'cdesc': 'Statistics', 'cid': 543},
                   {'cdesc': 'Visual Arts', 'cid': 524},
                   {'cdesc': 'Other Arts', 'cid': 622},
                   {'cdesc': 'Other Engineering', 'cid': 562},
                   {'cdesc': 'Other Management', 'cid': 603},
                   {'cdesc': 'Other', 'cid': 506}],
         'pdesc': 'Ph.D/Doctorate',
         'pid': 138}]


TEMPLATE_DEFAULT_ENTITY_POSITION = {
    1:[
      {"pos":1,"entity_id":6,"alignment":"left"},   #Summary
      {"pos":2,"entity_id":1,"alignment":"right"},  #Personal
      {"pos":3,"entity_id":3,"alignment":"center"}, #Experience
      {"pos":4,"entity_id":2,"alignment":"left"},   #Education
      {"pos":5,"entity_id":4,"alignment":"right"},  #Projects
      {"pos":6,"entity_id":5,"alignment":"left"},   #Skills
      {"pos":7,"entity_id":9,"alignment":"right"},  #Languages
      {"pos":8,"entity_id":8,"alignment":"center"}, #Certifications   
      {"pos":9,"entity_id":10,"alignment":"left"},  #References
      {"pos":10,"entity_id":7,"alignment":"right"}   #Awards
    ],

    2:[],
    3:[],
    4:[],
    5:[]
}

TEMPLATE_ALLOW_LEFT_RIGHT_SWITCH = {1:True,
                                  2:False,
                                  3:False,
                                  4:False,
                                  5:False
                                  }
