# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-19 07:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('task_type', models.PositiveIntegerField(choices=[(0, 'Select_Type'), (1, 'AutoLogin Token Genaration')], default=0)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Failure'), (2, 'Success'), (3, 'Working')], default=0)),
                ('percent_done', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)])),
                ('file_uploaded', models.FileField(blank=True, max_length=200, upload_to='scheduler/uploads/', verbose_name='Uploaded')),
                ('file_generated', models.FileField(blank=True, max_length=200, upload_to='scheduler/uploads/', verbose_name='Generated')),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduler',
                'permissions': (('can_generate_auto_login_token_task_scheduler', 'Can Generate Autologin Token From Console'), ('can_view_completed_task_list_scheduler', 'Can View All Completed Task List From Console')),
                'verbose_name_plural': 'Schedulers',
            },
        ),
    ]
