# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import scheduler.functions


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='file_generated',
            field=models.FileField(blank=True, max_length=200, upload_to=scheduler.functions.get_scheduler_upload_path, verbose_name='Generated'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='file_uploaded',
            field=models.FileField(blank=True, max_length=200, upload_to=scheduler.functions.get_scheduler_upload_path, verbose_name='Uploaded'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='task_type',
            field=models.PositiveIntegerField(choices=[(0, 'Select_Type'), (1, 'AutoLogin Token Genaration'), (2, 'Upload Certificate'), (3, 'Upload Candidate Certificate')], default=0),
        ),
    ]
