# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-13 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20180329_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduler',
            options={'permissions': (('can_generate_auto_login_token_task_scheduler', 'Can Generate Autologin Token From Console'), ('can_view_completed_task_list_scheduler', 'Can View All Completed Task List From Console'), ('can_download_product_list', 'Can Download Product List from Console')), 'verbose_name': 'Scheduler', 'verbose_name_plural': 'Schedulers'},
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='task_type',
            field=models.PositiveIntegerField(choices=[(0, 'Select_Type'), (1, 'AutoLogin Token Genaration'), (2, 'Upload Certificate'), (3, 'Upload Candidate Certificate'), (4, 'Generate Product  List')], default=0),
        ),
    ]
