# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20180713_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='task_type',
            field=models.PositiveIntegerField(choices=[(0, 'Select_Type'), (1, 'AutoLogin Token Genaration'), (2, 'Upload Certificate'), (3, 'Upload Candidate Certificate'), (4, 'Generate Product  List'), (5, 'Encrypted URLs for Mailer')], default=0),
        ),
    ]
