# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20190117_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='task_type',
            field=models.PositiveIntegerField(choices=[(0, 'Select_Type'), (1, 'AutoLogin Token Genaration'), (2, 'Upload Certificate'), (3, 'Upload Candidate Certificate'), (4, 'Generate Product  List'), (5, 'Encrypted URLs for Mailer'), (6, 'Generate Compliance Report'), (7, 'Pixel Report Generation')], default=0),
        ),
    ]
