# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20190725_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduler',
            options={'permissions': (('can_generate_auto_login_token_task_scheduler', 'Can Generate Autologin Token From Console'), ('can_view_completed_task_list_scheduler', 'Can View All Completed Task List From Console'), ('can_download_product_list', 'Can Download Product List from Console'), ('can_generate_compliance_report', 'Can Download Compliance Report From Console'), ('order.can_download_discount_report', 'Can Download Discount Report')), 'verbose_name': 'Scheduler', 'verbose_name_plural': 'Schedulers'},
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='task_type',
            field=models.PositiveIntegerField(choices=[(0, 'Select_Type'), (1, 'AutoLogin Token Genaration'), (2, 'Upload Certificate'), (3, 'Upload Candidate Certificate'), (4, 'Generate Product  List'), (5, 'Encrypted URLs for Mailer'), (6, 'Generate Compliance Report'), (7, 'Pixel Report Generation'), (8, 'Discount Report Generation')], default=0),
        ),
    ]
