# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20170707_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='couponuser',
            options={'ordering': ['pk'], 'verbose_name': 'Coupon User', 'verbose_name_plural': 'Coupon Users'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='type',
        ),
        migrations.AddField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('money', 'Money based coupon'), ('percentage', 'Percentage discount')], default='percentage', max_length=20, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Maximum Deduction'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Minimum purchase Value'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Leave empty for coupons that never expire', null=True, verbose_name='Valid from'),
        ),
        migrations.AddField(
            model_name='couponuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponuser',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='couponuser',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Email'),
        ),
        migrations.AlterUniqueTogether(
            name='couponuser',
            unique_together=set([]),
        ),
    ]
