# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20170718_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('flat', 'Money based coupon'), ('percent', 'Percentage discount')], max_length=20, verbose_name='Type'),
        ),
    ]
