# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_auto_20170808_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('flat', 'Flat Discount'), ('percent', 'Percentage discount')], max_length=20, verbose_name='Type'),
        ),
    ]
