# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 05:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20171031_1043'),
        ('coupon', '0005_auto_20170821_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_scope',
            field=models.PositiveIntegerField(choices=[(0, 'ALL'), (1, 'PRODUCT'), (2, 'SOURCE')], default=0, verbose_name='Coupon Scope'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='couponproducts', to='shop.Product', verbose_name='Coupon Products'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='site',
            field=models.PositiveIntegerField(choices=[(0, 'ALL SITE'), (1, 'Learning'), (2, 'CRM')], default=0, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='source',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
