# Generated by Django 2.2.10 on 2020-07-03 11:36

from django.db import migrations, models
import shop.functions


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_coupon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.functions.get_upload_path_coupon, verbose_name='image'),
        ),
    ]
