# Generated by Django 2.2.10 on 2020-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_auto_20200703_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_msg',
            field=models.CharField(blank=True, help_text='This message will display when coupon limit exceeds', max_length=60, null=True, verbose_name='Message to be displayed'),
        ),
    ]
