# Generated by Django 2.2.10 on 2020-07-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_coupon_coupon_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, help_text='This will be display on description', max_length=255, null=True, verbose_name='Description to be displayed on mailers'),
        ),
    ]
