# Generated by Django 2.2.10 on 2020-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='mailers',
            field=models.BooleanField(default=False),
        ),
    ]
