export const UPDATE_UI = 'UPDATE_UI';
export const SHOW_TEMPLATE_MODAL = 'SHOW_TEMPLATE_MODAL';
export const HIDE_TEMPLATE_MODAL = 'HIDE_TEMPLATE_MODAL';
export const SHOW_SELECT_TEMPLATE_MODAL = 'SHOW_SELECT_TEMPLATE_MODAL';
export const SHOW_SUGGESTION_MODAL = 'SHOW_SUGGESTION_MODAL';
export const HIDE_SUGGESTION_MODAL = 'HIDE_SUGGESTION_MODAL';
export const HIDE_SELECT_TEMPLATE_MODAL = 'HIDE_SELECT_TEMPLATE_MODAL';
export const SELECT_CURRENT_FORM = 'SELECT_CURRENT_FORM';
export const SHOW_MORE_SECTION = 'SHOW_MORE_SECTION';
export const HIDE_MORE_SECTION = 'HIDE_MORE_SECTION';
export const SHOW_ALERT_MODAL = 'SHOW_ALERT_MODAL';
export const HIDE_ALERT_MODAL = 'HIDE_ALERT_MODAL';
export const SHOW_GENERATE_RESUME_MODAL = 'SHOW_GENERATE_RESUME_MODAL';
export const HIDE_GENERATE_RESUME_MODAL = 'HIDE_GENERATE_RESUME_MODAL';
export const SAVE_SUGGESTIONS = 'SAVE_SUGGESTIONS';
export const SET_SUGGESTION_TYPE = 'SET_SUGGESTION_TYPE';
export const UPDATE_PREVIEW_CLICK_STATUS = 'UPDATE_PREVIEW_CLICK_STATUS';
export const SHOW_HELP_MODAL = 'SHOW_HELP_MODAL';
export const HIDE_HELP_MODAL = 'HIDE_HELP_MODAL';



