export const UPDATE_UI = 'UPDATE_UI';
export const SHOW_TEMPLATE_MODAL = 'SHOW_TEMPLATE_MODAL';
export const HIDE_TEMPLATE_MODAL = 'HIDE_TEMPLATE_MODAL';
export const SHOW_SELECT_TEMPLATE_MODAL = 'SHOW_SELECT_TEMPLATE_MODAL';
export const HIDE_SELECT_TEMPLATE_MODAL = 'HIDE_SELECT_TEMPLATE_MODAL';