export const UPDATE_MAIN_PAGE_LOADER = 'UPDATE_MAIN_PAGE_LOADER'
export const UPDATE_DATA_LOADER = 'UPDATE_DATA_LOADER'
export const FETCH_LOADER_STATUS = 'FETCH_LOADER_STATUS'
export const CHANGE_FORM_NAME = 'CHANGE_FORM_NAME'
export const SAVE_SUGGESTIONS = 'SAVE_SUGGESTIONS';
export const SET_SUGGESTION_TYPE = 'SET_SUGGESTION_TYPE';

