export const UPDATE_MAIN_PAGE_LOADER = 'UPDATE_MAIN_PAGE_LOADER'
export const UPDATE_DATA_LOADER = 'UPDATE_DATA_LOADER'
export const FETCH_LOADER_STATUS = 'FETCH_LOADER_STATUS'
export const CHANGE_FORM_NAME = 'CHANGE_FORM_NAME'
export const SAVE_SUGGESTIONS = 'SAVE_SUGGESTIONS';
export const SET_SUGGESTION_TYPE = 'SET_SUGGESTION_TYPE';
export const FETCH_ALERT_MODAL_STATUS = 'FETCH_ALERT_MODAL_STATUS';
export const UPDATE_ALERT_MODAL_STATUS = 'UPDATE_ALERT_MODAL_STATUS';
export const SHOW_GENERATE_RESUME_MODAL = 'SHOW_GENERATE_RESUME_MODAL';
export const HIDE_GENERATE_RESUME_MODAL = 'HIDE_GENERATE_RESUME_MODAL';
export const SHOW_HELP_MODAL = 'SHOW_HELP_MODAL'
export const HIDE_HELP_MODAL = 'HIDE_HELP_MODAL'
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';


