



export const UPLOAD_FILE_URL = 'UPLOAD_FILE_URL';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const EXPERT_FORM_SUBMIT ='EXPERT_FORM_SUBMIT';
export const CHECK_SESSION_AVAILABILITY = 'CHECK_SESSION_AVAILABILITY';
export const GET_CANDIDATE_ID = "GET_CANDIDATE_ID"
export const GET_CANDIDATE_RESUME = "GET_CANDIDATE_RESUME"
export const GET_CANDIDATE_SCORE = 'GET_CANDIDATE_SCORE'
export const GET_CANDIDATE_INFO = 'GET_CANDIDATE_INFO'